### ISSUE TITLE
Add support for embedding a Grid of iframes on the UI

### ISSUE THREAD

**Issue by tchaton** [Lightning-AI/pytorch-lightning#13496]
## 🚀 Feature

When creating a collection of works with their own UI, the only option is to create a tab for each one of them. Unfortunately, I had X works, this would probably don't work well.

I believe it would be interesting to investigate the introduction of arrangement on the UI while embedding the iframe.

The simplest one that I can think of is the Grid.

Here is the possible API.

```py
from lightning import LightningFlow
from lightning.app.frontend.layout import Grid

class Flow(LightningFlow):

    def configure_layout():
        tab = [{"name": "Sagemaker": "content": ...}]
        tab_grid = [{"name": "Sweep": "content": Grid(*[
            {"name": w.name, "content": w} for w in self.works()
        ])}]
        return tab + tab_grid
```

### Additional context

______________________________________________________________________

#### If you enjoy Lightning, check out our other projects! ⚡

- [**Metrics**](https://github.com/Lightning-AI/metrics): Machine learning metrics for distributed, scalable PyTorch applications.

- [**Lite**](https://pytorch-lightning.readthedocs.io/en/latest/starter/lightning_lite.html): enables pure PyTorch users to scale their existing code on any kind of device while retaining full control over their own loops and optimization logic.

- [**Flash**](https://github.com/Lightning-AI/lightning-flash): The fastest way to get a Lightning baseline! A collection of tasks for fast prototyping, baselining, fine-tuning, and solving problems with deep learning.

- [**Bolts**](https://github.com/Lightning-AI/lightning-bolts): Pretrained SOTA Deep Learning models, callbacks, and more for research and production with PyTorch Lightning and PyTorch.

- [**Lightning Transformers**](https://github.com/Lightning-AI/lightning-transformers): Flexible interface for high-performance research using SOTA Transformers leveraging Pytorch Lightning, Transformers, and Hydra.

cc @borda

**Comment by alecmerdler** [comment]
There can be performance implications with rendering too many (10+) `iframes` on a single page at the same time. Basically, the browser is restricted on how many HTTP connections it can have open at once, and when 10+ `iframes` are all loading in their HTML/CSS/JS/fonts/images/etc, it can cause the page to load very slowly (more than a minute, depending on internet speed).

I agree we should explore different ways to declaratively generate layouts for app UIs, but I'm not sure that adding more `iframes` is the answer. If anyone in the community has experience with this type of thing, we would love to hear your thoughts.
