### ISSUE TITLE
404 page not found error for all "Web UIs * " pages in the Intermediate skills Level 10 docs.

### ISSUE THREAD

**Issue by Nachimak28** [Lightning-AI/pytorch-lightning#13891]
## 📚 Documentation

Hi lightning team
I've been browsing through the documentation for the "App building skills" pages and found that all the card links for "Web UIs for non JS devs" as well as "Web UIs for non JS devs" pages return a 404 page not found error.  
To be specific I'm talking about the cards such as "Dash", "Gradio" etc

![image](https://user-images.githubusercontent.com/23210132/181347588-acb71b8c-d73a-4c02-a721-6d082f943123.png)

I did see the relevant pages being present in the `docs/workflows/add_web_ui/` folder in the repo but they don't show up even after I build locally (as per commands given in README). 
I could have created a PR but I'm a total noob when it comes to sphinx documentation making and building.
I'm ready to give this a shot and fix it with some guidance on sphinx doc generation and how its organized. 

______________________________________________________________________

#### If you enjoy Lightning, check out our other projects! ⚡

- [**Metrics**](https://github.com/Lightning-AI/metrics): Machine learning metrics for distributed, scalable PyTorch applications.

- [**Lite**](https://pytorch-lightning.readthedocs.io/en/latest/starter/lightning_lite.html): enables pure PyTorch users to scale their existing code on any kind of device while retaining full control over their own loops and optimization logic.

- [**Flash**](https://github.com/Lightning-AI/lightning-flash): The fastest way to get a Lightning baseline! A collection of tasks for fast prototyping, baselining, fine-tuning, and solving problems with deep learning.

- [**Bolts**](https://github.com/Lightning-AI/lightning-bolts): Pretrained SOTA Deep Learning models, callbacks, and more for research and production with PyTorch Lightning and PyTorch.

- [**Lightning Transformers**](https://github.com/Lightning-AI/lightning-transformers): Flexible interface for high-performance research using SOTA Transformers leveraging PyTorch Lightning, Transformers, and Hydra.

**Comment by alexandercort** [comment]
@Felonious-Spellfire FYI
