### ISSUE TITLE
LightningFlow state increases indefinitely

### ISSUE THREAD

**Issue by belerico** [Lightning-AI/pytorch-lightning#13944]
## 🐛 Bug

I don't know if this can be considered as a bug, but the LightningFlow state increases indefinitely.

### To Reproduce

```python
import subprocess
from typing import Any, Dict, Optional

import lightning as L
from pympler import asizeof
from pytorch_lightning.loggers import TensorBoardLogger


class TensorboardWork(L.LightningWork):
    """Tensorboard logger as a LightningWork

    Args:
        local_log_dir (str): where to save logs.
        **work_kwargs: additional arguments to pass to LightningWork.
    """

    def __init__(self, local_log_dir: str = "logs", **work_kwargs):
        super().__init__(**work_kwargs)
        self.local_log_dir = local_log_dir
        self._logger = TensorBoardLogger(self.local_log_dir)
        self._tensorboard_started = False

    @property
    def tensorboard_url(self) -> str:
        return self.url

    @property
    def tensorboard_log_dir(self) -> str:
        return self._logger.log_dir

    def run(self, episode_counter: int, metrics: Optional[Dict[str, Any]] = None):
        if not self._tensorboard_started:
            subprocess.Popen(
                [
                    "tensorboard",
                    "--logdir",
                    self.local_log_dir,
                    "--host",
                    self.host,
                    "--port",
                    str(self.port),
                ]
            )
            self._tensorboard_started = True
        if metrics is not None:
            self._logger.log_metrics(metrics, episode_counter)


class SimpleWork(L.LightningWork):
    def __init__(self, **work_kwargs):
        super().__init__(**work_kwargs)
        self.counter = 0

    def run(self, signal: int):
        self.counter += 1


class SimpleFlow(L.LightningFlow):
    def __init__(self):
        super().__init__()
        self.work0 = SimpleWork(parallel=True, cache_calls=True)
        self.work1 = SimpleWork(parallel=True, cache_calls=True)
        self.logger = TensorboardWork()

    def run(self):
        self.work0.run(self.work1.counter)
        if self.work0.counter > 0:
            self.work1.run(self.work0.counter)
        self.logger.run(self.work0.counter, {"State": asizeof.asizeof(self.state)})

    def configure_layout(self):
        tabs = [{"name": "Logs", "content": self.logger.tensorboard_url}]
        return tabs


if __name__ == "__main__":
    app = L.LightningApp(SimpleFlow())
```

### Expected behavior

The LightningFlow state size should be bounded, specially if one doesn't need all the cached-calls history. This can be useful when there are a lot of interactions between flows and works during the lifecycle of an app (e.g. in here: https://github.com/belerico/lightning-rl)

### Environment

* CUDA:
        - GPU:
        - available:         False
        - version:           10.2
* Packages:
        - lightning:         2022.7.18
        - lightning_app:     0.5.3
        - numpy:             1.22.4
        - pyTorch_debug:     False
        - pyTorch_version:   1.10.2+cu102
        - pytorch-lightning: 1.6.5
        - tqdm:              4.64.0
        - pympler: 1.0.1
* System:
        - OS:                Linux
        - architecture:
                - 64bit
                - ELF
        - processor:         x86_64
        - python:            3.8.13

### Additional context

A raw patch that i've made was to modify the following:

* LightningFlow:
  ```python
  def set_state(self, provided_state: Dict) -> None:
	    """Method to set the state to this LightningFlow, its children and
	    :class:`~lightning.core.lightning_work.LightningWork`."""
	    for k, v in provided_state["vars"].items():
		if isinstance(v, Dict):
		    v = _maybe_create_drive(self.name, v)
		setattr(self, k, v)
	    self._changes = provided_state["changes"]
	    if len(provided_state["calls"]) > 1:
		last_calls_key = list(provided_state["calls"].keys())[-1]
		latest_call_hash = provided_state["calls"]["latest_call_hash"]
		if latest_call_hash in provided_state["calls"]:
		    self._calls = {
		        "latest_call_hash": latest_call_hash,
		        latest_call_hash: provided_state["calls"][latest_call_hash],
		        last_calls_key: provided_state["calls"][last_calls_key],
		    }
	    else:
		self._calls.update(provided_state["calls"])
	    for child, state in provided_state["flows"].items():
		getattr(self, child).set_state(state)
	    for work, state in provided_state["works"].items():
		getattr(self, work).set_state(state)
	    for structure, state in provided_state["structures"].items():
		getattr(self, structure).set_state(state)

  ```
* LightningWork:
  ```python
  def set_state(self, provided_state):
	    for k, v in provided_state["vars"].items():
		if isinstance(v, Dict):
		    v = _maybe_create_drive(self.name, v)
		setattr(self, k, v)
	    self._changes = provided_state["changes"]
	    if len(provided_state["calls"]) > 1:
		last_calls_key = list(provided_state["calls"].keys())[-1]
		latest_call_hash = provided_state["calls"]["latest_call_hash"]
		if latest_call_hash in provided_state["calls"]:
		    self._calls = {
		        "latest_call_hash": latest_call_hash,
		        latest_call_hash: provided_state["calls"][latest_call_hash],
		        last_calls_key: provided_state["calls"][last_calls_key],
		    }
	    else:
		self._calls.update(provided_state["calls"]) 
  ```
* In `proxies.py`:
  ```python
     # 8. Deepcopy the work state and send the first `RUNNING` status delta to the flow.
	state = deepcopy(self.work.state)
	if call_hash not in self.work._calls:
	    self.work._calls["latest_call_hash"] = call_hash
	    self.work._calls[call_hash] = called["state"]["calls"][call_hash]
	else:
	    self.work._calls["latest_call_hash"] = call_hash
	self.work._calls[call_hash]["statuses"].append(make_status(WorkStageStatus.RUNNING))
	self.delta_queue.put(ComponentDelta(id=self.work_name, delta=Delta(DeepDiff(state, self.work.state)))) 
  ```
  
### Results

![image](https://user-images.githubusercontent.com/18405289/182017149-1909bb67-49c2-4b83-b89b-b2a6b7e10f1a.png)

* Orange: state size without the above changes (default)
* Blue: state size with the above changes
  

cc @tchaton @rohitgr7

**Comment by tchaton** [comment]
Hey @belerico,

Thanks for sharing the code above. I am looking into this. I will keep you updated.

Best,
T.C

**Comment by tchaton** [comment]
Hey @belerico Would you mind trying out https://github.com/Lightning-AI/lightning/pull/13970 branch? Normally, this should work better now.

**Comment by manskx** [comment]
This might be related: https://github.com/Lightning-AI/lightning/issues/13780

**Comment by belerico** [comment]
> Hey @belerico Would you mind trying out #13970 branch? Normally, this should work better now.

Hi @tchaton, thank you for the quick response. I've just tried it with the code that I shared above. Those are the results that i've obtained:

![image](https://user-images.githubusercontent.com/18405289/182229353-6ca19845-7c3d-4e0c-bfb9-0a974fb25d7e.png)

They green line is the one obtained with your fixes. It's a lot better, but in some cases, where there's a lot more interactions between components, it could become prohibitive.

Is there maybe the possibility for the user to specify how many history wants to be saved?

**Comment by tchaton** [comment]
Actually, my updated PR is even worse but not as bad as the orange one, roughly twice better, but the important part is that the circulating hidden state is constant in size. 

In your code, you are assuming a user won't put twice the state inputs in the run method once it has succeeded, which causes call_hashes not to be stored.

Right now, even if the state increases, it is done on the flow side only, so it isn't that bad. We will probably end up storing the statuses in a database to ensure the reliability of the system.

> Is there maybe the possibility for the user to specify how much history wants to be saved?
Probably, but I don't think this is required now that the circulating state is fixed. [Here](https://github.com/Lightning-AI/lightning/pull/13970/files#diff-5347e507417db0b69cdee291b23e64f0105cf382f743f8f2d7e60f308cf05b5dR70), I am skipping all the old keys as the work doesn't need them.

Would you mind trying out my updated branch with your app and sharing the experience?

Best,
T.C
