### ISSUE TITLE
pyright flags `__version__` as not being exported from module `pytorch_lightning`

### ISSUE THREAD

**Issue by rsokl** [Lightning-AI/pytorch-lightning#13996]
![image](https://user-images.githubusercontent.com/29104956/182516679-604a5ab5-be9f-4bc5-8051-9f3795ca37dc.png)

It looks like this is caused by the changes made by https://github.com/Lightning-AI/lightning/pull/13327

cc @tchaton @rohitgr7

**Comment by Borda** [comment]
This is serviced by an alternative leading from a separate file:
https://github.com/Lightning-AI/lightning/blob/ee4233b36cb70b19a13013371ada50875b429ef3/src/pytorch_lightning/__init__.py#L9L10

**Comment by rsokl** [comment]
>This is serviced by an alternative leading from a separate file:

I understand that, but I presume the code pattern that I posted above is still a valid way to check the version of library. Is this the case? If so, the vast majority of vscode users will see this error message, since pyright is at the core of VSCode's python support.

I tried to add a `__all__ = ["__version__"]` to `pytorch_lightning/__init__.py` and was surprised to see that it did not seem to fix the   error. You might consider opening an issue on the pyright GitHub discussion board if you are unable to figure out a remedy for this.

Here is code to reproduce:

[Install pyright](https://github.com/microsoft/pyright#command-line)

```python
# check_pyright.py
import pytorch_lightning

pytorch_lightning.__version__
```

```console
$ pyright check_pyright.py
Loading configuration file at C:\Users\Ryan Soklaski\responsible-ai-toolbox\pyrightconfig.json
Assuming Python version 3.9
Assuming Python platform Windows
stubPath C:\Users\Ryan Soklaski\responsible-ai-toolbox\typings is not a valid directory.
Searching for source files
Found 1 source file
pyright 1.1.265
C:\Users\Ryan Soklaski\responsible-ai-toolbox\scratch\check_pyright.py
  C:\Users\Ryan Soklaski\responsible-ai-toolbox\scratch\check_pyright.py:3:19 - error: "__version__" is not exported from module "pytorch_lightning" (reportPrivateImportUsage)
1 error, 0 warnings, 0 informations
Completed in 0.892sec
```

**Comment by Borda** [comment]
> I tried to add a `__all__ = ["__version__"]` to `pytorch_lightning/__init__.py` and was surprised to see that it did not seem to fix the error.

I am not surprised as the `__all__` is for `from pytorch_lightning import *`
