### ISSUE TITLE
reload-dataloaders-every-n-epochs has outdated documentation

### ISSUE THREAD

**Issue by KralaBenjamin** [Lightning-AI/pytorch-lightning#14210]
## 📚 Documentation

The pseudocode seems to be wrong in [the documention about trainer](https://pytorch-lightning.readthedocs.io/en/stable/common/trainer.html#reload-dataloaders-every-n-epochs) , because according to this [answer](https://github.com/Lightning-AI/lightning/issues/14093) , trainer reloads it from the datamodule, not the model. Viewing the changelogs the current description looks outdated.

______________________________________________________________________

#### If you enjoy Lightning, check out our other projects! ⚡

- [**Metrics**](https://github.com/Lightning-AI/metrics): Machine learning metrics for distributed, scalable PyTorch applications.

- [**Lite**](https://pytorch-lightning.readthedocs.io/en/latest/starter/lightning_lite.html): enables pure PyTorch users to scale their existing code on any kind of device while retaining full control over their own loops and optimization logic.

- [**Flash**](https://github.com/Lightning-AI/lightning-flash): The fastest way to get a Lightning baseline! A collection of tasks for fast prototyping, baselining, fine-tuning, and solving problems with deep learning.

- [**Bolts**](https://github.com/Lightning-AI/lightning-bolts): Pretrained SOTA Deep Learning models, callbacks, and more for research and production with PyTorch Lightning and PyTorch.

- [**Lightning Transformers**](https://github.com/Lightning-AI/lightning-transformers): Flexible interface for high-performance research using SOTA Transformers leveraging PyTorch Lightning, Transformers, and Hydra.

cc @borda @rohitgr7 @justusschock @awaelchli @ninginthecloud @otaj @carmocca @ananthsub @jjenniferdai

**Comment by awaelchli** [comment]
@KralaBenjamin The pseudo code is not very wrong, it's just overly simplified to get a simple message across. The real code has a bit more stuff going on. In Lightning, the dataloaders can come from different sources: 1) passed in directly to fit, 2) from the datamodule, 3) from the lightning module. 

The focus of the code snippet you point out is in how the `reload-dataloaders-every-n-epochs ` is used, and is less about where the dataloader comes from. 

What would you like to see changed? Perhaps you could open a PR with a suggestion? Perhaps all the code snippet needs is a small comment saying that the datamodule takes precedence.

**Comment by KralaBenjamin** [comment]
@awaelchli Thank you very much for the answer.
The reason why I opened the issue, was my confusion caused by the pseudo code. Though I used a datamodule
I thought I need to change my LM according to the pseudo code. Also in most cases I found in the internet LM and data handling were seperated. ( e.g. with a LDM)

My correction would be:

"
Reload the dataloaders (training, validation and test) from the data source (in most cases a datamodule)
```python 

# if 0 (default)
train_loader = datamodule.train_dataloader()
for epoch in epochs:
    for batch in train_loader:
        ...

# if a positive integer
for epoch in epochs:
    if not epoch % reload_dataloaders_every_n_epochs:
        train_loader = datamodule.train_dataloader()
    for batch in train_loader:
        ...

```
"

if you generally fine with the correction I would open a PR.

**Comment by awaelchli** [comment]
I mean nothing is wrong with what you have there, but someone could come and say "I don't use a datamodule, so the pseudo code is wrong, it should say `model.train_dataloader`". Do you see that the argument can go both ways? 

So it's probably more appropriate to put a comment there.

**Comment by rohitgr7** [comment]
I think we can just do
```py
train_loader = train_dataloader_source()
```

and add a note there
```
train_dataloader_source can be...
1) from the datamodule, 2) from the lightning module.
```
