### ISSUE TITLE
Header missing on local doc generation

### ISSUE THREAD

**Issue by Felonious-Spellfire** [Lightning-AI/pytorch-lightning#14647]
## 🐛 Bug

When generating the documentation for source-app, source-pytorch, and source-lit, the generated HTML files do not have a header.

### To Reproduce

The results are the same using conda Windows and conda Ubuntu with the following versions of Python: 3.8, 3.9, 3.10.

1. Clone the Lightning repo
2. In the root directory run the following: 
pip install -r requirements/app/docs.txt -U
pip install -e .
3. Run any of the following commands to generate docs:
python -m sphinx -b html -W --keep-going docs/source-app docs/build
or
python -m sphinx -b html -W --keep-going docs/source-pytorch docs/build
or
python -m sphinx -b html -W --keep-going docs/source-lit docs/build
4. Go to the build directory and open the index.html file (or any HTML file in the build directory).

The HTML output does not have a header.

### Expected behavior

The HTML output for locally generated docs has a header

### Environment

The results are the same using conda Windows and conda Ubuntu with the following versions of Python: 3.8, 3.9, 3.10.

cc @borda @rohitgr7 @Felonious-Spellfire

**Comment by awaelchli** [comment]
This was fixed in the meantime, when the template was reworked 👍
