### ISSUE TITLE
Default Python Version on cloud

### ISSUE THREAD

**Issue by aniketmaurya** [Lightning-AI/pytorch-lightning#14747]
## 🚀 Feature

Right now the default Python version on the cloud is 3.8 and there is no way to specify it. I want to use the shutdown of the `ThreadPoolExecutor` with the `cancel_futurers` argument which is only available in Python>=3.9

### Additional context

cc: @hhsecond 

______________________________________________________________________

#### If you enjoy Lightning, check out our other projects! ⚡

- [**Metrics**](https://github.com/Lightning-AI/metrics): Machine learning metrics for distributed, scalable PyTorch applications.

- [**Lite**](https://pytorch-lightning.readthedocs.io/en/latest/starter/lightning_lite.html): enables pure PyTorch users to scale their existing code on any kind of device while retaining full control over their own loops and optimization logic.

- [**Flash**](https://github.com/Lightning-AI/lightning-flash): The fastest way to get a Lightning baseline! A collection of tasks for fast prototyping, baselining, fine-tuning, and solving problems with deep learning.

- [**Bolts**](https://github.com/Lightning-AI/lightning-bolts): Pretrained SOTA Deep Learning models, callbacks, and more for research and production with PyTorch Lightning and PyTorch.

- [**Lightning Transformers**](https://github.com/Lightning-AI/lightning-transformers): Flexible interface for high-performance research using SOTA Transformers leveraging PyTorch Lightning, Transformers, and Hydra.

cc @borda

**Comment by awaelchli** [comment]
Maybe platform could provide a set of base images that we can choose from via build config or similar? 

@aniketmaurya In the mean time, you can implement the `cancel_futurers` using [this method](https://stackoverflow.com/questions/65443612/gracefully-exit-using-threadpoolexecutor).

**Comment by aniketmaurya** [comment]
Sure I'll use this solution. Thanks for sharing Adrian 🔥

**Comment by aniketmaurya** [comment]
Yes, some features are not available in `3.7` which are there in `3.9`, so maybe a way to select the Python version would be awesome 😄

**Comment by awaelchli** [comment]
Closing. The Python version can be changed in Lightning AI Studio in the environment settings now. This is probably the closes we will get to "specify the Python version" for apps.
