### ISSUE TITLE
Error when running lightning install app lightning/quick-start

### ISSUE THREAD

**Issue by OstaptsovDanil** [Lightning-AI/pytorch-lightning#15147]
### Bug description
![image](https://user-images.githubusercontent.com/64201643/195980692-e2a50a8a-c42a-429e-99dd-83e2f16bfe9f.png)

I cloned the rep `lightning install app lightning/quick-start` led to this
![image](https://user-images.githubusercontent.com/64201643/195978781-0705ed37-ad35-4e06-a0c7-b9dcc8cb6f49.png)
and it does not do `pip install -r requirements.txt`

### Error messages and logs

```

# Error messages and logs here please

```

### Environment

```

#- Lightning Component - LightningApp
#- Lightning App Version: 0.6.3
#- Python version: 3.8
#- OS Windows 11
#- CUDA/cuDNN version - no used
#- GPU models and configuration: NVidia GeForce GTX 1650TI mobile
#- How you installed Lightning: conda and pip
#- Running environment of LightningApp: local

```

**Comment by lantiga** [comment]
Hi @OstaptsovDanil, can you please paste the complete output you get on the console starting from a clean environment?

**Comment by OstaptsovDanil** [comment]
Hello @lantiga, yes of course. I still have these screenshots
![image](https://user-images.githubusercontent.com/64201643/196249960-4fc26132-49b8-4c6e-a257-d314cccf1e47.png)
![image](https://user-images.githubusercontent.com/64201643/196250117-d819cd5a-639d-4b12-88b2-53ec1d330353.png)
![image](https://user-images.githubusercontent.com/64201643/196250196-9be40b23-a6c6-48ee-90d6-673ad2160887.png)
![image](https://user-images.githubusercontent.com/64201643/196250234-00fe973d-e967-4497-9dc5-73cad0574fb9.png)

**Comment by krishnakalyan3** [comment]
Reached out via slack DM :). Perhaps we can get you unblocked over a call.

**Comment by yurijmikhalevich** [comment]
I tried and wasn't able to reproduce this. Danil says he didn't do anything special; he hit enter a few times, but this shouldn't have caused the issue anyway, [the code that handles the enter press](https://github.com/Lightning-AI/lightning/blob/a7f2d119c52ad450ef849e420eecd09f1ac677a9/src/lightning_app/cli/cmd_install.py#L92-L108) looks good 🤔

@OstaptsovDanil, can you please try and see if you can reproduce the issue?
