### ISSUE TITLE
Add sagemaker experiment as Logger

### ISSUE THREAD

**Issue by josete89** [Lightning-AI/pytorch-lightning#15718]
## 🚀 Feature

Create a new logger class which send the metrics to sagemaker experiments using the sagemaker experiments sdk

### Motivation

Since we use sagemaker in our daily basis for training models it’s a bit cumbersome to create regular expressions to parse the progres bar in order to get meaningful metrics in the UI.

### Pitch

Having available a logger class which makes really easy to display the metrics of the training in sagemaler

### Alternatives

Create a custom progress bar and a set of regular expression to parse this

### Additional context

I think this is somehow related to https://github.com/Lightning-AI/lightning/issues/12185

______________________________________________________________________

#### If you enjoy Lightning, check out our other projects! ⚡

- [**Metrics**](https://github.com/Lightning-AI/metrics): Machine learning metrics for distributed, scalable PyTorch applications.

- [**Lite**](https://pytorch-lightning.readthedocs.io/en/latest/starter/lightning_lite.html): enables pure PyTorch users to scale their existing code on any kind of device while retaining full control over their own loops and optimization logic.

- [**Flash**](https://github.com/Lightning-AI/lightning-flash): The fastest way to get a Lightning baseline! A collection of tasks for fast prototyping, baselining, fine-tuning, and solving problems with deep learning.

- [**Bolts**](https://github.com/Lightning-AI/lightning-bolts): Pretrained SOTA Deep Learning models, callbacks, and more for research and production with PyTorch Lightning and PyTorch.

- [**Lightning Transformers**](https://github.com/Lightning-AI/lightning-transformers): Flexible interface for high-performance research using SOTA Transformers leveraging PyTorch Lightning, Transformers, and Hydra.

cc @borda @awaelchli @Blaizzy

**Comment by awaelchli** [comment]
@tsenst As you already learned, Lightning doesn't integrate more loggers at the moment. For context, this is not against any particular framework or to favor others, but simply because of the maintenance effort we can't keep up, even with the help of the community, this is difficult at the moment. 

Your package looks great btw! Thanks for sharing. 
We could find a place in our logger docs to list external implementations. What do you think?

**Comment by tsenst** [comment]
@awaelchli I can understand that. Yes it would be very nice if you could link my repo. I also made a blog post https://medium.com/idealo-tech-blog/experiment-tracking-with-aws-sagemaker-and-pytorch-lightning-68b22fd4deee to explain how to use it. But link to the repo will totaly enough
