### ISSUE TITLE
Replace `tmpdir` usage with `tmp_path` in our tests

### ISSUE THREAD

**Issue by carmocca** [Lightning-AI/pytorch-lightning#16188]
### Outline & Motivation

`tmpdir` is considered legacy:

> The tmpdir and tmpdir_factory fixtures are similar to tmp_path and tmp_path_factory, but use/return legacy [py.path.local](https://py.readthedocs.io/en/latest/path.html) objects rather than standard [pathlib.Path](https://docs.python.org/3/library/pathlib.html#pathlib.Path) objects.

(from https://docs.pytest.org/en/7.1.x/how-to/tmp_path.html#the-tmpdir-and-tmpdir-factory-fixtures)

### Pitch

Run pytest with `pytest -p no:legacypath` as the link above suggests and replace all occurrences.

This can be added in https://github.com/Lightning-AI/lightning/blob/94e6d52b7e2f2a9ffc21f7e11e087808666fe710/setup.cfg#L28-L32

```diff
 addopts =
     --strict-markers
     --doctest-modules
     --color=yes
     --disable-pytest-warnings
     --ignore=legacy/checkpoints
+    -p no:legacypath
```

Replace all `tmpdir` usages

cc @borda

**Comment by Saumya-ranjan** [comment]
Hello @carmocca ! I would like to Contribute My first Open Source Contribution. If there is something I could help you out with or fix some issues Please do ping me.
Also if this issue is open can you please assign it to me?

**Comment by carmocca** [comment]
Go ahead!

**Comment by yhl48** [comment]
Happy to contribute to this issue if no one has been assigned to it!

**Comment by subham73** [comment]
Hello, @yhl48 are you still working on this? I'm planning to work on this, would love to have your input on this. Thanks

**Comment by Aditi840** [comment]
@carmocca, in which file tmpdir with tmp_path should be replaced

**Comment by Borda** [comment]
> @carmocca, in which file tmpdir with tmp_path should be replaced

in all files :)

**Comment by Aditi840** [comment]
All files of lightning-AI, can I work on it.

**Comment by Aditi840** [comment]
All files of lightning-AI, can I work on it.

**Comment by Borda** [comment]
Let's split is per topic:
- [ ] integrations_app + legacy
- [ ] parity_fabric + parity_pytorch
- [ ] tests_app
- [ ] tests_data + tests_store
- [ ] tests_fabric
- [ ] tests_pytorch
- [ ] tests_store

**Comment by Aditi840** [comment]
May I do the above 4 files.

**Comment by Aditi840** [comment]
@Borda Got it, replacements have to be done on tests file, I'm starting working on tests files.

**Comment by Aditi840** [comment]
@Borda  will you please check my pull request and the changes I have done.

**Comment by Borda** [comment]
> @Borda will you please check my pull request and the changes I have done.

I think it would be easier/faster if you create a PR per check item here: https://github.com/Lightning-AI/lightning/issues/16188#issuecomment-1691189400

**Comment by Aditi840** [comment]
@Borda , what we should do files, give me a idea

**Comment by Borda** [comment]
> @Borda , what we should do files, give me a idea

Let's create another PR and perform replacement just for one sub folder as listed in comment/check-list above...

**Comment by Aditi840** [comment]
@Borda what replacement do we need to perform and on which sub-folder

**Comment by Borda** [comment]
> @Borda what replacement do we need to perform and on which sub-folder

Could you please ping me on slack, would be easier to explain =)

**Comment by Aditi840** [comment]
@Borda , yaa sure tell me your slack Id

**Comment by Borda** [comment]
> @Borda , yaa sure tell me your slack Id

You can find me as Jirka :)
I made a sample partial fix, so based on partitions in https://github.com/Lightning-AI/lightning/issues/16188#issuecomment-1691189400, I just chose a topic/folder and tried to apply changes...

1. chose one folder and create a draft PR (which can be almost empty) that we can link the issues
2. take it file by file and perform replacement
3. I would suggest each file change shall be one commit in the PR so it is easier to trace what changes are not compatible

**Comment by Aditi840** [comment]
@Borda ok, will do that.

**Comment by fnhirwa** [comment]
@Borda is this still open for contribution, I would love to work on it 😊
