### ISSUE TITLE
Most of the docs links in old issues give a 404 page

### ISSUE THREAD

**Issue by matifali** [Lightning-AI/pytorch-lightning#16376]
### 📚 Documentation

For example in issue https://github.com/Lightning-AI/lightning/issues/10841
The link https://pytorch-lightning.readthedocs.io/en/latest/api/pytorch_lightning.core.lightning.html#pytorch_lightning.core.lightning.LightningModule.test_step does not work

There are many more that community can contribute. 

cc @borda

**Comment by Borda** [comment]
I think it is expected that these 2+ years links to docs that were back then considered as the latest won't work... probably the best was would replace all `latest` or `stable` with a specific version like `1.3.5` which was meant to back then...

**Comment by Borda** [comment]
@yurijmikhalevich could you check it this seems related to our deployment if I got to https://lightning.ai/docs/pytorch/1.9.3/api/ I can see this page/file there `pytorch_lightning.core.LightningModule.html`

**Comment by GregorySech** [comment]
One more thing, seems like the pages for the `lightning_fabric` are working correctly. I've tried a dozen of the other namespaces and they all are broken.

**Comment by Borda** [comment]
> One more thing, seems like the pages for the `lightning_fabric` are working correctly. I've tried a dozen of the other namespaces and they all are broken.

what link do you mean? https://lightning.ai/docs/fabric/stable/

**Comment by GregorySech** [comment]
> > One more thing, seems like the pages for the `lightning_fabric` are working correctly. I've tried a dozen of the other namespaces and they all are broken.
> 
> what link do you mean? https://lightning.ai/docs/fabric/stable/

I didn't specify that I was referring to the API page you shared (https://lightning.ai/docs/pytorch/1.9.3/api/). There the lightning_fabric.* links were the only ones working but the rest were 404s. 

Now they are working however if I go to https://lightning.ai/docs/pytorch/latest/past_versions.html in the docs navbar I still get 404.

**Comment by matifali** [comment]
@awaelchli, This should be closed as not planned if there are no plans to fix old links. They still give a 404.

**Comment by Borda** [comment]
> @awaelchli, This should be closed as not planned if there are no plans to fix old links. They still give a 404.

We may add custom redirect (there is an option in Sphinx) to some most often, do you have such list or suggestions?

**Comment by matifali** [comment]
@Borda, I would advise running a GraphQL query to get a list of all links in all issue comments, checking if they are 404, and adding redirects for all those.
