### ISSUE TITLE
Update the URL to UI

### ISSUE THREAD

**Issue by Borda** [Lightning-AI/pytorch-lightning#16580]
### Outline & Motivation

Update the URL to the release in GitHub once the PL app repo is public

https://github.com/Lightning-AI/lightning/blob/e4c3441b25a8c194a873c8850e9507771de7053c/src/lightning_app/cli/cmd_pl_init.py#L118

@alecmerdler @yurijmikhalevich I believe it is a reference to this one: https://github.com/Lightning-AI/lightning-ui

cc @borda @justusschock @awaelchli

**Comment by awaelchli** [comment]
@Borda this is for the PyTorch Lightning App. This is basically dead code, unmaintained. We should nuke the entire thing.

**Comment by rhiga2** [comment]
Hi, was wondering if this issue is still open?

**Comment by Borda** [comment]
> @Borda this is for the PyTorch Lightning App. This is basically dead code, unmaintained. I would nuke the entire thing.

OK with me
