### ISSUE TITLE
Coverage report on Codecov is messed up after package restructure

### ISSUE THREAD

**Issue by awaelchli** [Lightning-AI/pytorch-lightning#16660]
### Bug description

The code coverage report on [Codecov](https://app.codecov.io/gh/Lightning-AI/lightning) is confused because we recently changed the structure of the source package.

<img width="1394" alt="image" src="https://user-images.githubusercontent.com/5495193/217111470-d3b18f56-4127-47bf-a662-e03d7fe13435.png">

There are folders that don't exist anymore. Also, missing coverage uploads from CI jobs result in the coverage number to be extremely low (50 %). 

<img width="927" alt="image" src="https://user-images.githubusercontent.com/5495193/217111766-8b1be65e-455c-4508-9bb7-7e7268fbcfc6.png">

cc @carmocca @akihironitta @borda

**Comment by Borda** [comment]
not sure what we could do here, we would need to have one single test suite over the monologic `lightning` package and report this coverage...
