### ISSUE TITLE
all_gather operation fails in multi GPU setting

### ISSUE THREAD

**Issue by shamanez** [Lightning-AI/pytorch-lightning#17042]
### Bug description

I can gather tensors with all_gather in the test_epcoh_end. Then I can also compute things like similarity scores. But if I have an operation like     **target = torch.eye(similarity_scores.shape[0])** it fails. What could be the reason ?

### How to reproduce the bug

```python
from torchmetrics.functional import pairwise_cosine_similarity    
def test_epoch_end(self, outputs):
      
        
        A_emb = torch.cat([x["A_emb"] for x in outputs],dim=0)
        B_emb = torch.cat([x["B_emb"] for x in outputs],dim=0)
        
        all_A_emb = self.all_gather(A_emb).view(-1,item_emb.shape[1])
        all_B_emb = self.all_gather(B_emb).view(-1,user_emb.shape[1])
        
          
        similarity_scores = pairwise_cosine_similarity(all_A_emb, all_B_emb)

        target = torch.eye(similarity_scores.shape[0])

Code works fine without the pairwise_cosine_similarity part.
```

### Error messages and logs

ProcessExitedException: process 0 terminated with signal SIGSEGV

### Environment

Name: pytorch-lightning
Version: 1.9.4
Summary: PyTorch Lightning is the lightweight PyTorch wrapper for ML researchers. Scale your models. Write less boilerplate.
Home-page: https://github.com/Lightning-AI/lightning
Author: Lightning AI et al.
Author-email: pytorch@lightning.ai
License: Apache-2.0
Location: /local_disk0/.ephemeral_nfs/envs/pythonEnv-8d432daf-ab0f-41af-9b09-5c6128436d80/lib/python3.9/site-packages
Requires: fsspec, tqdm, typing-extensions, numpy, lightning-utilities, torchmetrics, packaging, PyYAML, torch
Required-by:

**Comment by awaelchli** [comment]
Hi @shamanez 

I took your snippet and integrated it into a minimal running example. Could you please change it to show how it fails (since you didn't post all code)?

```py
import torch
from torch.utils.data import DataLoader, Dataset

from pytorch_lightning import LightningModule, Trainer

from torchmetrics.functional import pairwise_cosine_similarity


class RandomDataset(Dataset):
    def __init__(self, size, length):
        self.len = length
        self.data = torch.randn(length, size)

    def __getitem__(self, index):
        return self.data[index]

    def __len__(self):
        return self.len


class BoringModel(LightningModule):
    def __init__(self):
        super().__init__()
        self.layer = torch.nn.Linear(32, 2)

    def forward(self, x):
        return self.layer(x)

    def test_step(self, batch, batch_idx):
        loss = self(batch).sum()
        self.log("test_loss", loss)

    def test_epoch_end(self, _):
        A_emb = torch.rand(3, 5)
        B_emb = torch.rand(3, 5)
        all_A_emb = self.all_gather(A_emb).view(-1, 5)
        all_B_emb = self.all_gather(B_emb).view(-1, 5)

        similarity_scores = pairwise_cosine_similarity(all_A_emb, all_B_emb)
        target = torch.eye(similarity_scores.shape[0])
        print(target)

    def configure_optimizers(self):
        return torch.optim.SGD(self.layer.parameters(), lr=0.1)


def run():
    test_data = DataLoader(RandomDataset(32, 64), batch_size=2)
    model = BoringModel()
    trainer = Trainer(devices=2, accelerator="cpu")
    trainer.test(model, dataloaders=test_data)


if __name__ == "__main__":
    run()

```

**Comment by shamanez** [comment]
Thanks a lot.

The only difference is 
```

def run():
    test_data = DataLoader(RandomDataset(32, 64), batch_size=2)
    model = BoringModel()
    trainer = Trainer(devices=2, accelerator="ddp_notebook")
    trainer.test(model, dataloaders=test_data)


```
Update on this: I executed this on a databricks notebook. But when I executed this from the terminal changing the accelerator="ddp" everything worked.

**Comment by awaelchli** [comment]
Hey @shamanez 
I actually don't believe you 😄 
You reported that the issue was with Lightning version 1.9.3 in your original post, but here you are saying that you set `accelerator="ddp"`, which is not a valid setting in this version. Have you mixed up something? I am glad that you found a solution, but it can't be this :))

Let me know if we should close the ticket or if there is anything left to do.

**Comment by shamanez** [comment]
No. I said all gather fails in multi-GPU settings. It was in a databricks notebook. But when I executed it as a python script, it worked by changing the ddp_notebook. Maybe my lightning version was incorrect. Actually, it is the latest version.

**Comment by awaelchli** [comment]
If it is the latest version, then `accelerator="ddp"` or `accelerator="ddp_notebook"` will rase a ValueError, that the accelerator is not supported. You should set instead `strategy="ddp"`, which is the right Trainer argument name. 

What was the error? Can you post the full stack trace please?

**Comment by shamanez** [comment]
oh my bad. It was *Strategy* I am using :).  Just in the minimal example, I
was using the accelerator. Sorry about that.  But yeah error happens when
only I run the code in a notebook.

**Comment by awaelchli** [comment]
Closing the issue now. DDP in notebooks is just very hit and miss. It's very difficult from the PyTorch side to support this reliably. 

I suggest to do prototyping in notebooks but then move the code to a script. Or use the notebook to instrument a Python script.
