### ISSUE TITLE
Make `RichProgressBar` visible for both light and dark theme by default 

### ISSUE THREAD

**Issue by tshu-w** [Lightning-AI/pytorch-lightning#17118]
### Description & Motivation

The RichProgressBar with default parameters is difficult to distinguish in the light theme. It is hoped that `RichProgressBar` will be visible by default in both light and dark themes without requiring users to modify the theme like https://github.com/Lightning-AI/lightning/discussions/10833#discussioncomment-1722781

<img width="2032" alt="Screenshot 2023-03-17 at 12 46 29" src="https://user-images.githubusercontent.com/13161779/225821164-5caf999c-7322-4357-bb0e-f55457a0c27e.png">

### Pitch

Try to use the [first 16 standard colors](https://rich.readthedocs.io/en/stable/appendix/colors.html#appendix-colors) combined with ansi styles in [`RichProgressBarTheme`](https://lightning.ai/docs/pytorch/latest/_modules/lightning/pytorch/callbacks/progress/rich_progress.html#RichProgressBar), which are usually defined by the terminal theme.

### Alternatives

Not quite sure, welcome to provide suggestions.

### Additional context

If the suggestion is feasible, I can submit a pull request.

cc @borda

**Comment by tshu-w** [comment]
active

**Comment by tshu-w** [comment]
@Borda Of course, but it may not be very fast.

**Comment by ashikshafi08** [comment]
Hello, 

@tshu-w are you still working on this? I'm planning to work on this, would love to have your input on this. 

Thank you.

**Comment by tshu-w** [comment]
Hello, @ashikshafi08, I was interrupted by other things so I haven't started yet. If you are willing to work on it and submit a PR, that would be great. My initial idea is the one mentioned above.

**Comment by SuwonPabby** [comment]
Hello, @Tribhuvan0 Is this still ongoing for you? I have confirmed that your PR is not closed yet. If you have difficulties continuing this due to other circumstances, I'm planning to take it over.
