### ISSUE TITLE
Clarify where to apply `torch.compile` in Fabric and add more tests

### ISSUE THREAD

**Issue by awaelchli** [Lightning-AI/pytorch-lightning#17250]
### Description & Motivation

Users currently ask questions where `torch.compile` should be applied in Fabric. There are two main choices:

1. Before calling fabric.setup()
2. After calling fabric.setup()

Which one is "correct"? If both work, which one is the better choice, what impact does it have? Some strategies like FSDP may have limitations regarding that.

### Pitch

Clarify this in docs (we could use a torch.compile section on its own) and also write tests for these. Investigate possible limitations.

### Additional context

Issues raised in e.g. https://github.com/Lightning-AI/lit-llama/issues/62

cc @borda @carmocca @justusschock @awaelchli

**Comment by batschoni** [comment]
I was wondering if there is any update on that issue?

**Comment by marikgoldstein** [comment]
Also wondering about guidance for torch compile with Fabric!

**Comment by carmocca** [comment]
Right now there are barely any optimizations from compiling the wrapped module, so I would recommend that you compile the original module and then wrap it which will also be less prone to graph breaks. This might change in the future.

**Comment by marikgoldstein** [comment]
Thanks for the super quick reply! I'll be trying it out and will comment here with any findings!

**Comment by carmocca** [comment]
Adding one more thing to consider: when using a plugin that replaces layers (Bitsandbytes and TransformerEngine at the moment), you want to `compile` after `setup` since that is when you can be sure that the layers have been replaced.

**Comment by YichengDWu** [comment]
This video might be helpful.
https://youtu.be/98enl3C3fps?si=2bnnu2mWfEb8Fjgd

**Comment by awaelchli** [comment]
We added a compile guide to the docs recently: https://lightning.ai/docs/fabric/2.2.0/advanced/compile.html

The https://github.com/Lightning-AI/pytorch-lightning/issues/17250#issuecomment-1831013511 should be resolved by https://github.com/Lightning-AI/pytorch-lightning/pull/19280
