### ISSUE TITLE
freezing and unfreezing has unexpected behaviour

### ISSUE THREAD

**Issue by botcs** [Lightning-AI/pytorch-lightning#17361]
### Bug description

Hi,

First of all, thanks a million times for the awesome framework! I just started learning the bits and bobs, but so far I find it super helpful for my projects.

I have integrated online evaluation in the training pipeline, roughly it looks something like:

```
    def eval_step(self, eval_data):
        self.eval()
        self.freeze()
        with torch.no_grad():
            eval_ind, eval_x, eval_target = eval_data
            eval_logit = self(eval_x)["logits"]
            eval_pred = torch.argmax(eval_logit, dim=1)
            acc1, acc5 = accuracy_at_k(eval_logit, eval_target, top_k=[1, 5])
        self.unfreeze()
        self.train()

        eval_out = {
            "next_batch_acc1": acc1, 
            "next_batch_acc5": acc5, 
            "next_batch_pred": eval_pred,
            "next_batch_target": eval_target
        }

        return eval_out
```
---
## Problem description:

The first problem is that the `self.train()` and `self.eval()` line is redundant, as they are also called in the `self.freeze()` and `self.unfreeze()` method - yet the results differ. Did I miss something?

The second problem is that the `self.freeze()` and `self.unfreeze()` calls take up an unreasonable amount of time (see the figure below): the evaluation altogether takes 3x time as the training pass.
<img width="1017" alt="image" src="https://user-images.githubusercontent.com/12262395/231807029-38615366-d941-4bb7-8cef-fba85b3d7149.png">

Probably I have just missed something, but so far I cannot find where did I go out of the lines of the lightning framework.

### Error messages and logs

```
# Error messages and logs here please
```

### Environment

<details>
  <summary>Current environment</summary>

```
#- Lightning Component (e.g. Trainer, LightningModule, LightningApp, LightningWork, LightningFlow):
#- PyTorch Lightning Version (e.g., 1.5.0):
#- Lightning App Version (e.g., 0.5.2):
#- PyTorch Version (e.g., 2.0):
#- Python version (e.g., 3.9):
#- OS (e.g., Linux):
#- CUDA/cuDNN version:
#- GPU models and configuration:
#- How you installed Lightning(`conda`, `pip`, source):
#- Running environment of LightningApp (e.g. local, cloud):
```

</details>

cc @carmocca @justusschock @awaelchli @borda

**Comment by awaelchli** [comment]
@botcs Can this issue be demonstrated with our [debug model](https://github.com/Lightning-AI/lightning/blob/master/examples/pytorch/bug_report/bug_report_model.py) as well? It would be much easier to study this one. It would be very valuable if you can demonstrate it there.
