### ISSUE TITLE
Refactor Fabric tests that use the old `.run()` method

### ISSUE THREAD

**Issue by awaelchli** [Lightning-AI/pytorch-lightning#17479]
### Outline & Motivation

After redesigning LightningLite into Fabric, we still have some tests leftover that use the old .run() construct to launch and initialize processes under the subclass of Fabric. 

```py
class TestSomething(Fabric):
    def run(self):
        assert ...

TestSomething(accelerator="cuda").run()
```

### Pitch

Refactor the tests to the regular usage of Fabric.

```py
fabric = Fabric(accelerator="cuda")
fabric.launch()
assert ...
```

Example: 
https://github.com/Lightning-AI/lightning/blob/d48ec08d76ec090fb0836b5da7f8f9d136f85426/tests/tests_fabric/strategies/test_deepspeed_integration.py#L33-L35

cc @justusschock @awaelchli @tchaton @carmocca @borda

**Comment by carmocca** [comment]
@awaelchli Anything leftover here?
