### ISSUE TITLE
Upgrade s3fs to support environment variable for 'endpoint_url'

### ISSUE THREAD

**Issue by lcaquot94** [Lightning-AI/pytorch-lightning#17568]
### Description & Motivation

Currently, s3fs only allows for specifying the 'endpoint_url' parameter directly when creating a connection to AWS S3. However, for users who want to use a different storage service like MinIO, this parameter needs to be set via an environment variable. This would enable users to set up MinIO as the storage service for Lightning, without having to modify the code. The latest version of s3fs (2023.3.0) now supports setting 'endpoint_url' via an environment variable, but Lightning is currently using an older version that doesn't have this capability.

### Pitch

We would like to request an upgrade to the latest version of s3fs (2023.3.0) in Lightning, in order to support setting 'endpoint_url' via an environment variable. This would enable users to use MinIO as their storage service for Lightning, without having to modify the code. This is a highly requested feature, as MinIO is becoming an increasingly popular storage service for many users. The upgrade would also improve the overall usability and flexibility of Lightning.

### Alternatives

If upgrading s3fs is not feasible, the alternative solution would be for users to manually modify the code to set the 'endpoint_url' parameter when creating a connection to MinIO. However, this would require a code change every time a user wants to switch between different storage services. Another alternative would be to use a different library that already supports setting 'endpoint_url' via an environment variable, but this would require significant changes to the existing codebase and may not be feasible. Therefore, upgrading s3fs is the most practical and efficient solution.

cc @borda

**Comment by awaelchli** [comment]
@lcaquot94 I don't think s3fs gets installed with Lightning. Users can use the latest version by just installing `pip install --upgrade s3fs`. The only place we specify s3fs is here: https://github.com/Lightning-AI/lightning/blob/master/requirements/app/cloud.txt

But the version limitation is not enforced in the package that users install.

**Comment by lcaquot94** [comment]
Ok thank you @awaelchli. You are right it turns out that we can update s3fs to it's last version.
However I still have a problem using Minio as a storage source for Lightning runs.
I try to proceed as described in [s3fs official documentation](https://s3fs.readthedocs.io/en/latest/) and run the following code:

```
s3 = s3fs.S3FileSystem(
      key='miniokey...',
      secret='asecretkey...',
      endpoint_url='https://...'
   )
logger = TensorBoardLogger(save_dir='s3://runs/')
```
Unfortunately it ends up with a `botocore.exceptions.NoCredentialsError: Unable to locate credentials`

I wonder if the issue comes from the fact that I can not pass this custom s3 filesystem to Lightning. Does Lightning define a new s3 session by itself ? Any clue to make MinIO working with Lightning ?

Thank you very much.

**Comment by awaelchli** [comment]
I am not very familiar with these different filesystems. We document the usage with Lightning here: https://lightning.ai/docs/pytorch/stable/common/remote_fs.html?highlight=remote
Anything else is considered unsupported. Of course, if there are ideas how to improve and extend the support, proposals or PRs for this would be welcome.

**Comment by awaelchli** [comment]
Lightning no longer comes with the hard requirement of a pinned s3fs version. It an be upgraded/installed to the version you desire. So I'm closing the issue now.
