### ISSUE TITLE
Support `strategy="deepspeed_stage_1_offload"`

### ISSUE THREAD

**Issue by keunwoochoi** [Lightning-AI/pytorch-lightning#17638]
### Description & Motivation

According to this [Issue](https://github.com/microsoft/DeepSpeed/issues/2174), seems like there is `_offload` version of deepspeed stage 1. But passing `"deepspeed_stage_1_offload"` to `Trainer` doesn't work. I believe it'd still work by passing a config dict, but it'd be great if it works out of the box by passing string.  

cc @borda @awaelchli

**Comment by nik777** [comment]
@awaelchli 
Please assign this issue to me.
