### ISSUE TITLE
Support WandBLogger in Fabric

### ISSUE THREAD

**Issue by MilesCranmer** [Lightning-AI/pytorch-lightning#17885]
### Description & Motivation

Right now there are only the following loggers available in `lightning.fabric`:

- Logger
- CSVLogger
- TensorBoardLogger

I would like for there to be a `WandbLogger`, similar to that available for the regular `Trainer` interface.

### Alternatives

- It seems I cannot use the regular `WandbLogger`, as it needs to be passed to a `Trainer` object. 
- I tried to use `wandb` directly, but it seems to launch multiple runs for each ddp process.

cc @borda @awaelchli @morganmcg1 @borisdayma @scottire @parambharat

**Comment by MilesCranmer** [comment]
Is there a reason why the regular loggers (https://lightning.ai/docs/pytorch/stable/api/lightning.pytorch.loggers.wandb.html#module-lightning.pytorch.loggers.wandb) are incompatible with `lightning.fabric`?

**Comment by ManoBharathi93** [comment]
HI @MilesCranmer ,

Given these limitations, it could be helpful to explore other options for implementing a WandbLogger in the lightning.fabric module. One approach could be to create a custom logger class that wraps around the regular WandbLogger and is specifically designed to work with the fabric module's distributed training setup.

This custom logger could handle the launching of the Weights & Biases run for each process in a DDP setup, ensuring that only one run is created per process. It could also provide additional functionality or customization options tailored specifically to the needs of users working with the fabric module.

**Comment by MilesCranmer** [comment]
A quick update is that I was able to actually pass the regular `WandbLogger` to the `fabric` module and it seems to be working. I think what happened was I saw an unrelated error, and noticed `WandbLogger` was not mentioned on the fabric loggers page, so I just assumed it was unsupported.

Out of curiosity why is there a separate loggers page for fabric if (presumably) the regular lightning loggers work? Would there be other problems I haven’t yet seen yet?

**Comment by MilesCranmer** [comment]
Hi @ManoBharathi93,

Just to check, do you know this for a fact, or are you generating these responses with ChatGPT? I am just curious because your message's writing style sounds exactly like a ChatGPT response, and some of your other issue responses have a very different writing style: e.g., https://github.com/Lightning-AI/lightning/issues/17793#issuecomment-1597223628:

> Did you fix this issue @vadim0x60 ?
> Can I know what model your training it ? (Application)
> I think No one is working on it !.
> Can I work on this issue with LSTM model ?

Regarding this comment:

> Regarding your question on the separate loggers page for Fabric, it's important to note that while Fabric is built on top of PyTorch Lightning, it has some unique features and requirements compared to a typical PyTorch Lightning project. This means that although most of the functionality of PyTorch Lightning should work seamlessly with Fabric, there may be cases where certain components need to be specifically designed or configured to work with Fabric.

Can you link a reference for where it states this, or how you know this? (Or is this a ChatGPT generation?)

Thanks,
Miles

**Comment by ManoBharathi93** [comment]
> Fabric is built on top of PyTorch Lightning



> Regarding your question on the separate loggers page for Fabric, it's important to note that while Fabric is built on top of PyTorch Lightning, it has some unique features and requirements compared to a typical PyTorch Lightning project. This means that although most of the functionality of PyTorch Lightning should work seamlessly with Fabric, there may be cases where certain components need to be specifically designed or configured to work with Fabric.

https://lightning.ai/pages/blog/introduction-to-lightning-fabric/

The statement is from official documentation. 
do you have any other questions ?

**Comment by MilesCranmer** [comment]
Where does it say there are cases where certain components of the **loggers** "need to be specifically designed or configured to work with Fabric"?

**Comment by ManoBharathi93** [comment]
> Where does it say there are cases where certain components of the **loggers** "need to be specifically designed or configured to work with Fabric"?

There may be some cases:
         1. When you come up with your own metrics for your model which need to be logged. 
         2. When you build your own custom Trainer .

**Comment by MilesCranmer** [comment]
No worries, I just didn't realize you were not on the Lightning team. But thanks for trying to help.

@Borda or another Lightning team member, do you know if using the `WandbLogger` from `lightning.pytorch.loggers.wandb` would pose any problems when using it in Lightning Fabric? It seems to work for me, but I noticed it's not actually part of the `fabric` submodule, so I wasn't sure. If there are no issues with this approach then feel free to close this.

**Comment by awaelchli** [comment]
Hi everyone, I can explain this. 

> Where does it say there are cases where certain components of the loggers "need to be specifically designed or configured to work with Fabric"?

It is not that the loggers need to be rewritten completely or anything like that. It is just that some loggers have trainer-specific hooks that wouldn't make sense in Fabric. If we just plugged the loggers as they are from PL into Fabric, it would work but then users could call APIs that would error out due to the missing code path into the Trainer. Another reason related to that is that we don't want a depencency from Fabric -> Trainer (the other way around would be ok). 

So the simple approach we take for the loggers is: 1) place their core implementation in `lightning.fabric.loggers` (no trainer assumptions). 2) Provide a second implementation in `lightning.pytorch.loggers` that reuses the code from Fabric but provides a superset of functionality with additional hooks etc. useful when used together with the Trainer. This is a relatively straightforward refactor. 

Let's keep the issue open. I am aware that we need to port the remaining loggers over, I just haven't had the time. Help from the community would be the best thing ever but I can also look into it in the next few days if it is difficult to do.

> It seems to work for me, but I noticed it's not actually part of the fabric submodule

Yes the basic functionality should work if you use the logger standalone. Feel free to continue doing that.

**Comment by 3outeille** [comment]
Any update about WandbLogger for Fabric ?

**Comment by ash0ts** [comment]
Hey @3outeille, Anish from W&B here 👋 . I'll be working on this next week! Looking forward to putting up this PR

**Comment by leng-yue** [comment]
Hi @ash0ts, is this WIP now? I can submit a PR if you are not working on it yet.

**Comment by h3x4g0ns** [comment]
@ash0ts Any update with this?

**Comment by rave78** [comment]
Hi @ash0ts 

Is still WIP?

**Comment by ash0ts** [comment]
Hey All! Sorry for the delay on this. PR #19077 should address this. Looking forward to getting this merged!

**Comment by lantiga** [comment]
Hey @ash0ts, thank you for your contribution.

We recently had internal discussions on the balance to strike between Fabric being batteries included vs keeping the core as lean as possible in the spirit of the library, and we opted for the second.

This is not to say that we are against such integrations. It only means that we would like to keep them out of core. We'll be happy to acknowledge the existence of an external package that provides this integration.

**Comment by ash0ts** [comment]
Hey @lantiga,

Thank you for the update and for considering the integration. I understand and respect the decision to maintain a lean core for Fabric in line with the library's philosophy.

In light of this, I'm exploring the possibility of moving the Fabric integration into an external package, possibly as part of the core`wandb` SDK or our additional package `wandb-addons`

However, I'm concerned about the discoverability of these integrations when they're not included in the core package. To help with this, could we consider adding a section in the Fabric documentation dedicated to third-party integrations? This could significantly enhance the visibility of external packages and provide users with easy access to additional functionality.

Thanks again for your consideration and support. I look forward to contributing further to the Lightning community.

**Comment by lantiga** [comment]
Hey @ash0ts, yes we’ll be very happy to do that!

**Comment by ash0ts** [comment]
@awaelchli What is the best way to add our Loggers to the PTL documentation?

**Comment by awaelchli** [comment]
@ash0ts Hey, thanks for your interest. 

Currently, the Fabric docs around loggers is very minimal. For example here, we just say which loggers are supported:
https://lightning.ai/docs/fabric/stable/guide/logging.html#track-metrics

I think it would make sense to add the WandbLogger option there to the list, and the link will either go to a dedicated page for the WandbLogger within the fabric docs, or if you prefer link to the external docs that you maintain. 

In case you already have a link to the source code of your implementation, or docs link, could I take a quick look?

**Comment by ash0ts** [comment]
Hey @awaelchli! 
- The PR we merged into our SDK for this logger is here: https://github.com/wandb/wandb/pull/6919. 
- The new docs should be available on https://docs.wandb.ai/guides/integrations/lightning at the end of the week. 
- We also have a new example being added to our Examples repo soon too: https://github.com/wandb/examples. 

What would the process look like to add a dedicated docs page directly within the fabric docs?

**Comment by awaelchli** [comment]
@ash0ts Looks great!

I opened a draft here to show you how it could look like: https://github.com/Lightning-AI/pytorch-lightning/pull/19444. The idea is that we could provide a simple page that shows how to get started, and then the full wandb-specific apis would be documented externally on the wandb page.

Let me know what you think and feel free to take my draft and tweak it.
