### ISSUE TITLE
DDP with DataLoader num_workers>0 seems to result in GIL (CPU summing to 100%)

### ISSUE THREAD

**Issue by CalumF** [Lightning-AI/pytorch-lightning#18149]
### Bug description

When running the pl Trainer with ddp on a single node with multiple gpus and DataLoader(..., num_workers=2) (or >0) CPU use seems to max at 100% - when num_woerkers=0 it will go much higher.

Running the below boring model results in very slow data loading with htop outputs like this:
![image](https://github.com/Lightning-AI/lightning/assets/46681532/418742c8-8c06-40f5-a0e4-fe1e53af3c12)

It looks like there are 100%/16 workes = ~6.25% each

On the other hand if I run it with num_workers=0 I get faster training and much better CPU utilisation:
![image](https://github.com/Lightning-AI/lightning/assets/46681532/56577d2a-8a24-49d1-bfbe-daa2583ce758)

When using num_workers=0 in practice with more complex dataloading workflows it is still a bottleneck (but still better utilisation than n>0).

Additionally the docs seem to suggest setting num_workers=num_cpus however it seems like num_workers is per device?

Any help/advice would be appreciated!

### What version are you seeing the problem on?

v2.0

### How to reproduce the bug

```python
import torch
from torch import nn
from torch.nn import functional as F
from torch.utils.data import DataLoader, Dataset
import pytorch_lightning as pl
tmpdir = os.getcwd()


class RandomDataset(Dataset):
    def __init__(self, shape, num_samples) -> None:
        super().__init__()
        self.shape = shape
        self.num_samples = num_samples
    
    def __len__(self):
        return self.num_samples
    
    def __getitem__(self, idx):
        return torch.randn(self.shape)**(5/4)

num_samples = 10000
train = RandomDataset((3, 2048, 2048), num_samples)
train = DataLoader(train, batch_size=32, pin_memory=True, num_workers=2)
val = RandomDataset((3, 2048, 2048), num_samples)
val = DataLoader(val, batch_size=32, pin_memory=True, num_workers=2)

class BoringModel(pl.LightningModule):

    def __init__(self):
        super().__init__()
        self.layer = torch.nn.Conv2d(3, 1, 1)

    def forward(self, x):
        return self.layer(x)

    def loss(self, batch, prediction):
        return torch.nn.functional.mse_loss(prediction, torch.ones_like(prediction))

    def training_step(self, batch, batch_idx):
        output = self.layer(batch)
        loss = self.loss(batch, output)
        self.log('train_loss', loss)
        return loss


    def validation_step(self, batch, batch_idx):
        output = self.layer(batch)
        loss = self.loss(batch, output)
        return {"x": loss}


    def test_step(self, batch, batch_idx):
        output = self.layer(batch)
        loss = self.loss(batch, output)
        self.log('test_loss', loss)
        return {"y": loss}


    def configure_optimizers(self):
        optimizer = torch.optim.SGD(self.layer.parameters(), lr=0.1)
        lr_scheduler = torch.optim.lr_scheduler.StepLR(optimizer, step_size=1)
        return [optimizer], [lr_scheduler]

def test(tmpdir):
    # init model
    model = BoringModel()

    # Initialize a trainer
    trainer = pl.Trainer(
        accelerator='gpu',
        strategy='ddp',
        devices=8,
        max_epochs=1,
        precision='bf16-mixed',
        default_root_dir=tmpdir
    )

    trainer.fit(model, train)

test(tmpdir)
```

### Environment

PyTorch version: 2.0.1
Is debug build: False
CUDA used to build PyTorch: 11.7
ROCM used to build PyTorch: N/A

OS: Debian GNU/Linux 11 (bullseye) (x86_64)
GCC version: (Debian 10.2.1-6) 10.2.1 20210110
Clang version: Could not collect
CMake version: version 3.18.4
Libc version: glibc-2.31

Python version: 3.10.12 | packaged by conda-forge | (main, Jun 23 2023, 22:40:32) [GCC 12.3.0] (64-bit runtime)
Python platform: Linux-5.10.0-23-cloud-amd64-x86_64-with-glibc2.31
Is CUDA available: True
CUDA runtime version: Could not collect
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration:
GPU 0: NVIDIA RTX A4000
GPU 1: NVIDIA RTX A4000
GPU 2: NVIDIA RTX A4000
GPU 3: NVIDIA RTX A4000
GPU 4: NVIDIA RTX A4000
GPU 5: NVIDIA RTX A4000
GPU 6: NVIDIA RTX A4000
GPU 7: NVIDIA RTX A4000

Nvidia driver version: 510.85.02
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture: x86_64
CPU op-mode(s): 32-bit, 64-bit
Byte Order: Little Endian
Address sizes: 40 bits physical, 48 bits virtual
CPU(s): 30
On-line CPU(s) list: 0-29
Thread(s) per core: 1
Core(s) per socket: 1
Socket(s): 30
NUMA node(s): 1
Vendor ID: AuthenticAMD
CPU family: 25
Model: 1
Model name: AMD EPYC 7313 16-Core Processor
Stepping: 1
CPU MHz: 3000.039
BogoMIPS: 6000.07
Virtualization: AMD-V
L1d cache: 1.9 MiB
L1i cache: 1.9 MiB
L2 cache: 15 MiB
L3 cache: 480 MiB
NUMA node0 CPU(s): 0-29
Vulnerability Itlb multihit: Not affected
Vulnerability L1tf: Not affected
Vulnerability Mds: Not affected
Vulnerability Meltdown: Not affected
Vulnerability Mmio stale data: Not affected
Vulnerability Retbleed: Not affected
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1: Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2: Mitigation; Retpolines, IBPB conditional, IBRS_FW, STIBP disabled, RSB filling, PBRSB-eIBRS Not affected
Vulnerability Srbds: Not affected
Vulnerability Tsx async abort: Not affected
Flags: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm rep_good nopl cpuid extd_apicid pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm cmp_legacy svm cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw perfctr_core invpcid_single ssbd ibrs ibpb stibp vmmcall fsgsbase tsc_adjust bmi1 avx2 smep bmi2 invpcid rdseed adx smap clflushopt clwb sha_ni xsaveopt xsavec xgetbv1 xsaves clzero xsaveerptr wbnoinvd arat npt nrip_save umip pku ospke vaes vpclmulqdq rdpid arch_capabilities

Versions of relevant libraries:
[pip3] efficientnet-pytorch==0.7.1
[pip3] numpy==1.24.4
[pip3] pytorch-lightning==2.0.5
[pip3] segmentation-models-pytorch==0.3.3
[pip3] torch==2.0.1
[pip3] torch-tb-profiler==0.4.1
[pip3] torchmetrics==0.12.0.dev0
[pip3] torchview==0.2.6
[pip3] torchvision==0.15.2
[pip3] torchviz==0.0.2
[pip3] triton==2.0.0
[conda] No relevant packages
</details>

cc @borda

**Comment by awaelchli** [comment]
@CalumF With a simple data preprocessing like you show `return torch.randn(self.shape)**(5/4)`, the process communication will dominate and is likely the reason why you see better performance with `num_workers=0`. To be sure, we could convert the example you gave to regular PyTorch code to show the same behavior (that would be my expectation).

**Comment by tonydavis629** [comment]
I have the same issue. @awaelchli the problem is not that the performance is worse with more workers, it's that the training entirely stops.

**Comment by CalumF** [comment]
@awaelchli Thanks for the response!

I can make the dataloading slower and you get the exact same behaviour (in my real training it's definitely more complex too!). eg:
```python
    def __getitem__(self, idx):
        arr = torch.randn(self.shape)**(5/4)
        for x in torch.randn(30000):
            arr *= x
        return arr
```
takes about ~2s for each __getitem__ call now and same ~6% CPU use.

I assumed it was just being slow but actually after about an hour it's still fails to finish the first step of the fist epoch - seems the same as @tonydavis629

**Comment by awaelchli** [comment]
@CalumF Could you take a look at this raw PyTorch example:

```py
import os

import torch
from torch import nn
from torch.nn.parallel import DistributedDataParallel
from torch.utils.data import DataLoader, Dataset


class RandomDataset(Dataset):
    def __init__(self, shape, num_samples) -> None:
        super().__init__()
        self.shape = shape
        self.num_samples = num_samples

    def __len__(self):
        return self.num_samples

    def __getitem__(self, idx):
        arr = torch.randn(self.shape) ** (5 / 4)
        # for x in torch.randn(30000):
        #     arr *= x
        return arr


class BoringModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.layer = torch.nn.Conv2d(3, 1, 1)

    def forward(self, x):
        return self.layer(x)


def run(rank, world_size):
    cuda = True
    torch.manual_seed(1)
    device = torch.device("cuda", rank) if cuda else torch.device("cpu")
    if cuda:
        torch.cuda.manual_seed(1)
        torch.cuda.set_device(device)

    os.environ["LOCAL_RANK"] = str(rank)
    os.environ["WORLD_SIZE"] = str(world_size)
    os.environ["MASTER_ADDR"] = "localhost"
    os.environ["MASTER_PORT"] = "1234"
    torch.distributed.init_process_group(
        backend=("nccl" if cuda else "gloo"),
        init_method="env://",
        rank=rank,
        world_size=world_size,
    )
    print("init rank done", rank)

    train = RandomDataset((3, 2048, 2048), 10000)
    train = DataLoader(
        train, 
        batch_size=32, 
        pin_memory=True, 
        num_workers=0,  # change here
    )

    model = BoringModel().to(device)
    ddp_model = DistributedDataParallel(model, device_ids=([rank] if cuda else None))
    optimizer = torch.optim.SGD(ddp_model.parameters(), lr=0.1)

    print("start training")
    for i, batch in enumerate(train):
        print(i)
        batch = batch.to(device)
        prediction = ddp_model(batch)
        loss = torch.nn.functional.mse_loss(prediction, torch.ones_like(prediction))
        loss.backward()
        optimizer.step()
        optimizer.zero_grad()


if __name__ == "__main__":
    world_size = 4  # change here
    torch.multiprocessing.spawn(run, nprocs=world_size, args=(world_size, ))

```

Set the `world_size`, `num_workers` and `cuda` flags as you like. This demonstrates the same behavior as described with the PL model. We are running on different systems, so if you could verify the observations:

- num_workers=2 => peak per-process usage is 100%, but GPU can overlap with data loading
- num_workers=0 => torch uses multiple cores in the main process directly (>100% usage), but CPU blocking the GPU

**Comment by awaelchli** [comment]
With `num_workers = 0`
<img width="1696" alt="image" src="https://github.com/Lightning-AI/lightning/assets/5495193/daeba1e0-8bb4-4889-b7e2-4fa917bf8a59">

With `num_workers=2`
<img width="1696" alt="image" src="https://github.com/Lightning-AI/lightning/assets/5495193/adce04cc-51ca-4800-b370-ac865c85127c">

PyTorch version for the above experiment:
`torch == 2.1.0.dev20230719+cu118`

**Comment by CalumF** [comment]
Hi @awaelchli - no worries! Thanks for getting back to me - I've been away a bit anyway!

I made the edits and for num_workers=2 I see the behavior I was seeing before - cpu use around 6-7% per process:
![image](https://github.com/Lightning-AI/lightning/assets/46681532/bc3d4dfa-5039-4ba3-ba36-658ea00c735b)

Likewise for num_workers=1 you see 8 procs with cpu ~= 100/8 (12.5%):
![image](https://github.com/Lightning-AI/lightning/assets/46681532/8b00a341-d2f4-45e8-bf3e-6b7bb2d2b130)

During the actual training loop (ie from .to(device) to zero_grad) there's normal/100% maxing cpu use: 
![image](https://github.com/Lightning-AI/lightning/assets/46681532/59889714-cc23-4ea2-8fac-ca33f6aac9da)
It's only while loading the batch that you see the pseudo single process behavior - but this is taking about 30s for each <1s training pass! I checked pin_memory=False in case and same behavior.

For num_workers=0 it's nice and normal:
![image](https://github.com/Lightning-AI/lightning/assets/46681532/b410d58a-4d22-4c19-8f01-c0ed58ebeca4)



Let me know any thoughts you have! It feels like it could be linux setup territory? If you can give me an idea of the possible issues that could cause it and/or the underlying systems involved I can talk to my IT/hardware dept and see if there's anything strange going on there too?

**Comment by awaelchli** [comment]
@CalumF Another thing to try would be to set and tune the value `OMP_NUM_THREADS=1` (add in front of your python command).

**Comment by CalumF** [comment]
I think I found it by the way! For some reason if, as in the scripts above, I don't explicitly set the Dataloader multiprocessing_context it defaults to None even with num_workers >0. If I set it to any of the options eg 'forkserver' or 'spawn' it works properly. I'm not sure why the default doesn't work but might be worth a bug fix or at least documentation change?

**Comment by awaelchli** [comment]
It is normal for `DataLoader.multiprocessing_context` to be None by default if you didn't explicitly set it. None there simply means that Pytorch will use the default depending on the operating system, and on Linux it will be "fork". I don't know why switching to a different one explicitly would make such a drastic difference for you.

**Comment by rogerwwww** [comment]
I have been digging into this issue for days and @CalumF's solution also worked for me!

**TL;DR** If your are loading some very large objects, set ``multiprocessing_context='spawn'`` when you are creating the DataLoader.

The reason why it matters might be found in [this blog post](https://pythonspeed.com/articles/faster-multiprocessing-pickle/). As it suggests,
> the "fork" context is super-broken, which is why it will stop being the default in Python 3.14.
>
> On my computer, this program (with "fork") consistently deadlocks: it freezes and never exits. Any time you have threads in the parent process, the "fork" context can cause in potential deadlocks, or even corrupted memory, in the child process.

So IMO ``"spawn"`` should be preferred in practice and please try this if you are facing similar issues!

**Comment by awaelchli** [comment]
It's definitely interesting that you were able to get into this case where `multiprocessing_context` has such a dramatic effect. I suggest we close the ticket, since Lightning probably can't do much here as the default for this is platform specific and set by PyTorch. If you believe this could affect a considerable amount of users, we could try to get some advice from the PyTorch team.

**Comment by rogerwwww** [comment]
> If you believe this could affect a considerable amount of users, we could try to get some advice from the PyTorch team.

I never had this issue before but started experiencing it after switching to a NFS-based system. Not sure if it will be the case for everyone. If are experiencing similar issues, maybe you can comment under this issue so that we can have a general idea of the number of affected users.

**Comment by Shen001** [comment]
if your model parameters too few ，CPU will go to near 100%，but bigger model is fine！！！
