### ISSUE TITLE
`link_arguments` inside a list with Lightning CLI

### ISSUE THREAD

**Issue by george-gca** [Lightning-AI/pytorch-lightning#18161]
### Description & Motivation

I would like to link two arguments, one of them being inside a list. For example, link `trainer.default_root_dir` with one of the `save_dir` of the loggers that I will attach to the trainer.

Currently this is not implemented as seen [here](https://github.com/Lightning-AI/lightning/issues/9887#issuecomment-1018286258).

### Pitch

Link my `trainer.default_root_dir` with my `trainer.logger[X].init_args.save_dir`.

### Alternatives

Currently this can be done manually by setting the path for both fields separately, but can't be enforced.

cc @borda @carmocca @mauvilsa

**Comment by mauvilsa** [comment]
@george-gca support for this kind of use cases was implemented some months ago in https://github.com/omni-us/jsonargparse/pull/399. I forgot to mention here. Hopefully that works for you.

**Comment by george-gca** [comment]
Thanks for letting me know here. I don't remember now where I was using it, so I can't really check in my code lol. Thanks for the support.
