### ISSUE TITLE
Pip warns about non-standard dependency specifier

### ISSUE THREAD

**Issue by mowangmodi** [Lightning-AI/pytorch-lightning#18563]
### Bug description

When I used pip install copy lighting=1.7.7 on ubuntu20.04, the following problem occurred：
DEPRECATION: pytorch-lightning 1.7.7 has a non-standard dependency specifier torch>=1.9.*. pip 23.3 will enforce this behaviour change. A possible replacement is to upgrade to a newer version of pytorch-lightning or contact the author to suggest that they release a version with a conforming dependency specifiers. Discussion can be found at https://github.com/pypa/pip/issues/12063

### What version are you seeing the problem on?

v1.7

### Error messages and logs

```
# Error messages and logs here please
```

### Environment

<details>
  <summary>Current environment</summary>

```
#- Lightning Component (e.g. Trainer, LightningModule, LightningApp, LightningWork, LightningFlow):
#- PyTorch Lightning Version (e.g., 1.5.0):
#- Lightning App Version (e.g., 0.5.2):
#- PyTorch Version (e.g., 2.0):
#- Python version (e.g., 3.9):
#- OS (e.g., Linux):
#- CUDA/cuDNN version:
#- GPU models and configuration:
#- How you installed Lightning(`conda`, `pip`, source):
#- Running environment of LightningApp (e.g. local, cloud):
```

</details>

cc @borda

**Comment by Borda** [comment]
This was fixed in later releases. Is there a specific reason you need to use this old version and can't jump to a newer one? The only other was trying to make one more/pst release with this fix...

**Comment by chriss1245** [comment]
> This was fixed in later releases. Is there a specific reason you need to use this old version and can't jump to a newer one? The only other was trying to make one more/pst release with this fix...
> 
> Just checking, and 1.8 shall have it fixed

In my case, I need to use an older version because of the restrictions of other libraries: pyannote.audio==0.0.1 requires pytorch_lightning<1.7

**Comment by chriss1245** [comment]
not really :c

**Comment by awaelchli** [comment]
Closing since this was fixed in all the recent versions. For the older versions that see this deprecation, we can't really make any new releases. The workaround will be either ignore the warning or downgrade pip to an earlier version that didn't warn.
