### ISSUE TITLE
LR Finder fails when using multi-node training 

### ISSUE THREAD

**Issue by praritagarwal** [Lightning-AI/pytorch-lightning#18812]
### Bug description

When running lr_finder with a multi-node cluster (for e.g. 2 nodes each having 8 GPUs), [this](https://github.com/Lightning-AI/lightning/blob/3f86ad7ba780716f8b6d8b9f47595b988e48536c/src/lightning/pytorch/tuner/lr_finder.py#L301) line tries to restore the checkpoint on all the nodes. This leads to an error as the checkpoint file is only saved on the 0-th node and is not present on other nodes  (as described [here](https://lightning.ai/docs/pytorch/stable/common/checkpointing_intermediate.html#manual-saving-with-distributed-training)). The code to restore the checkpoints in lr_finder should first check if the global_rank is zero. It seems like this was indeed the case earlier (see [here](https://github.com/Lightning-AI/lightning/blob/9be092dbdb37db353002365e6d5219fae116cc42/pytorch_lightning/tuner/lr_finder.py#L190C8-L190C30)) but was changed in later versions.  

### What version are you seeing the problem on?

master

### Error messages and logs

```
# Error messages and logs here please
```

### Environment

<details>
  <summary>Current environment</summary>

```
#- Lightning Component (e.g. Trainer, LightningModule, LightningApp, LightningWork, LightningFlow):
#- PyTorch Lightning Version (e.g., 1.5.0):
#- Lightning App Version (e.g., 0.5.2):
#- PyTorch Version (e.g., 2.0):
#- Python version (e.g., 3.9):
#- OS (e.g., Linux):
#- CUDA/cuDNN version:
#- GPU models and configuration:
#- How you installed Lightning(`conda`, `pip`, source):
#- Running environment of LightningApp (e.g. local, cloud):
```

</details>

**Comment by awaelchli** [comment]
@praritagarwal Lightning saves checkpoints on (global) rank 0. It assumes that the checkpoint path resides on a shared filesystem (e.g. a network mount in a cluster). For loading, each rank needs to load the file to restore its weights, and thus again we assume that the checkpoint is visible to all nodes (through the shared filesystem). This is how it is currently. It is not specific to the LR-finder, but all saving/loading of checkpoints.
