### ISSUE TITLE
Add `torch.compile` guide to docs

### ISSUE THREAD

**Issue by carmocca** [Lightning-AI/pytorch-lightning#18852]
### 📚 Documentation

This applies to 

- [x] Fabric (https://github.com/Lightning-AI/pytorch-lightning/pull/19330)
- [ ] PyTorch Lightning

Things to mention:
- Compiling `nn.Module` vs `LightningModule` or `fabric.setup(module)` (#17250)
- Known limitations.
- Known sources of graph breaks.

Related: #12398

cc @borda @carmocca @justusschock @awaelchli

**Comment by awaelchli** [comment]
This would also close #17250
