### ISSUE TITLE
Filter test names in `run_standalone_tests.sh` when checking for errors

### ISSUE THREAD

**Issue by awaelchli** [Lightning-AI/pytorch-lightning#19039]
### Description & Motivation

The run_standalone_tests.sh scripts runs the tests and then checks the output log for keywords such as "error", "exception", "failed", etc. 
https://github.com/Lightning-AI/lightning/blob/dd206a20d8cbe037912c144fc3c5e5306ac0d77e/tests/tests_pytorch/run_standalone_tests.sh#L54

It includes an extra rule to avoid false positives on keywords like "xfailed" or "on_exception" (which is a hook name). However, more false-positives can occur if the name of the tests includes one of the keywords. For example, if we have a test called

```py

@RunIf(standalone=True)
def test_for_an_exception_bla_bla():
 ...
```

### Pitch

In the check here

https://github.com/Lightning-AI/lightning/blob/dd206a20d8cbe037912c144fc3c5e5306ac0d77e/tests/tests_pytorch/run_standalone_tests.sh#L54

also exclude all test names that we ran. We have access to the list since we collect all parameterizations. 

cc @carmocca

**Comment by carmocca** [comment]
Good idea. In the meantime, I recommend using "raises" instead of "exception" in test names

**Comment by ryan597** [comment]
Do you have an example of what output is in the `standalone_test_output.txt`? @awaelchli 
If its just the test names we need to exclude, I think adding this should work

```bash
 | grep -qvF ${parametrizations_arr[@]/#/-e } # https://stackoverflow.com/a/2300653
```
so the check becomes
```bash
if grep -iE 'error|exception|traceback|failed' standalone_test_output.txt | grep -vE 'on_exception|xfailed' | grep -qvF ${parametrizations_arr[@]/#/-e }; then # https://stackoverflow.com/a/2300653
```

**Comment by awaelchli** [comment]
@ryan597 Yes if this works I think that's what we were looking for :))

The output log looks something like this (an excerpt):

```
============================= test session starts ==============================
collecting ... ============================= test session starts ==============================
collecting ... ============================= test session starts ==============================
collecting ... ============================= test session starts ==============================
collecting ... collected 1 item

strategies/test_ddp.py::test_ddp_grad_clipping[val-cpu-bf16-mixed] collected 1 item

strategies/test_ddp.py::test_ddp_grad_clipping[val-cuda-32-true] collected 1 item

strategies/test_ddp.py::test_ddp_grad_clipping[norm-cuda-16-mixed] ============================= test session starts ==============================
collecting ... ============================= test session starts ==============================
collecting ... Initializing distributed: GLOBAL_RANK: 1, MEMBER: 2/2
collected 1 item

strategies/test_ddp.py::test_ddp_grad_clipping[norm-cuda-32-true] ----------------------------------------------------------------------------------------------------
distributed_backend=gloo
All distributed processes registered. Starting with 2 processes
----------------------------------------------------------------------------------------------------

Initializing distributed: GLOBAL_RANK: 1, MEMBER: 2/2
Initializing distributed: GLOBAL_RANK: 1, MEMBER: 2/2
----------------------------------------------------------------------------------------------------
distributed_backend=nccl
All distributed processes registered. Starting with 2 processes
---------------------------------------------------------------------
```

Our heuristic to detect exceptions being printed in this output text is to grep for keywords like "error", "exception" etc. The reason why we want to exclude the test names is because a test could be named like

```py
def test_some_function_raises_error():
     ...
```
but would lead to a false-positive detection since the test names are printed in the output log as shown above.
