### ISSUE TITLE
Expand paths that start with "~" in `Trainer.default_root_dir` and other places

### ISSUE THREAD

**Issue by awaelchli** [Lightning-AI/pytorch-lightning#19059]
### Description & Motivation

In  #19058 we fixed the issue that `ModelCheckpoint(dirpath="~/checkpoints", ...)` would not expand the home folder in the path. When a user provides a path with this special character at the start, it is unlikely that their intention is to create a folder with that name in the current directory. The special ~ symbol is more commonly used to denote the home folder of the user.

### Pitch

Everywhere in our codebase where we accept a relative path as input from the user, we should expand such paths properly, as early as possible. See #19058 for how to do that.

An immediate example for this is `Trainer(default_root_dir=...)`, but there probably are other places we should double check.

### Alternatives

Keep as is, the user needs to expand the path themselves.

cc @carmocca

**Comment by abozb01** [comment]
Hey I'm new to this but feel I can do this, do you mind if you assign this one to me?

**Comment by awaelchli** [comment]
Sure, please go ahead. We appreciate it. 
I suggest you start with this one here:
https://github.com/Lightning-AI/lightning/blob/1fcb4ae6376bdfc54ccfb7fbb35874cbc02264c6/src/lightning/pytorch/trainer/trainer.py#L1289
You can fix it the same way I did in https://github.com/Lightning-AI/lightning/pull/19058

**Comment by SarthakNikhal** [comment]
Any progress with this? Can I help with this issue?
