### ISSUE TITLE
MPI Environment Plugin is broken

### ISSUE THREAD

**Issue by coreyjadams** [Lightning-AI/pytorch-lightning#19086]
### Bug description

The mpi.py environment plugin appears to be broken.  Here is the current code:

https://github.com/Lightning-AI/lightning/blob/master/src/lightning/fabric/plugins/environments/mpi.py#L109C1-L116C73

The problem here is the return type of `gather` is `Any`, and in fact is often `None` unless on the root node (rank == 0).  So the sort function fails because you can not make a set from `None`.

A working version of the code is to wrap the `sorted(set(all_hostnames))` to only compute that on rank 0, and then broadcast:
```python
        if self.global_rank() == 0:
            unique_hosts = sorted(set(all_hostnames))
        else:
            unique_hosts = None
```

I can submit a PR for this, if you like, but I am not 100% sure I've got the build correct.  I can change the file locally built when I build and install lightning, it reverts for some reason?  I think the build system you are using is confusing me, sorry.  

### What version are you seeing the problem on?

master

### Error messages and logs

```
# Error messages and logs here please
```

### Environment

<details>
  <summary>Current environment</summary>

```
#- Lightning Component (e.g. Trainer, LightningModule, LightningApp, LightningWork, LightningFlow):
#- PyTorch Lightning Version (e.g., 1.5.0):
#- Lightning App Version (e.g., 0.5.2):
#- PyTorch Version (e.g., 2.0):
#- Python version (e.g., 3.9):
#- OS (e.g., Linux):
#- CUDA/cuDNN version:
#- GPU models and configuration:
#- How you installed Lightning(`conda`, `pip`, source):
#- Running environment of LightningApp (e.g. local, cloud):
```

</details>

cc @awaelchli

**Comment by awaelchli** [comment]
Hey @coreyjadams 
Thanks for reaching out. I think this PR merged yesterday should address the issue: #19074
Let me know


> I can change the file locally built when I build and install lightning, it reverts for some reason?

It may be because you need to install with `pip install . -e` in editable mode?
With #19074 merged you could also install from master and test it, until the fix is included in 2.1.3.
