### ISSUE TITLE
torch.distributed._all_gather_base will be deprecated

### ISSUE THREAD

**Issue by ZHAOYANZHOU** [Lightning-AI/pytorch-lightning#19091]
### Outline & Motivation

/home/jonas.zhou/.conda/envs/py310/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py:2387: UserWarning: torch.distributed._all_gather_base is a private function and will be deprecated. Please use torch.distributed.all_gather_into_tensor instead.

cc @justusschock @awaelchli

**Comment by awaelchli** [comment]
@ZHAOYANZHOU We don't use `torch.distributed._all_gather_base` in our code. Which version of Lightning did you see this with? It is also possible that this comes from a third party package.

**Comment by awaelchli** [comment]
DeepSpeed uses all_gather_base: https://github.com/microsoft/DeepSpeed/blob/7122362fb025f42dcc1bab40a4211ee626116ce4/deepspeed/comm/torch.py#L220

@ZHAOYANZHOU Is this where your warning originated from?

**Comment by awaelchli** [comment]
@ZHAOYANZHOU friendly ping to reply :)

**Comment by ZHAOYANZHOU** [comment]
> @ZHAOYANZHOU friendly ping to reply :)
Thanks for your reply. I think it may be caused by another module, but not lightning. Thanks again!
