### ISSUE TITLE
serialize condition for PILSerializer

### ISSUE THREAD

**Issue by Lavenderjiang** [Lightning-AI/pytorch-lightning#19103]
### Bug description

when PIL is not installed, ```can_serialize``` would error out for [JPEGSerializer](https://github.com/Lightning-AI/pytorch-lightning/blob/520c1e4713340f5bbf66de215471c2863e8fbdf2/src/lightning/data/streaming/serializers.py#L103) and [PILSerializer](https://github.com/Lightning-AI/pytorch-lightning/blob/520c1e4713340f5bbf66de215471c2863e8fbdf2/src/lightning/data/streaming/serializers.py#L66) because ```Image``` and ```JpegImageFile``` are both None.

This is a problem because even for non-PIL data, lightning iterate over all possible serializer. So for non image application (e.g., texts), it is very likely that PIL is not installed and the check will throw an error.

### What version are you seeing the problem on?

master

### How to reproduce the bug

```python
call  using Jpeg or PIL serializer in a environment without PIL.

The bug can be fixed by adding a check that Image or JpegImageFile is not None before calling isinstance.

For example: ``` return Image is not None and isinstance(item, Image.Image) and not isinstance(item, JpegImageFile)````
```

### Error messages and logs

```
in can_serialize
    return isinstance(item, Image.Image) and not isinstance(item, JpegImageFile)
                            ^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'Image'
```

### Environment

no PIL installed

cc @tchaton

**Comment by tchaton** [comment]
Hey @Lavenderjiang, thanks for reporting this issue. I believe this is fixed on master. Would you mind checking on master ?

**Comment by Lavenderjiang** [comment]
> Hey @Lavenderjiang, thanks for reporting this issue. I believe this is fixed on master. Would you mind checking on master ?

Yes, sorry about the late reply and thank you @tchaton!
