### ISSUE TITLE
SAVE_LAST

### ISSUE THREAD

**Issue by dljjqy** [Lightning-AI/pytorch-lightning#19107]
### Bug description

What the fk it is?Why i want to save a copy of a ckpt?.Why not just save the ckpt after the last one training epoch?What fk it is really  " saves a last.ckpt whenever a checkpoint file gets saved"? It is so useless!

### What version are you seeing the problem on?

v2.1

### Error messages and logs

```
# Error messages and logs here please
```

### Environment

<details>
  <summary>Current environment</summary>

```
#- Lightning Component (e.g. Trainer, LightningModule, LightningApp, LightningWork, LightningFlow):
#- PyTorch Lightning Version (e.g., 1.5.0):
#- Lightning App Version (e.g., 0.5.2):
#- PyTorch Version (e.g., 2.0):
#- Python version (e.g., 3.9):
#- OS (e.g., Linux):
#- CUDA/cuDNN version:
#- GPU models and configuration:
#- How you installed Lightning(`conda`, `pip`, source):
#- Running environment of LightningApp (e.g. local, cloud):
```

</details>

**Comment by awaelchli** [comment]
@dljjqy You are violating the [code of conduct](https://github.com/Lightning-AI/pytorch-lightning/blob/master/.github/CODE_OF_CONDUCT.md). I will close the issue, your feedback in this form is not welcome.

We will only consider constructive feedback that is delivered in a respectful way.

**Comment by dljjqy** [comment]
OH. So you also think the "SAVE_LAST" is a stupid design? IT IS BULLSHIT. DID YOU GUY REALLY USE THE CODE YOU WRITTEN TO TRAIN A NETWORK? IF YOU DID, YOU WOULD UNDERSTAND WHAT "SAVE_LAST" SHOULD BE.
