### ISSUE TITLE
No protocol specified Error raised by pl.Trainer()

### ISSUE THREAD

**Issue by gitouni** [Lightning-AI/pytorch-lightning#19134]
### Bug description

|Environment|Pytorch-Lightning|Running Mode|
|---|---|---|
|Ubuntu 20.04.6| 2.1.1 | Remote|

Running pl.Trainer() raised `No protocol specified` Error.
```py
import pytorch_lightning as pl
pl.Trainer()
```
Error Output:
```
No protocol specified
```
And there is no any outputs after 5 minutes.
When running in a local mode, the error becomes:
```
Invalid MIT-MAGIC-COOKIE-1 key
```
without any outputs as well.

### What version are you seeing the problem on?

v2.1

### How to reproduce the bug

```python
import pytorch_lightning as pl
pl.Trainer()
```

### Error messages and logs

```
No protocol specified
```

### Environment

<details>
  <summary>Current environment</summary>

```
#- Lightning Component : Trainer
#- PyTorch Lightning Version: 2.1.1
#- Lightning App Version: N/A
#- PyTorch Version: 1.13.1
#- Python version 3.8.17
#- OS: Linux
#- CUDA/cuDNN version: CUDA 11.7 
#- GPU models and configuration: NVDIA RTX 3080 Ti
#- How you installed Lightning: conda / pip (both caused errors)
#- Running environment of LightningApp: N/A
```

</details>

**Comment by awaelchli** [comment]
@gitouni Could you please post the full error, or we won't be able to help.

**Comment by gitouni** [comment]
> @gitouni Could you please post the full error, or we won't be able to help.

Sorry, @awaelchli ， This is the full error. I understand this error is hard to produce, since my pytorch-lightning works fine until today. This error occurs when I use the Remote-ssh of VSCODE to run my code, and the `pl.Trainer()` command is enough to reproduce this error. When I run this code locally,    `pl.Trainer()` will throw the `Invalid MIT-MAGIC-COOKIE-1 key` error. No more error information is printed.

**Comment by awaelchli** [comment]
@gitouni If I google this error I can see this is a generic issue that is unrelated to the python program you run:
https://www.google.com/search?q=Invalid+MIT-MAGIC-COOKIE-1+key&sourceid=chrome&ie=UTF-8

I am sure that you get the same error if you run any python code, not just lightning. Please try to resolve the issue using the help [online](https://unix.stackexchange.com/questions/199891/invalid-mit-magic-cookie-1-key-when-trying-to-run-program-remotely) first.

**Comment by awaelchli** [comment]
@gitouni Can you try the solutions I linked?

**Comment by gitouni** [comment]
> @gitouni Can you try the solutions I linked?

Hi, @awaelchli , sorry to tell that I currently cannot try these solutions. Unfortunately, I restarted my PC and then it broke down and can't start up again. I will update you if I makes new progress. If I can't fix this hardware issue for many days, I will close this issue. Thanks.

**Comment by gitouni** [comment]
I'm sorry to tell you that I have not solved 'No protocal Specificed' and 'Invalid MIT-MAGIC-COOKIE-1 key' error yet. Maybe these stackoverflow answers do not work for me. However, it's good news that this error does not block the program again and `pl.Trainer()` also successfully show the avaiable resources in my PC now:
```
No protocol specified
GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
```
