### ISSUE TITLE
Saving Only LORA Weights in PyTorch Lightning with HuggingFace PEFT

### ISSUE THREAD

**Issue by NingJinzhong** [Lightning-AI/pytorch-lightning#19149]
### Description & Motivation

I'm currently working with HuggingFace's Parameter-Efficient Fine-Tuning (PEFT) framework within PyTorch Lightning, specifically employing the Low-Rank Adaptation (LORA) approach for training large models. My objective is to optimize storage efficiency by only saving the LORA layer weights, instead of the entire model weights.

Could you provide guidance or suggest a method to achieve this? I'm looking for a way to selectively save only the modified LORA weights after fine-tuning, which are crucial for my application, without having to store the complete set of model weights. This is especially important for managing storage space effectively when dealing with large models.

cc @awaelchli @borda

**Comment by awaelchli** [comment]
@NingJinzhong You can do it for example by implementing 

```py
def state_dict(self):
    state = super().state_dict()
    for name in list(state.keys()):
        if "lora" not in name:  # <-- adapt the condition to your use case
            state.pop(name)
    return state
```
in the LightningModule.

Another option is to override the [`on_save_checkpoint`](https://lightning.ai/docs/pytorch/stable/common/lightning_module.html#on-save-checkpoint
) hook:

```py
def on_save_checkpoint(self, checkpoint):
    state = checkpoint["state_dict"]
    for name in list(state.keys()):
        if "lora" not in name:  # <-- adapt the condition to your use case
            state.pop(name)
    return state
```

**Comment by NingJinzhong** [comment]
thanks!

**Comment by awaelchli** [comment]
FYI we also have LoRA in our hackable Lit-GPT in case you are interested to check it out: https://github.com/Lightning-AI/lit-gpt

**Comment by devansh20la** [comment]
I get a RuntimeError: OrderedDict mutated during iteration with both these approaches.

**Comment by Boltzmachine** [comment]
> FYI we also have LoRA in our hackable Lit-GPT in case you are interested to check it out: https://github.com/Lightning-AI/lit-gpt

Hi may I know where I can find the hack in litgpt?

**Comment by Boltzmachine** [comment]
You may find this function is useful

https://github.com/huggingface/peft/blob/c1fe8105a5a4a612a6178699e1def5c66c2638d2/src/peft/utils/save_and_load.py#L51
