### ISSUE TITLE
Training time increasing after updating torch / pytorch-lightning

### ISSUE THREAD

**Issue by KobanBanan** [Lightning-AI/pytorch-lightning#19178]
### Bug description

After upgrading python and pytorch-lightning  and dependancies i have training time degradation. 
Here is my setup before and after update

Python: Python 3.6.8 **VS** Python 3.9.18
OS: rhel7 **VS** rhel8
torch: torch==1.10.2+cu113 **VS** torch==2.0.1
pytorch-lightning: pytorch-lightning==1.5.10 **VS** pytorch-lightning==2.1.2
CUDA 11.5 **VS** 11.8
CUDANN: libcudnn8-8.3.3.40-1.cuda11.5 **VS** libcudnn8-8.9.1.23-1.cuda11.8
GPU: NVIDIA A100-PCIE-40GB

Here is python 3.6 training time 
<img width="737" alt="3 6" src="https://github.com/Lightning-AI/pytorch-lightning/assets/34056452/ee431e19-8f79-4e8f-89d7-6c047279da50">

and here is python 3.9 training time
<img width="634" alt="3 8" src="https://github.com/Lightning-AI/pytorch-lightning/assets/34056452/b66430da-3ea5-475e-b7e9-25dda3fda1e0">

i did not changed the script. Why am i having such performance degradation ? The script is running in Docker container. 

### What version are you seeing the problem on?

v2.1

### Error messages and logs

```
# Error messages and logs here please
```

### Environment

<details>
  <summary>Current environment</summary>

```
#- PyTorch Lightning Version: 2.1.2
#- PyTorch Version: 2.0.1
#- Python version: 3.9.18
#- OS : rhel8
#- CUDA/cuDNN version: 11.8 /  libcudnn8-8.9.1.23-1.cuda11.8
#- GPU models and configuration: NVIDIA A100-PCIE-40GB
#- How you installed Lightning: pip install 
#- Running environment of LightningApp: Docker 
```

</details>
 

cc @borda

**Comment by awaelchli** [comment]
The versions gap is quite large, so it is very hard to guess what could be the difference. It might just be about defaults that changed.

Perhaps you could narrow it down by only changing one variable at a time, i.e., upgrade only the python version, or take smaller version jumps until you find the problematic one.

**Comment by awaelchli** [comment]
@KobanBanan Have you made any new findings ever since?
