### ISSUE TITLE
`all_gather` of `SingleDeviceStrategy` does not return a tensor of shape (world_size, batch, ...)

### ISSUE THREAD

**Issue by function2-llx** [Lightning-AI/pytorch-lightning#19195]
### 📚 Documentation

The doc for `Fabric.all_gather` says:

https://github.com/Lightning-AI/pytorch-lightning/blob/002a465f849d64f01214d26a7b3e14c9bdc41d6c/src/lightning/fabric/fabric.py#L559-L561

However, the `all_gather` of `SingleDeviceStrategy` just returns the original tensor.

https://github.com/Lightning-AI/pytorch-lightning/blob/002a465f849d64f01214d26a7b3e14c9bdc41d6c/src/lightning/fabric/strategies/single_device.py#L72-L74

cc @borda @carmocca @justusschock @awaelchli

**Comment by awaelchli** [comment]
@function2-llx What do you think is better: unsqueeze the dimension, or change the documentation?

**Comment by function2-llx** [comment]
In my opinion, it depends on the principle of Fabric.
If Fabric tends to provide a more unified interface that is agnostic to the environment (e.g., number of devices in this case) and reduce boilerplate code (i.e., branch by `fabric.world_size`), then unsqueeze the dimension is better (and maybe also detach the tensor for consistency). For example, in my use case, even I developed a program using multiple devices, I usually want to debug it on a single device; I may also migrate my program to only use a single device when a device with larger memory is available.
However, if backward compatibility is at higher priority at this time and such boilerplate code is tolerable and expected when using Fabric, changing the documentation is also fine.
