### ISSUE TITLE
'load_from_checkpoint' error

### ISSUE THREAD

**Issue by liziru** [Lightning-AI/pytorch-lightning#19219]
### Bug description

I have encountered an error when load_from_checkpoint.  I tried to resume training a gan model with four gpus from the old checkpoint but I found GPU0 memory used was very high, and the training program exited with an error message 'torch.cuda.OutOfMemoryError: CUDA out of memory.'.  
![image](https://github.com/Lightning-AI/pytorch-lightning/assets/34911790/8ba3de46-225b-4173-8f74-4965d5f39ec6)
Another strange phenomenon is that 4 processes are using GPU0.
![image](https://github.com/Lightning-AI/pytorch-lightning/assets/34911790/1e207826-86d0-40e3-a605-2992e2151d0e)

![image](https://github.com/Lightning-AI/pytorch-lightning/assets/34911790/8b59f2fa-7b4a-4dde-a52a-d343b9d49984)
I also tried to train without loading the checkpoint and the GPU performance was ok.
![image](https://github.com/Lightning-AI/pytorch-lightning/assets/34911790/6c6b3fd9-3782-484b-ae7a-aebe88732994)

Thanks for any advice.

### What version are you seeing the problem on?

v2.1

### How to reproduce the bug

```python
system class is a 'pl.LightningModule' model.

   system = initialize_module(conf["system"]["path"], initialize=False).load_from_checkpoint(
            conf["trainer"]["fit"]['ckpt_path'], **system_args)
```
```


### Error messages and logs

```
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 16.00 MiB. GPU 0 has a total capacty of 11.77 GiB of which 20.06 MiB is free. Including non-PyTorch memory, this process has 9.53 GiB memory in use. Process 11259 has 739.00 MiB memory in use. Process 11260 has 739.00 MiB memory in use. Process 11261 has 739.00 MiB memory in use. Of the allocated memory 7.56 GiB is allocated by PyTorch, and 515.27 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
Epoch 0:   1%|          | 6/631 [02:08<3:43:04,  0.05it/s, v_num=12]       
```


### Environment

<details>
  <summary>Current environment</summary>

```
#- Lightning Component (e.g. Trainer, LightningModule, LightningApp, LightningWork, LightningFlow):
#- PyTorch Lightning Version (e.g., 1.5.0): 2.1.1
#- Lightning App Version (e.g., 0.5.2):
#- PyTorch Version (e.g., 2.0): 2.1.1
#- Python version (e.g., 3.9): 3.10
#- OS (e.g., Linux): ubuntu 20.04
#- CUDA/cuDNN version: 
#- GPU models and configuration: gan model
#- How you installed Lightning(`conda`, `pip`, source): pip 
#- Running environment of LightningApp (e.g. local, cloud): local 
```

</details>


### More info

_No response_

**Comment by awaelchli** [comment]
@liziru Are the weights in your checkpoint saved with device on cuda device 0? Your 4 processes are probably all trying to load the checkpoint into GPU 0. Try setting `.load_from_checkpoint(..., map_location="cpu")`

**Comment by awaelchli** [comment]
@liziru Can you give this a try?

Also, if your intention is to resume training, you should use `trainer.fit(model, ckpt_path=...)` to resume from a checkpoint file.

**Comment by liziru** [comment]
> @liziru Are the weights in your checkpoint saved with device on cuda device 0? Your 4 processes are probably all trying to load the checkpoint into GPU 0. Try setting `.load_from_checkpoint(..., map_location="cpu")`

It does work. Thanks a lot.
