### ISSUE TITLE
load_from_checkpoint not working at all

### ISSUE THREAD

**Issue by YixuannnL** [Lightning-AI/pytorch-lightning#19218]
### Bug description

I want to use my trained model to predict something, so in my own predict module, i use load_from_checkpoint to load a ckpt to my model

` new_model = DiFFdisenSystem(hparams)`
` model = copy.deepcopy(new_model)`
` new_model.load_from_checkpoint('ckpts/12.27-freq-self-coord/last.ckpt')`

and to verify whether or not the model has already loaded the ckpt, i use
`for (name, param), (new_name, new_param) in zip(model.named_parameters(), new_model.named_parameters()):`
          `  if torch.equal(param, new_param):`
              `        print(f"Parameters in {name} are the same.")`
         `  else:`
              `        print(f"Parameters in {name} are different.")`
and the printing output turns out each parameter is the SAME!

### What version are you seeing the problem on?

v1.9

### How to reproduce the bug

```python
class DiFFdisenSystem(LightningModule):

    def __init__(
        self,
        hparams,
    ):
        super().__init__()
        self.save_hyperparameters(hparams)

        self.model = BeatGANsAutoencConfig(
            enc_out_channels = self.hparams.enc_out_channels,
            enc_attn_resolutions = self.hparams.enc_attn_resolutions,
            enc_pool = self.hparams.enc_pool,
            enc_num_res_block = self.hparams.enc_num_res_block,
            enc_channel_mult = self.hparams.enc_channel_mult,
            enc_grad_checkpoint = self.hparams.enc_grad_checkpoint,
            latent_net_conf = None,
        ).make_model()
        
        # self.model = ToyModel()
        
        self.tr_noise_scheduler = DDIMScheduler.from_pretrained(self.hparams.pretrained_model_name_or_path, subfolder='scheduler')
        self.noise_scheduler = DDIMScheduler.from_pretrained(self.hparams.pretrained_model_name_or_path, subfolder='scheduler')
        self.vae = AutoencoderKL.from_pretrained(self.hparams.pretrained_model_name_or_path, subfolder='vae')
        self.scale_factor = 0.18125
        
        self.vae_channel = 4
        self.vae_out_dim = 16               
        
        self.reduce_channel = nn.Conv2d(in_channels=8, out_channels=4, kernel_size=1)
        
        freeze_params(self.vae.parameters())
```

### Error messages and logs

```
# Error messages and logs here please
```

### Environment

<details>
  <summary>Current environment</summary>

```
#- Lightning Component (e.g. Trainer, LightningModule, LightningApp, LightningWork, LightningFlow):
#- PyTorch Lightning Version (e.g., 1.5.0):
#- Lightning App Version (e.g., 0.5.2):
#- PyTorch Version (e.g., 2.0):
#- Python version (e.g., 3.9):
#- OS (e.g., Linux):
#- CUDA/cuDNN version:
#- GPU models and configuration:
#- How you installed Lightning(`conda`, `pip`, source):
#- Running environment of LightningApp (e.g. local, cloud):
```

</details>

**Comment by awaelchli** [comment]
Hi

You need to use

```py
new_model = DiFFdisenSystem.load_from_checkpoint('ckpts/12.27-freq-self-coord/last.ckpt', hparams=hparams)
```
(and delete the deepcopy call)

In recent versions of Lightning, the previous way would error now and inform the user of the correct usage.

**Comment by YixuannnL** [comment]
您好，我已经收到您的邮件。我将尽快给您回复。谢谢！

**Comment by awaelchli** [comment]
@YixuannnL Could you give this a try and let me know if that resolves your issue?

**Comment by awaelchli** [comment]
@YixuannnL I didn't get a reply from you, but I'm confident that my previous answer will resolve the issue with the code that you use to load and verify.
