### ISSUE TITLE
ImportError: cannot import name '_distributed_available' from  'lightning_fabric.utilities.distributed' 

### ISSUE THREAD

**Issue by linnew007** [Lightning-AI/pytorch-lightning#19217]
### Bug description

system  ubuntu22.04  python 3.10.12.when run python webui.py --xformers ,there are some errors.deails:

***/anaconda3/envs/stablediffusionenv/lib/python3.10/site-packages/pytorch_lightning/uti │
│ lities/distributed.py:22 in <module>                                                         │
│                                                                                              │
│    19 from torch.nn.parallel.distributed import DistributedDataParallel                      │
│    20                                                                                        │
│    21 from lightning_fabric.utilities.distributed import _all_gather_ddp_if_available as new │
│ ❱  22 from lightning_fabric.utilities.distributed import _distributed_available as new_distr │
│    23 from lightning_fabric.utilities.distributed import _gather_all_tensors as new_gather_a │
│    24 from lightning_fabric.utilities.distributed import (                                   │
│    25 │   _get_default_process_group_backend_for_device as new_get_default_process_group_bac │
╰──────────────────────────────────────────────────────────────────────────────────────────────╯
ImportError: cannot import name '_distributed_available' from 
'lightning_fabric.utilities.distributed' 

### What version are you seeing the problem on?

v2.1

### How to reproduce the bug

```python
python run webui.py --xformers
```

### Error messages and logs

```
# Error messages and logs here please
```
***/anaconda3/envs/stablediffusionenv/lib/python3.10/site-packages/pytorch_lightning/uti │
│ lities/distributed.py:22 in <module>                                                         │
│                                                                                              │
│    19 from torch.nn.parallel.distributed import DistributedDataParallel                      │
│    20                                                                                        │
│    21 from lightning_fabric.utilities.distributed import _all_gather_ddp_if_available as new │
│ ❱  22 from lightning_fabric.utilities.distributed import _distributed_available as new_distr │
│    23 from lightning_fabric.utilities.distributed import _gather_all_tensors as new_gather_a │
│    24 from lightning_fabric.utilities.distributed import (                                   │
│    25 │   _get_default_process_group_backend_for_device as new_get_default_process_group_bac │
╰──────────────────────────────────────────────────────────────────────────────────────────────╯
ImportError: cannot import name '_distributed_available' from 
'lightning_fabric.utilities.distributed' 

### Environment

<details>
  <summary>Current environment</summary>

```
#- Lightning Component (e.g. Trainer, LightningModule, LightningApp, LightningWork, LightningFlow):
#- PyTorch Lightning Version (e.g., 1.5.0):
#- Lightning App Version (e.g., 0.5.2):
#- PyTorch Version (e.g., 2.0):
#- Python version (e.g., 3.9):
#- OS (e.g., Linux):
#- CUDA/cuDNN version:
#- GPU models and configuration:
#- How you installed Lightning(`conda`, `pip`, source):
#- Running environment of LightningApp (e.g. local, cloud):
```

</details>

**Comment by linnew007** [comment]
have a solution.copy the function "_distributed_available" from pytorch_lightning 1.9.5 (lightning_fabric.utilities.distributed')to 2.1.3(lightning_fabric.utilities.distributed'),Then restart stable diffusion webui,correctly working.

the function code:
def _distributed_available() -> bool:
    from lightning_fabric.accelerators.tpu import _tpu_distributed

    return torch.distributed.is_available() and torch.distributed.is_initialized() or _tpu_distributed()

**Comment by awaelchli** [comment]
@linnew007 The reason is likely because you ended up with different, mismatching versions of pytorch-lightning and lightning-fabric. Could you verify this by pasting the output of 

```
pip list | grep lightning
```
here please?

**Comment by awaelchli** [comment]
@linnew007 can you check?
