### ISSUE TITLE
Customizing PyTorch Lightning ModelCheckpoint Callback for Dual Model Weights Checkpointing

### ISSUE THREAD

**Issue by arashno** [Lightning-AI/pytorch-lightning#19228]
### Description & Motivation

Hi there,

I am currently working on a project using PyTorch Lightning and I need to save two different versions of my model's weights during the checkpointing process. Specifically, I want to save:

1. Regular weights
2. The results of applying a particular function on the regular weights

I am aware that I can achieve this by saving the regular checkpoint and later applying the function, but I am looking for a more streamlined approach by integrating this dual checkpointing directly into the training code. Additionally, the function I want to apply during checkpointing requires some parameters that are readily available during training but are challenging to retrieve from a checkpoint.

How can I customize the ModelCheckpoint callback in PyTorch Lightning to accomplish this task? I am not interested in overriding monitoring or other functionalities provided by the callback; rather, I simply want to modify its behavior to save two checkpoints instead of one whenever it gets called.

Your guidance on this customization would be greatly appreciated.

Thank you!

cc @borda @carmocca @awaelchli

**Comment by awaelchli** [comment]
I think modifying the ModelCheckpoint callback to save two files instead of one is going to be too challenging, because many features like `save_top_k` etc. won't work properly when each checkpoint file has two versions. 

A better approach could be to use two ModelCheckpoint instances, where one is just saving the regular weights and the other is a custom subclass where you apply a transformation in `_save_checkpoint`. 

Rough sketch:

```py
class CustomModelCheckpiont(ModelCheckpoint):
    def _save_checkpoint(self, trainer, filepath):
        trainer.lightning_module.save_transformed_model = True
        super()._save_checkpoint(trainer, filepath)
        
class MyLightningModule(LightningModule):
	def __init__(self):
		...
		self.save_transformed_model = False
	
	def on_save_checkpoint(self, checkpoint):
		if self.save_transformed_model:
			checkpoint["state_dict"] = my_transformation(checkpoint["state_dict"])
			self.save_transformed_model = False
         

checkpoint1 = ModelCheckpiont(...)
checkpoint2 = CustomModelCheckpiont(...)
trainer = Trainer(callbacks=[checkpoint1, checkpoint2], ...)
```

**Comment by arashno** [comment]
Great!
That is all I need.
Thanks.
