### ISSUE TITLE
lighting.pytorch IS NOT pytorch_lightning

### ISSUE THREAD

**Issue by svnv-svsv-jm** [Lightning-AI/pytorch-lightning#19252]
### Bug description

Documentation mentions that `pytorch_lightning` is now `lightning`, and that the old API can be found at `lightning_pytorch`.

And yet, if you do:

```python
import lightning.pytorch as pl
from pytorch_lightning import LightningModule

class MyModel(LightningModule):
    pass

model = MyModel()
trainer = pl.Trainer()
trainer.fit(model)
```
this still won't work, you will get:

```
TypeError: `model` must be a `LightningModule` or `torch._dynamo.OptimizedModule`, got `LightningModule`
```

because the `Trainer` was imported from `lightning.pytorch`, while the model is a `LightningModule` from `pytorch_lightning`. Are they the same or not?

Why can't we "mix" them?

This is sometimes necessary when working with other packages where some rely on `lightning` or `lightning.pytorch`, and other rely on `pytorch_lightning`.

### What version are you seeing the problem on?

v2.0

### How to reproduce the bug

```python
import lightning.pytorch as pl
from pytorch_lightning import LightningModule

class MyModel(LightningModule):
    pass

model = MyModel()
trainer = pl.Trainer()
trainer.fit(model)
```

### Error messages and logs

```
# Error messages and logs here please
```

### Environment

<details>
  <summary>Current environment</summary>

```
#- Lightning Component (e.g. Trainer, LightningModule, LightningApp, LightningWork, LightningFlow):
#- PyTorch Lightning Version (e.g., 1.5.0):
#- Lightning App Version (e.g., 0.5.2):
#- PyTorch Version (e.g., 2.0):
#- Python version (e.g., 3.9):
#- OS (e.g., Linux):
#- CUDA/cuDNN version:
#- GPU models and configuration:
#- How you installed Lightning(`conda`, `pip`, source):
#- Running environment of LightningApp (e.g. local, cloud):
```

</details>

**Comment by awaelchli** [comment]
Hi @svnv-svsv-jm 

> because the Trainer was imported from lightning.pytorch, while the model is a LightningModule from pytorch_lightning. Are they the same or not?
> 
> Why can't we "mix" them?

They are two different packages, with the same source code and the only difference is the imports. But Python doesn't know that, so you can't mix them together in the same source code. If you import LightningModule from one package, but the Trainer from the other one, it won't work. They are not meant to be interchangeable. 

> This is sometimes necessary when working with other packages where some rely on lightning or lightning.pytorch, and other rely on pytorch_lightning.

It's not possible to mix them. You will have to rewrite the code so that all of it is only from one package.

**Comment by svnv-svsv-jm** [comment]
Thanks a lot for your reply!

So it is literally source code duplication?

I thought that in the `lightning.pytorch` module, you would just import `pytorch_lightning`, but it is the same code. Why maintain two exact replicas?

Just curious at this point.

**Comment by awaelchli** [comment]
We don't maintain two copies of the code. We maintain lightning (see the content in GitHub here) and generate the pytorch_lightning package automatically. 

That there are two packages is a consequence of the decision to rename the package from pytorch-lightning to lightning.

**Comment by svnv-svsv-jm** [comment]
Ok, thanks lot!

**Comment by awaelchli** [comment]
Thanks and you're welcome. Sorry for the inconvenience. Over time, more users will switch to the new package name and these questions and struggles will hopefully disappear in history.
