### ISSUE TITLE
Type hint for `configure_optimizers` does not include `Sequence[OptimizerLRSchedulerConfig]`

### ISSUE THREAD

**Issue by tilman151** [Lightning-AI/pytorch-lightning#19276]
### 📚 Documentation

The return type hints for the `configure_optimizers` method of the `LightningModule` do not include  `Sequence[OptimizerLRSchedulerConfig]` even though it is a valid return type. The docs themself state so and it runs without problem.

Nevertheless, it is linted by `mypy` to be invalid and breaks our CI.

cc @borda

**Comment by awaelchli** [comment]
I think a sequence is allowed (for manual optimization). So updating the type sounds good to me.

**Comment by tilman151** [comment]
@awaelchli I would be willing to do it myself. Shouldn't be that hard, hopefully.

**Comment by awaelchli** [comment]
@tilman151 Yes that would be great. It should just be updating that type hint I think.
