### ISSUE TITLE
When initialising groups for DDP, a certain amount of memory is accumulated on the 0th GPU.

### ISSUE THREAD

**Issue by drizzle0171** [Lightning-AI/pytorch-lightning#19284]
### Bug description

Hi, I want to use DDP in pytorch lightning, but I'm reaching out to you because I saw a strange error today. 

As shown in the code below, when I initialise the model, it keeps taking up more than a certain amount of memory. If this memory grab was happening on all GPUs, I'd be fine with it, but you can see that it's consistently piling up to zero.

```python
    data = DataModule(args.batch_size)
    
    checkpoint_callback = ModelCheckpoint(
        dirpath = args.checkpoint_dir,
        filename = '{epoch}-{val_loss:.2f}',
        monitor="val_loss"
    )
    
    
    trainer = Trainer(
        log_every_n_steps=50,
        accelerator='gpu',
        strategy = DDPStrategy(find_unused_parameters=False),
        devices=4,
        max_epochs=args.max_epochs,
        resume_from_checkpoint=args.resume_from_checkpoint,
        logger=wandb_logger,
        enable_progress_bar=True,
        callbacks=[
            checkpoint_callback,
        ]
    )
    model = CLIP() # that I implemented
    
    trainer.fit(model, data)

```
Additionally, if you pass the DDPStrategy class or the string "ddp" as the strategy argument to Trainer, you can see that a certain amount of memory continues to be stacked at time 0 whenever group is initialised, as shown below.

![image](https://github.com/Lightning-AI/pytorch-lightning/assets/90444862/919a1ef9-4b99-4f1c-90be-a6dc449e6e86)

I didn't get this error before, but it happened suddenly and I'm very confused. Maybe I'm missing something, and if anyone has experienced it, please share. Thank you.

### What version are you seeing the problem on?

v1.8

### How to reproduce the bug

```python
.
```

### Error messages and logs

There was no error message but only memory imbalance.

### Environment

<details>
  <summary>Current environment</summary>

```
#- Lightning Component (e.g. Trainer, LightningModule, LightningApp, LightningWork, LightningFlow): Trainer
#- PyTorch Lightning Version (e.g., 1.5.0): 1.7.7
#- Lightning App Version (e.g., 0.5.2): X
#- PyTorch Version (e.g., 2.0): 1.12.1
#- Python version (e.g., 3.9): 3.8
#- OS (e.g., Linux): Linux
#- CUDA/cuDNN version: 11.6
#- GPU models and configuration: RTX 4080
#- How you installed Lightning(`conda`, `pip`, source): pip
#- Running environment of LightningApp (e.g. local, cloud): server (local)
```

</details>

**Comment by awaelchli** [comment]
@drizzle0171 Are you loading a checkpoint somewhere? Note that if you do, and the checkpoint contains cuda tensors, they will be allocated on device 0. You will have to add `map_location="cpu"` if you want to prevent that. Or you may have some code before `trainer.fit()` that allocates device memory. This can't be controlled by Lightning.

**Comment by awaelchli** [comment]
Hey @drizzle0171 
Can you check my reply please?
Have you tried `map_location="cpu"` when loading the checkpoint?

**Comment by drizzle0171** [comment]
Oh! I'm sorry I missed your message. As you said, I loaded a checkpoint from a library. So I fixed the problems. Thank you very much.
