### ISSUE TITLE
ModelCheckpoint does not save the last checkpoint on local file system

### ISSUE THREAD

**Issue by shenmishajing** [Lightning-AI/pytorch-lightning#19325]
### Bug description

<img width="690" alt="Screenshot 2024-01-22 113852" src="https://github.com/Lightning-AI/pytorch-lightning/assets/32559715/08f6a3b3-bbac-47fd-ba47-575834100a88">

As demonstrated in the above figure, checkpoints will only be saved as topk best checkpoints and the last checkpoint is only a link for the last **best** checkpoint instead of the last checkpoint. The excepted behaviour should be creating a link if we already save the checkpoint in as the topk best checkpoint, and save the checkpoint as a file if we do not save checkpoint for this epoch as the topk best checkpoint.

### What version are you seeing the problem on?

v2.1

### Error messages and logs

```
# Error messages and logs here please
```

### Environment

<details>
  <summary>Current environment</summary>

* CUDA:
	- GPU:
		- NVIDIA GeForce RTX 4090
		- NVIDIA GeForce RTX 4090
		- NVIDIA GeForce RTX 4090
		- NVIDIA GeForce RTX 4090
		- NVIDIA GeForce RTX 4090
		- NVIDIA GeForce RTX 4090
		- NVIDIA GeForce RTX 4090
		- NVIDIA GeForce RTX 4090
	- available:         True
	- version:           12.1
* Lightning:
	- lightning:         2.1.3
	- lightning-template: 1.6.1.dev0+dirty
	- lightning-utilities: 0.10.0
	- pytorch-lightning: 2.1.3
	- torch:             2.1.2
	- torchaudio:        2.1.2
	- torchmetrics:      1.2.1
	- torchvision:       0.16.2
* Packages:
	- accessible-pygments: 0.0.4
	- aiohttp:           3.9.1
	- aiosignal:         1.3.1
	- alabaster:         0.7.13
	- antlr4-python3-runtime: 4.9.3
	- anyascii:          0.3.2
	- appdirs:           1.4.4
	- argcomplete:       3.1.6
	- astroid:           3.0.2
	- attrs:             23.2.0
	- babel:             2.14.0
	- beautifulsoup4:    4.12.2
	- build:             1.0.3
	- cachetools:        5.3.2
	- certifi:           2023.11.17
	- cfgv:              3.4.0
	- chardet:           5.2.0
	- charset-normalizer: 3.3.2
	- click:             8.1.7
	- colorama:          0.4.6
	- commitizen:        3.13.0
	- contourpy:         1.2.0
	- coverage:          7.4.0
	- cycler:            0.12.1
	- decli:             0.6.1
	- distlib:           0.3.8
	- distro:            1.9.0
	- docker-pycreds:    0.4.0
	- docstring-parser:  0.15
	- docutils:          0.20.1
	- filelock:          3.13.1
	- fonttools:         4.47.0
	- frozenlist:        1.4.1
	- fsspec:            2023.12.2
	- gitdb:             4.0.11
	- gitpython:         3.1.40
	- identify:          2.5.33
	- idna:              3.6
	- imagesize:         1.4.1
	- importlib-metadata: 6.11.0
	- importlib-resources: 6.1.1
	- iniconfig:         2.0.0
	- jinja2:            3.1.2
	- joblib:            1.3.2
	- jsonargparse:      4.27.1
	- jsonnet:           0.20.0
	- jsonschema:        4.20.0
	- jsonschema-specifications: 2023.12.1
	- kiwisolver:        1.4.5
	- lightning:         2.1.3
	- lightning-template: 1.6.1.dev0+dirty
	- lightning-utilities: 0.10.0
	- livereload:        2.6.3
	- logmatic-python:   0.1.7
	- markdown-it-py:    3.0.0
	- markupsafe:        2.1.3
	- matplotlib:        3.8.2
	- mdit-py-plugins:   0.4.0
	- mdurl:             0.1.2
	- mpmath:            1.3.0
	- multidict:         6.0.4
	- myst-parser:       2.0.0
	- networkx:          3.2.1
	- nodeenv:           1.8.0
	- numpy:             1.26.2
	- nvidia-cublas-cu12: 12.1.3.1
	- nvidia-cuda-cupti-cu12: 12.1.105
	- nvidia-cuda-nvrtc-cu12: 12.1.105
	- nvidia-cuda-runtime-cu12: 12.1.105
	- nvidia-cudnn-cu12: 8.9.2.26
	- nvidia-cufft-cu12: 11.0.2.54
	- nvidia-curand-cu12: 10.3.2.106
	- nvidia-cusolver-cu12: 11.4.5.107
	- nvidia-cusparse-cu12: 12.1.0.106
	- nvidia-nccl-cu12:  2.18.1
	- nvidia-nvjitlink-cu12: 12.3.101
	- nvidia-nvtx-cu12:  12.1.105
	- omegaconf:         2.3.0
	- packaging:         23.2
	- pandas:            2.1.4
	- pillow:            10.1.0
	- pip:               23.3.1
	- platformdirs:      4.1.0
	- pluggy:            1.3.0
	- pre-commit:        3.6.0
	- prompt-toolkit:    3.0.36
	- protobuf:          4.25.1
	- psutil:            5.9.7
	- pydata-sphinx-theme: 0.14.4
	- pygments:          2.17.2
	- pyparsing:         3.1.1
	- pyproject-api:     1.6.1
	- pyproject-hooks:   1.0.0
	- pytest:            7.4.4
	- pytest-cov:        4.1.0
	- python-dateutil:   2.8.2
	- python-json-logger: 2.0.7
	- pytorch-lightning: 2.1.3
	- pytz:              2023.3.post1
	- pyyaml:            6.0.1
	- questionary:       2.0.1
	- reconplogger:      4.12.0
	- referencing:       0.32.0
	- requests:          2.31.0
	- rich:              13.7.0
	- rpds-py:           0.16.2
	- ruff:              0.1.11
	- ruyaml:            0.91.0
	- scikit-learn:      1.3.2
	- scipy:             1.11.4
	- sentry-sdk:        1.39.1
	- setproctitle:      1.3.3
	- setuptools:        68.2.2
	- shell-command-launcher: 1.0.6
	- six:               1.16.0
	- smmap:             5.0.1
	- snowballstemmer:   2.2.0
	- soupsieve:         2.5
	- speed-benchmark:   1.0.3
	- sphinx:            7.2.6
	- sphinx-autoapi:    3.0.0
	- sphinx-autobuild:  2021.3.14
	- sphinx-book-theme: 1.1.0
	- sphinx-design:     0.5.0
	- sphinxcontrib-applehelp: 1.0.7
	- sphinxcontrib-devhelp: 1.0.5
	- sphinxcontrib-htmlhelp: 2.0.4
	- sphinxcontrib-jsmath: 1.0.1
	- sphinxcontrib-qthelp: 1.0.6
	- sphinxcontrib-serializinghtml: 1.1.9
	- sympy:             1.12
	- termcolor:         2.4.0
	- thop:              0.1.1.post2209072238
	- threadpoolctl:     3.2.0
	- tomlkit:           0.12.3
	- torch:             2.1.2
	- torchaudio:        2.1.2
	- torchmetrics:      1.2.1
	- torchvision:       0.16.2
	- tornado:           6.4
	- tox:               4.11.4
	- tqdm:              4.66.1
	- triton:            2.1.0
	- typeshed-client:   2.4.0
	- typing-extensions: 4.9.0
	- tzdata:            2023.4
	- urllib3:           2.1.0
	- virtualenv:        20.25.0
	- wandb:             0.16.1
	- wcwidth:           0.2.12
	- wheel:             0.41.2
	- yarl:              1.9.4
	- zipp:              3.17.0
* System:
	- OS:                Linux
	- architecture:
		- 64bit
		- ELF
	- processor:         x86_64
	- python:            3.11.5
	- release:           5.15.0-91-generic
	- version:           #101-Ubuntu SMP Tue Nov 14 13:30:08 UTC 2023

</details>

### More info

A simple fix will be just that we first try to remove the existing `last.ckpt` before we save the last checkpoint and then set the `self._last_checkpoint_saved` var to `None` after we have saved the last checkpoint. Change the following code

https://github.com/Lightning-AI/pytorch-lightning/blob/d02009af76531e803a6e1593827894b436e366fc/src/lightning/pytorch/callbacks/model_checkpoint.py#L689-L694

to

```python
        # set the last model path before saving because it will be part of the state.
        previous, self.last_model_path = self.last_model_path, filepath
        self._remove_checkpoint(trainer, filepath)
        if _is_local_file_protocol(filepath) and self._last_checkpoint_saved and self.save_top_k != 0:
            self._link_checkpoint(trainer, self._last_checkpoint_saved, filepath)
        else:
            self._save_checkpoint(trainer, filepath)
        self._last_checkpoint_saved = None
```

cc @carmocca @awaelchli

**Comment by awaelchli** [comment]
@shenmishajing Sorry I don't understand what the problem is. Your description does not match the screenshot. In the screenshot, we can see three checkpoints. The best checkpoint is the one with the lowest loss, which is 3.286 and the correct file. The last checkpoint is the one that was saved last, that is the one with the highest epoch/step number which is in your case epoch 3. This all looks correct to me. 

But one thing that is confusing is that best.ckpt is a link. Why? Are you running a custom checkpoint callback? In the bug report, you left out the section "How to reproduce the bug". Without a code example, I'm afraid I probably can't help here.

**Comment by shenmishajing** [comment]
@awaelchli Hi, sorry for my unclear description and the problem is that the experiment I have runned has 24 epoches, but all checkpoints behind epoch 3 did not be sved since the metric of them was worse than the metric of the epoch 0, 2 and 3. Therefore, them were not saved as the top3 best checkpoint, and then, in the save last func, we still try to create a link for the checkpoint of epoch 3 then we did not clear the var `self._last_checkpoint_saved`, and so, we lost the last checkpoint. The correct logic should be if we save checkpoint for the current epoch, we create a link for it, but if we do not save the current checkpoint in the save best func, we should remove the original link file and call the `self._save_checkpoint`.

> Without a code example, I'm afraid I probably can't help much.

Ok, I skip this part since I think the code to reproduce this is simple, you can create a toy model to return val loss as [10, 9, 8, 7, 11, 12, 13, 6, 5, 4] at epoch 0 to 9 and checkpoint callback with topk = 3. You will find that every thing goes well before our val loss is equal to 11, at which point, we will get three checkpoints and the `last.ckpt` link to the val_loss=7 checkpoint. However, in the val loss = 11 epoch,  since we do not save this checkpoint since 11 is less than 9, 8, 7, the `self._last_checkpoint_saved` var is still pointing to the val_loss=7 checkpoint, so we lost the checkpoint of this epoch. The excepted behaviour should be that we save the checkpoint for this epoch as a file instead of creating a link. It will be the same for val loss = 12 and 13. The [ 6, 5, 4 ] is used to test we can remove the checkpoint file and create a link again.

> But one thing that is confusing is that best.ckpt is a link. Why? Are you running a custom checkpoint callback?

Yeah, I customize the best ckpt part. It's irrelavent to this bug, we can just ignore it.

**Comment by awaelchli** [comment]
I followed your description and created this example:

```
import os

import torch
from lightning.pytorch import LightningModule, Trainer
from torch.utils.data import DataLoader, Dataset

from lightning.pytorch.callbacks import ModelCheckpoint


class RandomDataset(Dataset):
    def __init__(self, size, length):
        self.len = length
        self.data = torch.randn(length, size)

    def __getitem__(self, index):
        return self.data[index]

    def __len__(self):
        return self.len


class BoringModel(LightningModule):
    def __init__(self):
        super().__init__()
        self.layer = torch.nn.Linear(32, 2)

    def forward(self, x):
        return self.layer(x)

    def training_step(self, batch, batch_idx):
        loss = self(batch).sum()
        self.log("train_loss", loss)
        return {"loss": loss}

    def validation_step(self, batch, batch_idx):
        loss = self(batch).sum()
        metrics = [10, 9, 8, 7, 11, 12, 13, 6, 5, 4]
        self.log("valid_loss", metrics[self.current_epoch])

    def configure_optimizers(self):
        return torch.optim.SGD(self.layer.parameters(), lr=0.1)


train_data = DataLoader(RandomDataset(32, 64), batch_size=2)
val_data = DataLoader(RandomDataset(32, 64), batch_size=2)

model = BoringModel()
trainer = Trainer(
    callbacks=ModelCheckpoint(save_top_k=3, dirpath="checkpoints", monitor="valid_loss", save_last=True),
    enable_progress_bar=False,
    enable_model_summary=False,
    max_epochs=10,
)
trainer.fit(model, train_dataloaders=train_data, val_dataloaders=val_data)

print(os.listdir("checkpoints"))
# print output:
# ['epoch=9-step=320.ckpt', 'last.ckpt', 'epoch=8-step=288.ckpt', 'epoch=7-step=256.ckpt']
print(os.readlink("checkpoints/last.ckpt"))
# print output:
# ..../checkpoints/epoch=9-step=320.ckpt

```

I used Lightning 2.1.3 here. Please confirm that you are also using this version.
The output is correct, the last.ckpt points to 9 which was the last one saved. 

Please modify the above example to show the unexpected behavior. Thank you.

**Comment by shenmishajing** [comment]
> I followed your description and created this example:
> 
> ```python
> import os
> 
> import torch
> from lightning.pytorch import LightningModule, Trainer
> from torch.utils.data import DataLoader, Dataset
> 
> from lightning.pytorch.callbacks import ModelCheckpoint
> 
> 
> class RandomDataset(Dataset):
>     def __init__(self, size, length):
>         self.len = length
>         self.data = torch.randn(length, size)
> 
>     def __getitem__(self, index):
>         return self.data[index]
> 
>     def __len__(self):
>         return self.len
> 
> 
> class BoringModel(LightningModule):
>     def __init__(self):
>         super().__init__()
>         self.layer = torch.nn.Linear(32, 2)
> 
>     def forward(self, x):
>         return self.layer(x)
> 
>     def training_step(self, batch, batch_idx):
>         loss = self(batch).sum()
>         self.log("train_loss", loss)
>         return {"loss": loss}
> 
>     def validation_step(self, batch, batch_idx):
>         loss = self(batch).sum()
>         metrics = [10, 9, 8, 7, 11, 12, 13, 6, 5, 4]
>         self.log("valid_loss", metrics[self.current_epoch])
> 
>     def configure_optimizers(self):
>         return torch.optim.SGD(self.layer.parameters(), lr=0.1)
> 
> 
> train_data = DataLoader(RandomDataset(32, 64), batch_size=2)
> val_data = DataLoader(RandomDataset(32, 64), batch_size=2)
> 
> model = BoringModel()
> trainer = Trainer(
>     callbacks=ModelCheckpoint(save_top_k=3, dirpath="checkpoints", monitor="valid_loss", save_last=True),
>     enable_progress_bar=False,
>     enable_model_summary=False,
>     max_epochs=10,
> )
> trainer.fit(model, train_dataloaders=train_data, val_dataloaders=val_data)
> 
> print(os.listdir("checkpoints"))
> # print output:
> # ['epoch=9-step=320.ckpt', 'last.ckpt', 'epoch=8-step=288.ckpt', 'epoch=7-step=256.ckpt']
> print(os.readlink("checkpoints/last.ckpt"))
> # print output:
> # ..../checkpoints/epoch=9-step=320.ckpt
> ```
> 
> I used Lightning 2.1.3 here. Please confirm that you are also using this version. The output is correct, the last.ckpt points to 9 which was the last one saved.
> 
> Please modify the above example to show the unexpected behavior. Thank you.

@awaelchli Ok, thing is broken in the process. We have to add a callback to see what is happenning.

Add the callback part to the file:

```python
class TestCheckpointCallback(Callback):
    def print_checkpoints(self, epoch):
        if os.path.exists("checkpoints"):
            print(f"before epoch {epoch}")
            print(os.listdir("checkpoints"))
            print(os.readlink("checkpoints/last.ckpt"))

    def on_train_epoch_start(self, trainer, *args, **kwargs) -> None:
        self.print_checkpoints(trainer.current_epoch)

    def on_train_end(self, trainer, *args, **kwargs) -> None:
        self.print_checkpoints(trainer.current_epoch)


trainer = Trainer(
    callbacks=[
        ModelCheckpoint(
            save_top_k=3, dirpath="checkpoints", monitor="valid_loss", save_last=True
        ),
        TestCheckpointCallback(),
    ],
    enable_progress_bar=False,
    enable_model_summary=False,
    max_epochs=10,
)
trainer.fit(model, train_dataloaders=train_data, val_dataloaders=val_data)
```

and the output should be:
```text
before epoch 1
['epoch=0-step=32.ckpt', 'last.ckpt']
/data3/zhengwenhao/Project/natural_language_processing/medical_large_visual_language_model/checkpoints/epoch=0-step=32.ckpt
before epoch 2
['epoch=0-step=32.ckpt', 'last.ckpt', 'epoch=1-step=64.ckpt']
/data3/zhengwenhao/Project/natural_language_processing/medical_large_visual_language_model/checkpoints/epoch=1-step=64.ckpt
before epoch 3
['epoch=0-step=32.ckpt', 'last.ckpt', 'epoch=1-step=64.ckpt', 'epoch=2-step=96.ckpt']
/data3/zhengwenhao/Project/natural_language_processing/medical_large_visual_language_model/checkpoints/epoch=2-step=96.ckpt
before epoch 4
['last.ckpt', 'epoch=3-step=128.ckpt', 'epoch=1-step=64.ckpt', 'epoch=2-step=96.ckpt']
/data3/zhengwenhao/Project/natural_language_processing/medical_large_visual_language_model/checkpoints/epoch=3-step=128.ckpt # it works well until now.
before epoch 5
['last.ckpt', 'epoch=3-step=128.ckpt', 'epoch=1-step=64.ckpt', 'epoch=2-step=96.ckpt']
/data3/zhengwenhao/Project/natural_language_processing/medical_large_visual_language_model/checkpoints/epoch=3-step=128.ckpt # it was broken now.
before epoch 6
['last.ckpt', 'epoch=3-step=128.ckpt', 'epoch=1-step=64.ckpt', 'epoch=2-step=96.ckpt']
/data3/zhengwenhao/Project/natural_language_processing/medical_large_visual_language_model/checkpoints/epoch=3-step=128.ckpt
before epoch 7
['last.ckpt', 'epoch=3-step=128.ckpt', 'epoch=1-step=64.ckpt', 'epoch=2-step=96.ckpt']
/data3/zhengwenhao/Project/natural_language_processing/medical_large_visual_language_model/checkpoints/epoch=3-step=128.ckpt
before epoch 8
['epoch=7-step=256.ckpt', 'last.ckpt', 'epoch=3-step=128.ckpt', 'epoch=2-step=96.ckpt']
/data3/zhengwenhao/Project/natural_language_processing/medical_large_visual_language_model/checkpoints/epoch=7-step=256.ckpt # the new ckpt saved as topk ckpt fixs the checkpoint callback
before epoch 9
['epoch=8-step=288.ckpt', 'epoch=7-step=256.ckpt', 'last.ckpt', 'epoch=3-step=128.ckpt']
/data3/zhengwenhao/Project/natural_language_processing/medical_large_visual_language_model/checkpoints/epoch=8-step=288.ckpt
`Trainer.fit` stopped: `max_epochs=10` reached.
before epoch 10
['epoch=8-step=288.ckpt', 'epoch=9-step=320.ckpt', 'epoch=7-step=256.ckpt', 'last.ckpt']
/data3/zhengwenhao/Project/natural_language_processing/medical_large_visual_language_model/checkpoints/epoch=9-step=320.ckpt
```

**Comment by awaelchli** [comment]
@shenmishajing I see what you were talking about now. The current way is the way the ModelCheckpoint save last has always been working. The docs for save last say:

> save_last: When ``True``, saves a `last.ckpt` copy whenever a checkpoint file gets saved.

save_last does not mean "save the latest checkpoint", it means to save a copy/link to whatever was last saved. In the case of top-k, it means it will always point to the last saved top-k checkpoint among the ones that are there. So in the case above where we have 

```
['last.ckpt', 'epoch=3-step=128.ckpt', 'epoch=1-step=64.ckpt', 'epoch=2-step=96.ckpt']
```

then last.ckpt would point to `epoch=3-step=128.ckpt` even if we are in epoch 5. Because this checkpoint remains the last one saved by the top-k mechanism and `epoch=5-step=...ckpt` is not in top-k according to the metric, so it never gets saved. 

@carmocca Can you confirm my explanation is correct?

**Comment by shenmishajing** [comment]
@awaelchli Ok, I see. Then, it's not a bug now. However, I think we definitly need the _latest_ checkpoint instead of the _latest saved_ checkpoint. Say, we want the checkpoint from epoch 5 if we set the `max_epochs=5` and `save_last=True` instead of a link to the checkpoint from epoch 3. Will you agree with that? And should we change the behaviour of `save_last`?

**Comment by awaelchli** [comment]
To change the behavior of `save_last=True` is probably unrealistic since it has been around for so long, it would be a considerable breaking change. If this was changed, it would have to be implemented under a different argument name not to break existing code. If you want, you can take a look at the discussion here: https://github.com/Lightning-AI/pytorch-lightning/issues/4335#issue-728855136

To save the "latest", there is a simple way to achieve this by adding an additional ModelCheckpoint callback (you can have multiple) that does this:

```py
latest_checkpoint = ModelCheckpoint(
    filename="latest.ckpt",
    save_top_k=1,
    mode="max",
    monitor="current_epoch"
)
```
(The idea here is that since the epoch metric is monotonically increasing, the latest one will always be the "best" and therefore be saved as topk with the filename "latest")

**Comment by shenmishajing** [comment]
> To change the behavior of `save_last=True` is probably unrealistic since it has been around for so long, it would be a considerable breaking change. If this was changed, it would have to be implemented under a different argument name not to break existing code. If you want, you can take a look at the discussion here: [#4335 (comment)](https://github.com/Lightning-AI/pytorch-lightning/issues/4335#issue-728855136)

Got it. Thanks for your explaination, and I will close this issue.
