### ISSUE TITLE
`fabric.setup_module` fails on MPS

### ISSUE THREAD

**Issue by DWarez** [Lightning-AI/pytorch-lightning#19359]
### Bug description

I am following [this Lightning blogpost](https://lightning.ai/blog/8-bit-quantization-with-lightning-fabric/) to post-training quantize an HuggingFace's model using Lightning Fabric, however the `setup_module` command fails because of this failed assertion: `AssertionError: Torch not compiled with CUDA enabled`. 
I don't have a NVidia GPU on my machine, however the MPS backend, which I am using, should be supported. In fact, I specify in the `Fabric` object that the accelerator to use is MPS. 

Is there a way to make this work without CUDA?

### What version are you seeing the problem on?

v2.1

### How to reproduce the bug

```python
from lightning.fabric import Fabric
from lightning.fabric.plugins import BitsandbytesPrecision

model = YourModel()
plugin = BitsandbytesPrecision(mode="int8")
fabric = Fabric(plugins=plugin, accelerator="mps")
model = fabric.setup_module(model)
```

### Error messages and logs

```
AssertionError: Torch not compiled with CUDA enabled
```

### Environment

<details>
  <summary>Current environment</summary>

```
#- Lightning Component: Fabric, BitsandbytesPrecision
#- PyTorch Lightning Version: v2.1.3
#- PyTorch Version: v2.1.2
#- Python version: v3.11.7
#- OS: MacOS 14.1
#- GPU models and configuration: MPS
#- How you installed Lightning: conda
#- Running environment of LightningApp: local
```

</details>

cc @carmocca @justusschock @awaelchli

**Comment by awaelchli** [comment]
@DWarez The bitsandbytes only works with CUDA (this is a limitation of the bitsandbytes package itself not Lightning). The error message can be made better.

**Comment by DWarez** [comment]
> @DWarez The bitsandbytes only works with CUDA (this is a limitation of the bitsandbytes package itself, not Lightning). The error message can be made better.

Thanks a lot for the reply, I didn't find this information in the documentation. I agree that the message could be more explanatory (perhaps something like "Bitsandbytes doesn't support MPS accelerator").
