### ISSUE TITLE
DataLoader throughput does not scale for number of workers > 4-8

### ISSUE THREAD

**Issue by romanonly** [Lightning-AI/pytorch-lightning#19391]
### Bug description

Bug description
Setting workers = 8, 16, and greater does not make DataLoader any faster.

1. I run 64-core node
2. I fetch data from local ssd which has a ms latency.
3. My image size =5MB and batch size=1
4. I use no GPU and benchmark Pytorch Lightning data loading throughput only
5. Download throughput flattens at approx. 180 it/sec, approx. 6 ms per iteration at number of workers > 8-16
6.  I also tested io fetch only and have removed processing (image transformation and collate).
Download throughputs flattens at 700 t/sec approx. 1.5ms per iteration for any number of workers > 8-16  

How to reproduce the bug

### What version are you seeing the problem on?

v2.0

### How to reproduce the bug

```python
I created my benchmarking code per example in:
https://github.com/Lightning-AI/pytorch-lightning/issues/17410

I attach screenshots of the following experiments:
1. Three Throughputs for no-fetch-no-process, fetch-from-ssd-only, fetch-and-processing
It shows no effect of running number of workers > 8-16
2. CPU cores load for number of workers=0
this shows CPU load is distributed over 20+ cores. However, this "0"-mode
does not scale for largher batches neither higher number of processing transforms
3. CPU cores load for number of workers=1,2,4
these screenshots show high nearly 100% CPU utilization for 1 and 2 workers becomes low in number of workers=4
```

### Error messages and logs

```
# Error messages and logs here please
```
Figure Notice multi-core load with number of workers = 0 mode {64-core AWS g5): good scale for io fetching (max out my network card throughput), but no scale for processing (i.e.transformations)

Figure Notice the high utilization for number of workers = 1 and 2 vs low CPU utilization for 4 and higher number of workers 

![Screenshot 2024-02-01 at 11 38 30 AM](https://github.com/Lightning-AI/pytorch-lightning/assets/17115347/880cdc80-2437-4546-b6ed-b588d5a2beff)

### Environment

<details>
  <summary>Current environment</summary>

```
#- Lightning Component (e.g. Trainer, LightningModule, LightningApp, LightningWork, LightningFlow):
#- PyTorch Lightning Version (e.g., 1.5.0):
#- Lightning App Version (e.g., 0.5.2):
#- PyTorch Version (e.g., 2.0):
#- Python version (e.g., 3.9):
#- OS (e.g., Linux):
#- CUDA/cuDNN version:
#- GPU models and configuration:
#- How you installed Lightning(`conda`, `pip`, source):
#- Running environment of LightningApp (e.g. local, cloud):
```

</details>

cc @borda

**Comment by romanonly** [comment]
Figure Notice Pytorch Lightning throughputs  [1] “0” mode vs 1 and  [2] 4-8 and higher number of workers
![Screenshot 2024-02-01 at 11 40 18 AM](https://github.com/Lightning-AI/pytorch-lightning/assets/17115347/43c6ed30-b135-4ada-aa50-3c2607086f6d)

**Comment by romanonly** [comment]
Hi Ryan @ryan597 
your example in https://github.com/Lightning-AI/pytorch-lightning/issues/17410 shows these (no scale beyond 8-16 workers) effects. for example, set number of workers  to 0, 1, 4,  8, 16, 32, 48

**Comment by awaelchli** [comment]
Hey @romanonly a few notes:

1. Can you update to the latest version of Lightning if you repeat the benchmark again?
2. Increasing the number of workers does not necessarily mean that your throughput will increase. I am not aware of any such guarantees.
4. Since you are interested in measuring purely the data fetch iteration speed, I suggest you write a simple for loop with raw pytorch over the dataloader. You should see a very similar it/s without Lightning involved. I'd like you to do this because it is not clear to me what evidence is there that Lightning is doing anything wrong. I need to see that there is a significant gap between pure PyTorch and Lightning before I start a thorough investigation. 
5. You might want to try different settings for `DataLoader(..., multiprocessing_context="spawn")` vs. `DataLoader(..., multiprocessing_context="fork")`. Similar issue here: https://github.com/Lightning-AI/pytorch-lightning/issues/18149

If you could investigate these, that would be very helpful. Thank you!

**Comment by romanonly** [comment]
thank you for prompt response, @awaelchli . I will work on 1-5 and well let you know once done.

**Comment by romanonly** [comment]
Hi @awaelchli 

Please see below my newly added benchmarks:

1. torch and lightning versions: 
2.2.0 and 2.1.3 respectivelye

2. added Trainer(barebones=True)

4. Experimentation matrix: 

Tested Dataset data loading without lightning and with lightning training
multiprocessing_context: fork and spawn 
with and without processing

Observations: 
1. Very small data load speedup (i.e. latency decrease) after 8 workers. 
2. No speedup beyond 16 workers. 
3. In "fork", Dataset dataload alone (no PL training) in the 1-worker mode is slower compared to "0" (main) worker mode. 
 4. "spawn" with training and with processing training takes the same time, regardless on the number of workers 
 
 
Please see the actual code and  num-workes-latencies(ms) pairs:

import random
import time

import pytorch_lightning as pl
import torch
from tqdm import tqdm  # type: ignore[import]
from torch.utils.data import DataLoader, Dataset
from pytorch_lightning.callbacks import TQDMProgressBar, EarlyStopping

MAX_ITER = 1000

class Model(pl.LightningModule):
    def __init__(self):
        super(Model, self).__init__()
        self.conv = torch.nn.Conv2d(3, 3, 3, padding='same')

    def forward(self, x):
        return self.conv(x)

    def training_step(self, train_batch, batch_idx):
        mse_l = torch.nn.MSELoss()
        x, y = train_batch
        logits = self.forward(x)
        loss = mse_l(logits, y)
        self.log('train_loss', loss)
        return loss

    def validation_step(self, val_batch, batch_idx):
        mse_l = torch.nn.MSELoss()
        x, y = val_batch
        logits = self.forward(x)
        loss = mse_l(logits, y)
        self.log('val_loss', loss)
        return loss

    def configure_optimizers(self):
        optimizer = torch.optim.Adam(self.parameters(), lr=1e-3)
        return optimizer


class Data(Dataset):
    def __init__(self, length, do_processing):
        super().__init__()
        self.length = length
        self.do_processing = do_processing
    
    def __len__(self):
        return self.length

    def __getitem__(self, index):
        if self.do_processing:
            time.sleep(0.01)
        return [torch.rand(3, 256, 256), torch.rand(3, 256, 256)]

def init_test(num_workers, do_processing, multiprocessing_context="spawn"):
    print(f"\n\nnum_workers= {num_workers}\tstart processing")
    train_data = Data(MAX_ITER, do_processing)
    validation_data = Data(int(MAX_ITER/10), do_processing)
    if num_workers > 0:
        train_loader = DataLoader(train_data, batch_size=32, num_workers=num_workers, multiprocessing_context=multiprocessing_context)
        validation_loader = DataLoader(validation_data, batch_size=32, num_workers=num_workers, multiprocessing_context=multiprocessing_context)
    else:
        # multiprocessing_context can only be used with multi-process loading (num_workers > 0)
        train_loader = DataLoader(train_data, batch_size=32, num_workers=num_workers)
        validation_loader = DataLoader(validation_data, batch_size=32, num_workers=num_workers)
    return train_loader, validation_loader

def test(num_workers, do_processing, multiprocessing_context="spawn", is_lightning=False):
    if is_lightning:
        return test_lightning(num_workers, do_processing, multiprocessing_context)
    return test_no_lightning(num_workers, do_processing, multiprocessing_context)

def test_no_lightning(num_workers, do_processing, multiprocessing_context):
    train_loader, _ = init_test(num_workers, do_processing, multiprocessing_context)

    start = time.time()
    time_seq = []
    current = time.time()

    for (idx, batch) in enumerate(tqdm(train_loader)):
        time_seq.append(time.time() - current)
        current = time.time()
    print(f"dataload took = {sum(time_seq)}s\n\n\n")
    return sum(time_seq)

def test_lightning(num_workers, do_processing, multiprocessing_context="spawn"):
    """
    multiprocessing_context="spawn"
    multiprocessing_context="fork"
    """

    train_loader, validation_loader = init_test(num_workers, do_processing, multiprocessing_context)

    trainer = pl.Trainer(
        barebones=True, 
        max_epochs=1,
        devices=1,
        # callbacks=[EarlyStopping(monitor="val_loss", mode="min", patience=3),
        #            TQDMProgressBar(refresh_rate=1)],
        #log_every_n_steps=10,
        accelerator='cpu',
        strategy='ddp',    
        )

    model = Model()

    start_time = time.time()
    trainer.fit(model=model, train_dataloaders=train_loader, val_dataloaders=validation_loader)
    end_time = time.time()
    print(f"\n\nnum_workers= {num_workers}\tdo processing= {do_processing}")
    print(f"training took = {end_time -start_time}s\n\n\n")
    return end_time - start_time

if __name__ == "__main__":
    """ 
    https://github.com/Lightning-AI/pytorch-lightning/issues/17410 

    1. reproduce "1" vs. "0" slowdown on no-processing
    2. show no scale in > 16 workers in multiprocessing
    3. show low CPU utilization in > 16 cores
    4. Install:
    https://docs.conda.io/projects/miniconda/en/latest/
    exit 
    login
    conda create -n py311pl21 python=3.11
    conda activate py311pl21
    conda install lightning -c conda-forge
    conda install pytorch -c pytorch
    or python -m pip install lightning

    5 dimentional experiments
    
    disable all features in Lightning that might add overhead if you aren't doing any realistic training. 
    These are logging, checkpointing etc: Trainer(barebones=True).

    1. with vs without transformation
    2. with vs without pl
    3. try different settings for DataLoader(..., multiprocessing_context="spawn") vs. DataLoader(..., multiprocessing_context="fork")    
    """

    print(torch.__version__)
    print(pl.__version__)
    num_workers = [0, 1, 2, 4, 8, 16, 32, 48]
    result_list = []
    for multiprocessing_context in ["fork", "spawn"]:
        for is_lightning in [False, True]:
            for do_processing in [False, True]:
                latency_list = []
                for nw in num_workers:
                # for nw in [0, 1, 7]:
                    latency = test(nw, do_processing, is_lightning=is_lightning)
                    latency_list.append(latency)
                    # print(f"{multiprocessing_context} is_lightning={is_lightning} is_processing={do_processing} nw={nw:3d} latency={(latency):6.3f}")
                    s = f"{multiprocessing_context} is_lightning={is_lightning} is_processing={do_processing} (num_workers,latency(ms))={([(num_workers[indx], int(1000*x+.5)) for indx, x in enumerate(latency_list)])}\n"
                    print(f"\n======\n nw={nw:3d} {s}\n=======")
                result_list.append(s)
                for s in result_list: print(s)
    print("\n===\n results")            
    for s in result_list: print(s)

**Comment by romanonly** [comment]
import random
    import time
    
    import pytorch_lightning as pl
    import torch
    from tqdm import tqdm  # type: ignore[import]
    from torch.utils.data import DataLoader, Dataset
    from pytorch_lightning.callbacks import TQDMProgressBar, EarlyStopping
    
    MAX_ITER = 1000
    
    class Model(pl.LightningModule):
        def __init__(self):
            super(Model, self).__init__()
            self.conv = torch.nn.Conv2d(3, 3, 3, padding='same')
    
        def forward(self, x):
            return self.conv(x)
    
        def training_step(self, train_batch, batch_idx):
            mse_l = torch.nn.MSELoss()
            x, y = train_batch
            logits = self.forward(x)
            loss = mse_l(logits, y)
            self.log('train_loss', loss)
            return loss
    
        def validation_step(self, val_batch, batch_idx):
            mse_l = torch.nn.MSELoss()
            x, y = val_batch
            logits = self.forward(x)
            loss = mse_l(logits, y)
            self.log('val_loss', loss)
            return loss
    
        def configure_optimizers(self):
            optimizer = torch.optim.Adam(self.parameters(), lr=1e-3)
            return optimizer
    
    
    class Data(Dataset):
        def __init__(self, length, do_processing):
            super().__init__()
            self.length = length
            self.do_processing = do_processing
        
        def __len__(self):
            return self.length
    
        def __getitem__(self, index):
            if self.do_processing:
                time.sleep(0.01)
            return [torch.rand(3, 256, 256), torch.rand(3, 256, 256)]
    
    def init_test(num_workers, do_processing, multiprocessing_context="spawn"):
        print(f"\n\nnum_workers= {num_workers}\tstart processing")
        train_data = Data(MAX_ITER, do_processing)
        validation_data = Data(int(MAX_ITER/10), do_processing)
        if num_workers > 0:
            train_loader = DataLoader(train_data, batch_size=32, num_workers=num_workers, multiprocessing_context=multiprocessing_context)
            validation_loader = DataLoader(validation_data, batch_size=32, num_workers=num_workers, multiprocessing_context=multiprocessing_context)
        else:
            # multiprocessing_context can only be used with multi-process loading (num_workers > 0)
            train_loader = DataLoader(train_data, batch_size=32, num_workers=num_workers)
            validation_loader = DataLoader(validation_data, batch_size=32, num_workers=num_workers)
        return train_loader, validation_loader
    
    def test(num_workers, do_processing, multiprocessing_context="spawn", is_lightning=False):
        if is_lightning:
            return test_lightning(num_workers, do_processing, multiprocessing_context)
        return test_no_lightning(num_workers, do_processing, multiprocessing_context)
    
    def test_no_lightning(num_workers, do_processing, multiprocessing_context):
        train_loader, _ = init_test(num_workers, do_processing, multiprocessing_context)
    
        start = time.time()
        time_seq = []
        current = time.time()
    
        for (idx, batch) in enumerate(tqdm(train_loader)):
            time_seq.append(time.time() - current)
            current = time.time()
        print(f"dataload took = {sum(time_seq)}s\n\n\n")
        return sum(time_seq)
    
    def test_lightning(num_workers, do_processing, multiprocessing_context="spawn"):
        """
        multiprocessing_context="spawn"
        multiprocessing_context="fork"
        """
    
        train_loader, validation_loader = init_test(num_workers, do_processing, multiprocessing_context)
    
        trainer = pl.Trainer(
            barebones=True, 
            max_epochs=1,
            devices=1,
            # callbacks=[EarlyStopping(monitor="val_loss", mode="min", patience=3),
            #            TQDMProgressBar(refresh_rate=1)],
            #log_every_n_steps=10,
            accelerator='cpu',
            strategy='ddp',    
            )
    
        model = Model()
    
        start_time = time.time()
        trainer.fit(model=model, train_dataloaders=train_loader, val_dataloaders=validation_loader)
        end_time = time.time()
        print(f"\n\nnum_workers= {num_workers}\tdo processing= {do_processing}")
        print(f"training took = {end_time -start_time}s\n\n\n")
        return end_time - start_time
    
    if __name__ == "__main__":
        """ 
        https://github.com/Lightning-AI/pytorch-lightning/issues/17410 
    
        1. reproduce "1" vs. "0" slowdown on no-processing
        2. show no scale in > 16 workers in multiprocessing
        3. show low CPU utilization in > 16 cores
        4. Install:
        https://docs.conda.io/projects/miniconda/en/latest/
        exit 
        login
        conda create -n py311pl21 python=3.11
        conda activate py311pl21
        conda install lightning -c conda-forge
        conda install pytorch -c pytorch
        or python -m pip install lightning
    
        5 dimentional experiments
        
        disable all features in Lightning that might add overhead if you aren't doing any realistic training. 
        These are logging, checkpointing etc: Trainer(barebones=True).
    
        1. with vs without transformation
        2. with vs without pl
        3. try different settings for DataLoader(..., multiprocessing_context="spawn") vs. DataLoader(..., multiprocessing_context="fork")    
        """
    
        print(torch.__version__)
        print(pl.__version__)
        num_workers = [0, 1, 2, 4, 8, 16, 32, 48]
        result_list = []
        for multiprocessing_context in ["fork", "spawn"]:
            for is_lightning in [False, True]:
                for do_processing in [False, True]:
                    latency_list = []
                    for nw in num_workers:
                    # for nw in [0, 1, 7]:
                        latency = test(nw, do_processing, is_lightning=is_lightning)
                        latency_list.append(latency)
                        # print(f"{multiprocessing_context} is_lightning={is_lightning} is_processing={do_processing} nw={nw:3d} latency={(latency):6.3f}")
                        s = f"{multiprocessing_context} is_lightning={is_lightning} is_processing={do_processing} (num_workers,latency(ms))={([(num_workers[indx], int(1000*x+.5)) for indx, x in enumerate(latency_list)])}\n"
                        print(f"\n======\n nw={nw:3d} {s}\n=======")
                    result_list.append(s)
                    for s in result_list: print(s)
        print("\n===\n results")            
        for s in result_list: print(s)

**Comment by romanonly** [comment]
results
fork is_lightning=False is_processing=False (num_workers,latency(ms))=[(0, 3222), (1, 3770), (2, 2607), (4, 2016), (8, 1844), (16, 1880), (32, 2257), (48, 2646)]

fork is_lightning=False is_processing=True (num_workers,latency(ms))=[(0, 13302), (1, 13745), (2, 7663), (4, 4518), (8, 3008), (16, 2315), (32, 2561), (48, 2824)]

fork is_lightning=True is_processing=False (num_workers,latency(ms))=[(0, 8219), (1, 7584), (2, 7429), (4, 7580), (8, 6665), (16, 6101), (32, 7808), (48, 7691)]

fork is_lightning=True is_processing=True (num_workers,latency(ms))=[(0, 25139), (1, 17246), (2, 10798), (4, 7504), (8, 7703), (16, 7055), (32, 7214), (48, 8629)]

spawn is_lightning=False is_processing=False (num_workers,latency(ms))=[(0, 5528), (1, 3753), (2, 2652), (4, 2042), (8, 1847), (16, 1863), (32, 2339), (48, 2731)]

spawn is_lightning=False is_processing=True (num_workers,latency(ms))=[(0, 19303), (1, 13814), (2, 7639), (4, 4649), (8, 3085), (16, 2326), (32, 2792), (48, 3119)]

spawn is_lightning=True is_processing=False (num_workers,latency(ms))=[(0, 6544), (1, 7339), (2, 7514), (4, 7302), (8, 6523), (16, 5843), (32, 6938), (48, 8017)]

spawn is_lightning=True is_processing=True (num_workers,latency(ms))=[(0, 24396), (1, 17346), (2, 10721), (4, 7935), (8, 6971), (16, 6068), (32, 8245), (48, 8962)]
![Screenshot 2024-02-05 at 6 43 03 PM](https://github.com/Lightning-AI/pytorch-lightning/assets/17115347/5f2b67ff-43ef-4abe-8fbf-f13404336b23)

**Comment by romanonly** [comment]
The new tests confirm the problems observred in 
https://github.com/Lightning-AI/pytorch-lightning/issues/19391#issuecomment-1922098072

The main problem is not having any speedup in the beyond 16 workers range.

**Comment by awaelchli** [comment]
Ok thank you for the investigation. The comparison between lightning and no-lightning is not fair though. The following concerns me a bit:

1. The no-lightning loop just fetches data and doesn't do any other work, but the lightning benchmark does actual optimization since you've implemented `training_step()` do to meaingful work.
2. In the trainer, you configured DDP. This will be an unnecessary overhead on a single device. 
3. The lightning-benchmark measures the time over the entire trainer.fit, this also includes the setup time and other checks that are not present in the no-lightning version. Measuring the time via callbacks `on_train_start` and `on_train_end` would be slightly better.

Furthermore, PyTorch emits this warning (you can see it at the very beginning):

> /Users/adrian/miniconda3/envs/lightning/lib/python3.11/site-packages/torch/utils/data/dataloader.py:558: This DataLoader will create 32 worker processes in total. Our suggested max number of worker in current system is 10 (`cpuset` is not taken into account), which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.

This is what I was trying to say. Why more workers should be faster is not clear to me.

I still took your code and ran it. Here are the modifications I made to make the comparison more apples to apples:
1. Removed `strategy="ddp"`
2. Removed the body of `training_step` (just passing it to not compute the loss)
3. I added callback that records start time in `on_train_epoch` start and end time in `on_epoch_end`

Here is the output of the benchmark:

```
fork is_lightning=False is_processing=False (num_workers,latency(ms))=[(0, 27665), (1, 5985), (2, 4713), (4, 4237), (8, 4203), (16, 4280), (32, 4927), (48, 5619)]
fork is_lightning=True is_processing=False (num_workers,latency(ms))=[(0, 28890), (1, 5944), (2, 4701), (4, 4137), (8, 4113), (16, 4394), (32, 4905), (48, 5705)]
fork is_lightning=False is_processing=True (num_workers,latency(ms))=[(0, 37800), (1, 18289), (2, 11251), (4, 7483), (8, 5626), (16, 4971), (32, 5277), (48, 6082)]
fork is_lightning=True is_processing=True (num_workers,latency(ms))=[(0, 38423), (1, 18833), (2, 11374), (4, 7555), (8, 5681), (16, 4959), (32, 5300), (48, 5923)]


spawn is_lightning=False is_processing=False (num_workers,latency(ms))=[(0, 27828), (1, 5966), (2, 4731), (4, 4267), (8, 4162), (16, 4260), (32, 4886), (48, 5626)]
spawn is_lightning=True is_processing=False (num_workers,latency(ms))=[(0, 29112), (1, 6019), (2, 4695), (4, 4228), (8, 4102), (16, 4352), (32, 4854), (48, 5663)]
spawn is_lightning=False is_processing=True (num_workers,latency(ms))=[(0, 37422), (1, 18813), (2, 11310), (4, 7534), (8, 5585), (16, 4858), (32, 5251), (48, 5831)]
spawn is_lightning=True is_processing=True (num_workers,latency(ms))=[(0, 38402), (1, 18286), (2, 11263), (4, 7395), (8, 5586), (16, 4870), (32, 5234), (48, 5994)]

```
I reordered the lines such that `is_lightning=True` and False are next to each other. You can see that up to some minor variance, the two match each other pretty well. 


Attached the modified code and my system information. With this summary, I hope you can reproduce my observation and be confident that Lightning is just doing the same thing as PyTorch (when measured correctly, which is very important).


```py
import random
import time

import pytorch_lightning as pl
import torch
from tqdm import tqdm  # type: ignore[import]
from torch.utils.data import DataLoader, Dataset
from pytorch_lightning.callbacks import TQDMProgressBar, EarlyStopping, Callback

MAX_ITER = 1000


class Model(pl.LightningModule):
    def __init__(self):
        super(Model, self).__init__()
        self.conv = torch.nn.Conv2d(3, 3, 3, padding='same')

    def forward(self, x):
        return self.conv(x)

    def training_step(self, train_batch, batch_idx):
        # mse_l = torch.nn.MSELoss()
        # x, y = train_batch
        # logits = self.forward(x)
        # loss = mse_l(logits, y)
        # self.log('train_loss', loss)
        # return loss
        pass

    def configure_optimizers(self):
        optimizer = torch.optim.Adam(self.parameters(), lr=1e-3)
        return optimizer


class Data(Dataset):
    def __init__(self, length, do_processing):
        super().__init__()
        self.length = length
        self.do_processing = do_processing

    def __len__(self):
        return self.length

    def __getitem__(self, index):
        if self.do_processing:
            time.sleep(0.01)
        return [torch.rand(3, 256, 256), torch.rand(3, 256, 256)]


def init_test(num_workers, do_processing, multiprocessing_context="spawn"):
    print(f"\n\nnum_workers= {num_workers}\tstart processing")
    train_data = Data(MAX_ITER, do_processing)
    validation_data = Data(int(MAX_ITER / 10), do_processing)
    if num_workers > 0:
        train_loader = DataLoader(train_data, batch_size=32, num_workers=num_workers,
                                  multiprocessing_context=multiprocessing_context)
        validation_loader = DataLoader(validation_data, batch_size=32, num_workers=num_workers,
                                       multiprocessing_context=multiprocessing_context)
    else:
        # multiprocessing_context can only be used with multi-process loading (num_workers > 0)
        train_loader = DataLoader(train_data, batch_size=32, num_workers=num_workers)
        validation_loader = DataLoader(validation_data, batch_size=32, num_workers=num_workers)
    return train_loader, validation_loader


def test(num_workers, do_processing, multiprocessing_context="spawn", is_lightning=False):
    if is_lightning:
        return test_lightning(num_workers, do_processing, multiprocessing_context)
    return test_no_lightning(num_workers, do_processing, multiprocessing_context)


def test_no_lightning(num_workers, do_processing, multiprocessing_context):
    train_loader, _ = init_test(num_workers, do_processing, multiprocessing_context)

    start = time.time()
    time_seq = []
    current = time.time()

    for (idx, batch) in enumerate(tqdm(train_loader)):
        time_seq.append(time.time() - current)
        current = time.time()
    print(f"dataload took = {sum(time_seq)}s\n\n\n")
    return sum(time_seq)


def test_lightning(num_workers, do_processing, multiprocessing_context="spawn"):
    """
    multiprocessing_context="spawn"
    multiprocessing_context="fork"
    """

    class MeasureTime(Callback):
        def __init__(self):
            self.start = 0
            self.end = 0
    
        def on_train_epoch_start(self, *_, **__):
            self.start = time.time()

        def on_train_epoch_end(self, *_, **__):
            self.end = time.time()
        

    train_loader, validation_loader = init_test(num_workers, do_processing, multiprocessing_context)

    timer = MeasureTime()

    trainer = pl.Trainer(
        barebones=True,
        max_epochs=1,
        devices=1,
        callbacks=[timer],
        accelerator='cpu',
    )

    model = Model()

    trainer.fit(model=model, train_dataloaders=train_loader, val_dataloaders=validation_loader)
    print(f"\n\nnum_workers= {num_workers}\tdo processing= {do_processing}")
    print(f"training took = {timer.end - timer.start}s\n\n\n")
    return timer.end - timer.start


if __name__ == "__main__":
    """ 
    https://github.com/Lightning-AI/pytorch-lightning/issues/17410 

    1. reproduce "1" vs. "0" slowdown on no-processing
    2. show no scale in > 16 workers in multiprocessing
    3. show low CPU utilization in > 16 cores
    4. Install:
    https://docs.conda.io/projects/miniconda/en/latest/
    exit 
    login
    conda create -n py311pl21 python=3.11
    conda activate py311pl21
    conda install lightning -c conda-forge
    conda install pytorch -c pytorch
    or python -m pip install lightning

    5 dimentional experiments

    disable all features in Lightning that might add overhead if you aren't doing any realistic training. 
    These are logging, checkpointing etc: Trainer(barebones=True).

    1. with vs without transformation
    2. with vs without pl
    3. try different settings for DataLoader(..., multiprocessing_context="spawn") vs. DataLoader(..., multiprocessing_context="fork")    
    """

    print(torch.__version__)
    print(pl.__version__)
    num_workers = [0, 1, 2, 4, 8, 16, 32, 48]
    result_list = []
    for multiprocessing_context in ["spawn", "fork"]:
        for is_lightning in [True]:  # HERE run the script separately once with True, then with False to avoid any weird interactions
            for do_processing in [False, True]:
                latency_list = []
                for nw in num_workers:
                    latency = test(nw, do_processing, is_lightning=is_lightning)
                    latency_list.append(latency)

                    s = f"{multiprocessing_context} is_lightning={is_lightning} is_processing={do_processing} (num_workers,latency(ms))={([(num_workers[indx], int(1000 * x + .5)) for indx, x in enumerate(latency_list)])}\n"
                    print(f"\n======\n nw={nw:3d} {s}\n=======")
                result_list.append(s)
                for s in result_list: print(s)
    print("\n===\n results")
    for s in result_list: print(s)

```

```
Collecting environment information...
PyTorch version: 2.3.0.dev20240201+cu121
Is debug build: False
CUDA used to build PyTorch: 12.1
ROCM used to build PyTorch: N/A

OS: Ubuntu 22.04.3 LTS (x86_64)
GCC version: (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
Clang version: Could not collect
CMake version: version 3.26.0
Libc version: glibc-2.35

Python version: 3.10.9 (main, Jan 11 2023, 15:21:40) [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-5.15.0-75-generic-x86_64-with-glibc2.35
Is CUDA available: True
CUDA runtime version: Could not collect
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: 
GPU 0: NVIDIA A100-SXM4-40GB
GPU 1: NVIDIA A100-SXM4-40GB
GPU 2: NVIDIA A100-SXM4-40GB
GPU 3: NVIDIA A100-SXM4-40GB
GPU 4: NVIDIA A100-SXM4-40GB
GPU 5: NVIDIA A100-SXM4-40GB
GPU 6: NVIDIA A100-SXM4-40GB
GPU 7: NVIDIA A100-SXM4-40GB

Nvidia driver version: 525.125.06
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.9.5
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.9.5
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.9.5
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.9.5
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.9.5
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.9.5
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.9.5
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Address sizes:                   43 bits physical, 48 bits virtual
Byte Order:                      Little Endian
CPU(s):                          256
On-line CPU(s) list:             0-254
Off-line CPU(s) list:            255
Vendor ID:                       AuthenticAMD
Model name:                      AMD EPYC 7742 64-Core Processor
CPU family:                      23
Model:                           49
Thread(s) per core:              2
Core(s) per socket:              64
Socket(s):                       2
Stepping:                        0
Frequency boost:                 enabled
CPU max MHz:                     2250.0000
CPU min MHz:                     0.0000
BogoMIPS:                        4499.83
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nopl nonstop_tsc cpuid extd_apicid aperfmperf rapl pni pclmulqdq monitor ssse3 fma cx16 sse4_1 sse4_2 x2apic movbe popcnt aes xsave avx f16c rdrand lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw ibs skinit wdt tce topoext perfctr_core perfctr_nb bpext perfctr_llc mwaitx cpb cat_l3 cdp_l3 hw_pstate ssbd mba ibrs ibpb stibp vmmcall fsgsbase bmi1 avx2 smep bmi2 cqm rdt_a rdseed adx smap clflushopt clwb sha_ni xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local clzero irperf xsaveerptr rdpru wbnoinvd amd_ppin arat npt lbrv svm_lock nrip_save tsc_scale vmcb_clean flushbyasid decodeassists pausefilter pfthreshold avic v_vmsave_vmload vgif v_spec_ctrl umip rdpid overflow_recov succor smca sme sev sev_es
Virtualization:                  AMD-V
L1d cache:                       4 MiB (128 instances)
L1i cache:                       4 MiB (128 instances)
L2 cache:                        64 MiB (128 instances)
L3 cache:                        512 MiB (32 instances)
NUMA node(s):                    2
NUMA node0 CPU(s):               0-63,128-191
NUMA node1 CPU(s):               64-127,192-254
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Mmio stale data:   Not affected
Vulnerability Retbleed:          Mitigation; untrained return thunk; SMT enabled with STIBP protection
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Retpolines, IBPB conditional, STIBP always-on, RSB filling, PBRSB-eIBRS Not affected
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected

Versions of relevant libraries:
[pip3] mypy==1.4.1
[pip3] mypy-extensions==1.0.0
[pip3] numpy==1.24.2
[pip3] onnx==1.12.0
[pip3] onnxruntime==1.14.1
[pip3] pytorch-lightning==2.0.6
[pip3] pytorch-triton==3.0.0+901819d2b6
[pip3] torch==2.3.0.dev20240201+cu121
[pip3] torch-tb-profiler==0.4.3
[pip3] torchmetrics==1.3.0.post0
[pip3] torchvision==0.17.0
[pip3] triton==2.2.0
[conda] numpy                     1.24.2                   pypi_0    pypi
[conda] pytorch-lightning         2.0.6                    pypi_0    pypi
[conda] pytorch-triton            3.0.0+901819d2b6          pypi_0    pypi
[conda] torch                     2.3.0.dev20240201+cu121          pypi_0    pypi
[conda] torch-tb-profiler         0.4.3                    pypi_0    pypi
[conda] torchmetrics              1.3.0.post0              pypi_0    pypi
[conda] torchvision               0.17.0                   pypi_0    pypi
[conda] triton                    2.2.0                    pypi_0    pypi
```

**Comment by awaelchli** [comment]
I'm confident in my analysis, so I'm closing this now. But please do let me know if you have any further questions or concerns! Thanks
