### ISSUE TITLE
on_validation_epoch_end() missing 1 required positional argument: 'outputs' while it is actually there

### ISSUE THREAD

**Issue by MuFazil** [Lightning-AI/pytorch-lightning#19419]
## I am trying to run 

`trainer.fit(model)`

and getting this error : 
### TypeError: T5FineTuner.on_validation_epoch_end() missing 1 required positional argument: 'outputs'

But I am actually passing the outputs variable in on_validation_epoch_end

`def on_validation_epoch_end(self, outputs):
        avg_loss = torch.stack([x["val_loss"] for x in outputs]).mean()
        tensorboard_logs = {"val_loss": avg_loss}`

### I tried returning the logs&loss also
`def on_validation_epoch_end(self, outputs):
        avg_loss = torch.stack([x["val_loss"] for x in outputs]).mean()
        tensorboard_logs = {"val_loss": avg_loss}
        return {"val_loss": avg_loss, "log": tensorboard_logs}`

both results in the same error.

### What version are you seeing the problem on?

v2.1

### How to reproduce the bug

```python
This is the notebook I am working on:
[https://colab.research.google.com/drive/1kE3HIVejvZdPNUDyw-2J0cwLJy22nX-n?usp=sharing](url)
```

### Error messages and logs

```
# Error messages and logs here please
```

### Environment

<details>
  <summary>Current environment</summary>

```
#- Lightning Component (e.g. Trainer):
#- PyTorch Lightning Version (e.g., 2.1.4):
#- How you installed Lightning( `pip`):
#- Running environment of LightningApp (Colab):
```

</details>

**Comment by awaelchli** [comment]
@MuFazil When you upgrade to 2.0, you need to remove the "outputs" argument from this method. Outputs from validation step are no longer automatically tracked like that. If you want to see an example how to do it in 2.0, take a look at the release notes: https://github.com/Lightning-AI/pytorch-lightning/releases/tag/2.0.0#bc-changes-pytorch

Here is the full migration guide: https://lightning.ai/docs/pytorch/stable/upgrade/migration_guide.html

**Comment by MuFazil** [comment]
Hey thanks for the input. Now I have modified my code according to this.
But now I have a different error :

MisconfigurationException                 Traceback (most recent call last)
[<ipython-input-23-45d4afebefac>](https://localhost:8080/#) in <cell line: 1>()
----> 1 trainer.fit(model)

10 frames
[/usr/local/lib/python3.10/dist-packages/pytorch_lightning/loops/optimization/closure.py](https://localhost:8080/#) in consume_result(self)
     51         """
     52         if self._result is None:
---> 53             raise MisconfigurationException(
     54                 "The closure hasn't been executed."
     55                 " HINT: did you call `optimizer_closure()` in your `optimizer_step` hook? It could also happen because"

MisconfigurationException: The closure hasn't been executed. HINT: did you call `optimizer_closure()` in your `optimizer_step` hook? It could also happen because the `optimizer.step(optimizer_closure)` call did not execute it internally.


This one also I think is due to the upgrade, But I couldnt find it in the release notes. May be a different upgrade.
Can you help me with this?

**Comment by awaelchli** [comment]
Change your optimizer_step signature to:

```py
    def optimizer_step(self,
                       epoch=None,
                       batch_idx=None,
                       optimizer=None,
                       optimizer_closure=None,
        ):
```

**Comment by awaelchli** [comment]
@MuFazil I tested this change out in the Colab you posted and this seems to resolve the error.
