### ISSUE TITLE
_FabricModule breaks the Huggingface `model.generate()` method

### ISSUE THREAD

**Issue by the-jb** [Lightning-AI/pytorch-lightning#19495]
### Bug description

Due to the strict prevention of bypassing model `forward()` call in PR #18819, it breaks the Huggingface generation models, which inherit [GenerationMixin](https://huggingface.co/docs/transformers/en/main_classes/text_generation#transformers.GenerationMixin) class having `generate()` method.

Since `generate()` method is not to call `backward()`, the methd should not be prevented.

### What version are you seeing the problem on?

v2.1, v2.2, master

### How to reproduce the bug

```python
model = AutoModelForCausalLM.from_pretrained("gpt2")
model = Fabric(accelerator="cuda", strategy="ddp").setup_module(model)
model.generate(**some_inputs)
```

### Error messages and logs

```
RuntimeError: You are calling the method `GPT2LMHeadModel.generate()` from outside the model. This will bypass the wrapper from the strategy and result in incorrect behavior in `.backward()`. You should pass your inputs through `forward()`.
```

### Environment

<details>
  <summary>Current environment</summary>

```
#- Lightning Component (e.g. Trainer, LightningModule, LightningApp, LightningWork, LightningFlow):
#- PyTorch Lightning Version (e.g., 1.5.0):
#- Lightning App Version (e.g., 0.5.2):
#- PyTorch Version (e.g., 2.0):
#- Python version (e.g., 3.9):
#- OS (e.g., Linux):
#- CUDA/cuDNN version:
#- GPU models and configuration:
#- How you installed Lightning(`conda`, `pip`, source):
#- Running environment of LightningApp (e.g. local, cloud):
```

</details>

cc @carmocca @justusschock @awaelchli

**Comment by awaelchli** [comment]
I would like to keep the strict error checking because otherwise the user either runs into silent slowdowns or ends up failing in forward because the parameters are not getting all-gathered (in FSDP):

```
[rank1]: Traceback (most recent call last):
[rank1]:   File "/home/adrian/repositories/lightning/repro.py", line 22, in <module>
[rank1]:     out = model.model.generate(input)
[rank1]:   File "/home/adrian/.conda/envs/lightning/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
[rank1]:     return func(*args, **kwargs)
[rank1]:   File "/home/adrian/.conda/envs/lightning/lib/python3.10/site-packages/transformers/generation/utils.py", line 1437, in generate
[rank1]:     return self.greedy_search(
[rank1]:   File "/home/adrian/.conda/envs/lightning/lib/python3.10/site-packages/transformers/generation/utils.py", line 2248, in greedy_search
[rank1]:     outputs = self(
[rank1]:   File "/home/adrian/.conda/envs/lightning/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
[rank1]:     return self._call_impl(*args, **kwargs)
[rank1]:   File "/home/adrian/.conda/envs/lightning/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
[rank1]:     return forward_call(*args, **kwargs)
[rank1]:   File "/home/adrian/.conda/envs/lightning/lib/python3.10/site-packages/transformers/models/gpt2/modeling_gpt2.py", line 1075, in forward
[rank1]:     transformer_outputs = self.transformer(
[rank1]:   File "/home/adrian/.conda/envs/lightning/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
[rank1]:     return self._call_impl(*args, **kwargs)
[rank1]:   File "/home/adrian/.conda/envs/lightning/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
[rank1]:     return forward_call(*args, **kwargs)
[rank1]:   File "/home/adrian/.conda/envs/lightning/lib/python3.10/site-packages/transformers/models/gpt2/modeling_gpt2.py", line 842, in forward
[rank1]:     inputs_embeds = self.wte(input_ids)
[rank1]:   File "/home/adrian/.conda/envs/lightning/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
[rank1]:     return self._call_impl(*args, **kwargs)
[rank1]:   File "/home/adrian/.conda/envs/lightning/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
[rank1]:     return forward_call(*args, **kwargs)
[rank1]:   File "/home/adrian/.conda/envs/lightning/lib/python3.10/site-packages/torch/nn/modules/sparse.py", line 163, in forward
[rank1]:     return F.embedding(
[rank1]:   File "/home/adrian/.conda/envs/lightning/lib/python3.10/site-packages/torch/nn/functional.py", line 2264, in embedding
[rank1]:     return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
[rank1]: RuntimeError: 'weight' must be 2-D
[rank0]: Traceback (most recent call last):
[rank0]:   File "/home/adrian/repositories/lightning/repro.py", line 22, in <module>
[rank0]:     out = model.model.generate(input)
[rank0]:   File "/home/adrian/.conda/envs/lightning/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
[rank0]:     return func(*args, **kwargs)
[rank0]:   File "/home/adrian/.conda/envs/lightning/lib/python3.10/site-packages/transformers/generation/utils.py", line 1437, in generate
[rank0]:     return self.greedy_search(
[rank0]:   File "/home/adrian/.conda/envs/lightning/lib/python3.10/site-packages/transformers/generation/utils.py", line 2248, in greedy_search
[rank0]:     outputs = self(
[rank0]:   File "/home/adrian/.conda/envs/lightning/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
[rank0]:     return self._call_impl(*args, **kwargs)
[rank0]:   File "/home/adrian/.conda/envs/lightning/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
[rank0]:     return forward_call(*args, **kwargs)
[rank0]:   File "/home/adrian/.conda/envs/lightning/lib/python3.10/site-packages/transformers/models/gpt2/modeling_gpt2.py", line 1075, in forward
[rank0]:     transformer_outputs = self.transformer(
[rank0]:   File "/home/adrian/.conda/envs/lightning/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
[rank0]:     return self._call_impl(*args, **kwargs)
[rank0]:   File "/home/adrian/.conda/envs/lightning/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
[rank0]:     return forward_call(*args, **kwargs)
[rank0]:   File "/home/adrian/.conda/envs/lightning/lib/python3.10/site-packages/transformers/models/gpt2/modeling_gpt2.py", line 842, in forward
[rank0]:     inputs_embeds = self.wte(input_ids)
[rank0]:   File "/home/adrian/.conda/envs/lightning/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
[rank0]:     return self._call_impl(*args, **kwargs)
[rank0]:   File "/home/adrian/.conda/envs/lightning/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
[rank0]:     return forward_call(*args, **kwargs)
[rank0]:   File "/home/adrian/.conda/envs/lightning/lib/python3.10/site-packages/torch/nn/modules/sparse.py", line 163, in forward
[rank0]:     return F.embedding(
[rank0]:   File "/home/adrian/.conda/envs/lightning/lib/python3.10/site-packages/torch/nn/functional.py", line 2264, in embedding
[rank0]:     return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
[rank0]: RuntimeError: 'weight' must be 2-D
```
(I generated this error by disabling our error checking and selecting FSDP!!)


If users want to use different methods for forward, they need to wrap their model and redirect the call for correctness:
```py
class Model(torch.nn.Module):
    def __init__(self):
        super().__init__()
        self.model = AutoModelForCausalLM.from_pretrained("gpt2")

    def forward(self, x):
        return self.model.generate(x)
```

This is unavoidable, and a limitation from PyTorch.

**Comment by the-jb** [comment]
I was wondering if it would be possible to have this just as a "warning", at least for non-FSDP strategies.

The `forward()` function is intended to get a direct output for the input, but the `generate()` method includes operations for several prediction strategies, such as beam search, based on the model's `forward()` method.
Therefore, users may want to use `forward()` and `generate()` together in the same model, especially if they inherit a GenerationMixin in their custom model and want to implement `generate()` utilizing their own `forward()` method.

I understand that this requires to consider compatibility for different strategies, which is not an easy task. However, unlike LightningModule, I use Fabric for enough low-level modification for my model. It will be great if there are some ways to call different methods when users understanding the caution.

**Comment by awaelchli** [comment]
I am against making it a warning for two reasons: 1) users don't read warnings or they get swallowed by other outputs and users don't see them 2) it would enable a silent correctness issue, or lead to other PyTorch errors that would surface.

Here you can see what DDP does in forward:
https://github.com/pytorch/pytorch/blob/26fbbc3e844c8267aa8cf78f152c9612da40dc89/torch/nn/parallel/distributed.py#L1584

These pre and post hooks are important for training, and brings up the question why we should even wrap the model in DDP if you are doing inference? There is no communication required when you do generate(), so you could also just drop the `setup()` call in theory. Then it would be valid to call `generate()`. Would that work in your case?

**Comment by carmocca** [comment]
>  There is no communication required when you do generate(), so you could also just drop the setup() call in theory. Then it would be valid to call generate()

This is an interesting question for Fabric. So far we always recommend calling `fabric.setup()` but it is true that during evaluation, the DDP wrapper is counter productive, in fact, we don't use it in the Trainer under the evaluation stages: https://github.com/Lightning-AI/pytorch-lightning/blob/master/src/lightning/pytorch/strategies/ddp.py#L170-L171

On the other hand, dropping `setup` is not a good decision because then you lose all the other things that the `_FabricModule` takes care of. It could also introduce bugs where `fabric.something()` expects to find the model FabricModule-wrapped.

Does this tell us that the DDP wrapper needs to be configurable in Fabric? Or does this mean that we need a multi-process launching mechanism without the DDP strategy?

**Comment by awaelchli** [comment]
@carmocca I've previously proposed to have a way to signal Fabric whether the user is training or running inference (can't find the issue right now) because of this, and also because that's what the trainer does and would be needed if we further unify the Trainer and Fabric strategies. But this idea was rejected. 

For now, the only way is for the user to avoid calling `setup` for inference.

**Comment by the-jb** [comment]
If that is a problem, why not just specify functions that allow forward calls to pass the validation? Perhaps something like `@allow_forward_function`, or `setup_module(module, allow_forward_functions=["generate"])`.

**Comment by the-jb** [comment]
If that is a problem, why not just specify functions to allow forward calls to pass the validation? Perhaps something like `@allow_forward_function`, or `setup_module(module, allow_forward_functions=["generate"])`.
