### ISSUE TITLE
Add Ascend NPU as a backend

### ISSUE THREAD

**Issue by hipudding** [Lightning-AI/pytorch-lightning#19498]
### Description & Motivation

Ascend is a full-stack AI computing infrastructure for industry applications and services based on Huawei Ascend processors and software. For more information about Ascend, see [Ascend Community](https://www.hiascend.com/en/).

[CANN](https://www.hiascend.com/en/software/cann) (Compute Architecture of Neural Networks), developped by Huawei, is a heterogeneous computing architecture for AI.

Pytorch has officially announced [support for Ascend NPU](https://pytorch.org/blog/pytorch-2-1/) (through key PrivateUse1), please see the PrivateUse1 tutorial [here](https://pytorch.org/tutorials/advanced/privateuseone.html).

Provide new backend support for pytorch-lighting, allowing users who use Ascend NPU to also use the convenient development and acceleration capabilities provided by pytorch-lighting.

### Pitch

I'd like to add a new accelerator, and register it into Accelerators, which make it possible that customer can use this new backend by: "accelerator='npu'".

### Additional context

I have wrote a demo, please refer to: https://github.com/Lightning-AI/pytorch-lightning/pull/19308

cc @borda

**Comment by hipudding** [comment]
@lantiga Good day, Could you please give me some suggestions? Thanks.

**Comment by andre0rlandi** [comment]
@hipudding have you managed how to solve this issue?

**Comment by hipudding** [comment]
> @hipudding have you managed how to solve this issue?

Not yet. I have create a Draft PR, which is a demo for this new backend. I need reply from community, This will guide my subsequent development tasks. However, I haven't gotten any response from the community yet, this issue is currently pending.

**Comment by whu-dft** [comment]
@hipudding 

Hello,

I have recently utilized the draft code [here](https://github.com/hipudding/pytorch-lightning/tree/npu_support) for training with PyTorch Lightning on NPU. It has proven to be quite useful, and I would like to extend my gratitude for your contribution. I am hopeful that the pending pull request (PR) can be reviewed and merged into the official repository promptly.

Thank you once again for your valuable work.

Best regards

**Comment by Borda** [comment]
> Thank you once again for your valuable work.

i think i could be made as extension repo

**Comment by hipudding** [comment]
> > Thank you once again for your valuable work.
> 
> i think i could be made as extension repo

Thanks for your reply. Could you please tell me how to do with this extension repo? Is there any guidance on extension development? Or just use monkey patch.

**Comment by XXXHUA** [comment]
> > i think i could be made as extension repo
> 
> @Borda Thanks for your reply. Could you please tell me how to do with this extension repo? Is there any guidance on extension development? Or just use monkey patch.

if I wanna use lightning in NPU Ascend now, could you give me some draft templates or suggestions ? Thanks！

**Comment by hipudding** [comment]
> > > i think i could be made as extension repo
> > 
> > 
> > @Borda Thanks for your reply. Could you please tell me how to do with this extension repo? Is there any guidance on extension development? Or just use monkey patch.
> 
> if I wanna use lightning in NPU Ascend now, could you give me some draft templates or suggestions ? Thanks！

Yes, here's the [demo](https://github.com/Lightning-AI/pytorch-lightning/pull/19308#issuecomment-2041725276).

**Comment by RobertLuo1** [comment]
Hi, @hipudding, Any update now? I have used your draft code for training. I found that although it runs pretty well with minimal changes, the speed is quite slow (910B vs V100). I wonder if the problem stems from torch_npu or the lightning framework.
Thank you in advance.

**Comment by hipudding** [comment]
> Hi, @hipudding, Any update now? I have used your draft code for training. I found that although it runs pretty well with minimal changes, the speed is quite slow (910B vs V100). I wonder if the problem stems from torch_npu or the lightning framework. Thank you in advance.

Thanks for using this PR. Actually, I didn't do any analysis about the performace, If you are not using any strategy, it only a simple wrapper of torch(torch_npu), I think you can use a simple demo that only use torch(torch_npu) to see where is the root cause of this performance issue.

**Comment by RobertLuo1** [comment]
Thanks for your quick reply! I have found something strange when I train the autoencoder, the speed is normal and 2x better than V100.  However, when I train the Transformer-based model, the speed is extremely slow (10x slower).

**Comment by hipudding** [comment]
> Thanks for your quick reply! I have found something strange when I train the autoencoder, the speed is normal and 2x better than V100. However, when I train the Transformer-based model, the speed is extremely slow (10x slower).

Sorry, I'm not an expert in this area and I can't give you any advice.

**Comment by 24hours** [comment]
we are trying to evaluate possibility of running pl on huawei NPU. Thanks for your contribution. 
I agree with @Borda  that making it an extension repo would be better. 

2 example with be  
https://github.com/Lightning-AI/lightning-Graphcore
https://github.com/Lightning-AI/lightning-Habana 

We are currently pending procure the hardware. Looking forward for your opinion.

**Comment by hipudding** [comment]
> we are trying to evaluate possibility of running pl on huawei NPU. Thanks for your contribution. I agree with @Borda that making it an extension repo would be better.
> 
> 2 example with be https://github.com/Lightning-AI/lightning-Graphcore https://github.com/Lightning-AI/lightning-Habana
> 
> We are currently pending procure the hardware. Looking forward for your opinion.

Thanks. We will try to make it as a extension repo.
