### ISSUE TITLE
Setting a compression on `optimize` fails on data deserialization

### ISSUE THREAD

**Issue by mads-oestergaard** [Lightning-AI/pytorch-lightning#19500]
### Bug description

Setting a compression on `optimize` fails when loading data on a StreamingDataset. 

### What version are you seeing the problem on?

v2.2, master

### How to reproduce the bug

```python
import torch
import torchaudio
from io import BytesIO
from lightning.data import optimize, StreamingDataset

def fn(index) -> dict:
    # load dummy audio as bytes
     data = torch.randn((1, 16000))

    # convert tensor to bytes
    with BytesIO() as f:
        torchaudio.save(f, data, 16000, format="wav")
        data = f.getvalue()

    data = {"content": data}
    return data

optimize(
    fn=fn,
    inputs=list(range(100)),
    output_dir="tmp",  # The directory where the optimized data are stored.
    num_workers=4,  # The number of workers. The inputs are distributed among them.
    chunk_bytes="64MB",  # The maximum number of bytes to write into a chunk.
    compression="zstd",
)

dataset = StreamingDataset(input_dir="tmp")
dataset[0] # fails here
```

### Error messages and logs

```
ValueError: tree_unflatten(leaves, treespec): `leaves` has length 0 but the spec refers to a pytree that holds 1 items (TreeSpec(dict, ['content'], [*])).
```

### Environment

<details>
  <summary>Current environment</summary>

```
#- Lightning Component (e.g. Trainer, LightningModule, LightningApp, LightningWork, LightningFlow):
#- PyTorch Lightning Version (e.g., 1.5.0):
#- Lightning App Version (e.g., 0.5.2):
#- PyTorch Version (e.g., 2.0):
#- Python version (e.g., 3.9):
#- OS (e.g., Linux):
#- CUDA/cuDNN version:
#- GPU models and configuration:
#- How you installed Lightning(`conda`, `pip`, source):
#- Running environment of LightningApp (e.g. local, cloud):
```

</details>

cc @tchaton

**Comment by tchaton** [comment]
Hey @mads-oestergaard, thanks for raising the error. I will advice for you to skip the compression argument for the time being.

**Comment by mads-oestergaard** [comment]
Super, thanks for the link! Looking forward to a stable release. You do good work 🚀 

I noticed two bugs with torchaudio:
1. If you add the path to a wav file as a string, it gets registered as a “wav” type and fails when decoding
2. Saving a bytes object with the ‘wave’ lib results in a strange format.

I will update with an example when I get back to my computer (likely Thursday 🤗)

**Comment by tchaton** [comment]
Thanks @mads-oestergaard I believe I resolved all the issues you shared on this PR: https://github.com/Lightning-AI/pytorch-lightning/pull/19503. Would you mind giving it a try by using that branch ?

Best regards,
T.C

**Comment by mads-oestergaard** [comment]
It works on my end. Very nice! 

I've made a version of the LocalDownloader that uses a cache for local files (e.g. useable for mounted shared drives) and would like to make a PR with it - do it do it on lit-data or here?

**Comment by tchaton** [comment]
Hey @mads-oestergaard That's great to hear ! Make a PR to this repo. Once merged, I will port everything to the other one. Sorry for the flux period ;)

**Comment by mads-oestergaard** [comment]
No worries :-) 
I prefer the flux period over adding tons of new dependencies to our codebase, as I would with MosaicML 

BTW lightning-cloud is not a dependency on lightning.
If I just check out master and install pytorch-lightning with `pip install -e .` then this fails: 
```python
from lightning.data import StreamingDataset

dataset = StreamingDataset(input_dir="whatever")
```

Want me to create it as an issue?
