### ISSUE TITLE
Don't save pretrained submodules in checkpoint

### ISSUE THREAD

**Issue by davidpicard** [Lightning-AI/pytorch-lightning#19514]
### Description & Motivation

All sub-modules are saved during checkpointing, but many modern systems rely on huge submodules (LLM, big VAE, etc) that are pretrained and not modified in any way since they are only use as pre/post-processing. They are wasting a ton of space and time during checkpointing (mostly space tbh).

### Pitch

It'd be nice to have a way to indicate that some submodules should not be saved/loaded during checkpointing. I have no idea what would be the best trade-off between ease of implementation and ease of use, but I can imagine something like

```
with pl.disable_checkpointing():
  self.vae = AutoencoderKL.from_pretrained(...)
```

or

```
self.vae = AutoencoderKL.from_pretrained(...)
self.disable_checkpointing(self.vae)
```

Maybe there are more pythonic alternatives.

cc @borda

**Comment by awaelchli** [comment]
Hey @davidpicard 
This is best done by implementing the `state_dict` method. In Lightning 2.2, there is also a new feature that allows you to define `self.strict_loading = False` so that you can load the partial checkpoint again if needed:
https://lightning.ai/docs/pytorch/stable/common/checkpointing_advanced.html#resume-from-a-partial-checkpoint

**Comment by davidpicard** [comment]
Thanks a lot! I could not find this information by searching/googling/chatgpting/etc. It would be great to have it somewhere more accessible than cloud checkpointing which is more niche in my opinion.

**Comment by awaelchli** [comment]
Yeah agree, this is very odd. I'll convert this into a docs issue for myself. 
Thanks

**Comment by sem-k32** [comment]
Can provide a small example with [DINOv2](https://huggingface.co/docs/transformers/en/model_doc/dinov2?usage=Pipeline#dinov2) as a pretrained submodule.

In your LightningModule's ```__init__``` you'll have something like

```python
self.dino = AutoModel.from_pretrained(
    "facebook/dinov2-huge"
)
```

Then you override ```state_dict()``` where you filter the full state dict (I use [toolz.keyfilter](https://toolz.readthedocs.io/en/latest/api.html#toolz.dicttoolz.keyfilter) and [re](https://docs.python.org/3/library/re.html) to do it)

```python
def state_dict(self, destination=None, prefix='', keep_vars=False):
        """ We exclude frozen dino module from the state dict
        """
        full_state_dict = super().state_dict(
            destination=destination, prefix=prefix, keep_vars=keep_vars
        )
        return keyfilter(lambda k: not re.search("dino", k), full_state_dict)
```

When checkpoints are created, DINO params won't be included. When you load checkpoint, don't forget to unset strict mode

```python
classifier = YourLightningModule.load_from_checkpoint(
    "checkpoint.ckpt",
    weights_only=False,
    strict=False
)
```
