### ISSUE TITLE
Model stuck after saving a checkpoing when using the FSDPStrategy

### ISSUE THREAD

**Issue by charlesxu90** [Lightning-AI/pytorch-lightning#19526]
### Bug description

I'm training a GPT model using Fabric. Below are the setups for Fabric

It works well if I'm running without saving a checkpoint. However, if I save a checkpoint using ethier `torch.save` with `fabric.barrier()` or with `fabric.save()` the training will stuck.

I saw `torch.distributed.barrier()` have a [similar issue](https://github.com/pytorch/pytorch/issues/54059). I don't have a similar utilities in my code. Not sure if there is a same usage in `Fabric`. 

### What version are you seeing the problem on?

v2.1

### How to reproduce the bug

```python
strategy = FSDPStrategy(
            auto_wrap_policy={Block},
            activation_checkpointing_policy={Block},
            state_dict_type="full",
            limit_all_gathers=True,
            cpu_offload=False,
        )
self.fabric = L.Fabric(accelerator=device, devices=n_devices, strategy=strategy, precision=precision)
```
Saving model with

```python
state = {"model": model}
full_save_path = os.path.abspath(get_path(base_dir, base_name, '.pt'))
fabric.save(full_save_path, state)
```

### Error messages and logs

```
# Error messages and logs here please
```
No errors, only stuck!

### Environment

<details>
  <summary>Current environment</summary>

```
#- Lightning Component (e.g. Trainer, LightningModule, LightningApp, LightningWork, LightningFlow): lightning, mainly using Fabric
#- PyTorch Lightning Version (e.g., 1.5.0): 2.1.3
#- Lightning App Version (e.g., 0.5.2):
#- PyTorch Version (e.g., 2.0): 2.1.2+cu118
#- Python version (e.g., 3.9): 3.10.13
#- OS (e.g., Linux): Ubuntu
#- CUDA/cuDNN version: 11.8
#- GPU models and configuration: A100 40Gx2
#- How you installed Lightning(`conda`, `pip`, source): pip
#- Running environment of LightningApp (e.g. local, cloud): local
```

</details>

### More info

I think it relates to the communications betweeen the systems.

cc @awaelchli @carmocca

**Comment by awaelchli** [comment]
@charlesxu90 are you able to share the code? or a minimized version that reproduces the problem?

**Comment by charlesxu90** [comment]
Sorry, I cannot share my code. I solved it by not saving checkpoints in the middle.

**Comment by gaozhangyang** [comment]
I meet the same problem. Who can help me?

**Comment by WelkinYang** [comment]
> Sorry, I cannot share my code. I solved it by not saving checkpoints in the middle.

you should not close this issue bc not saving in training stage is a bad idea
