### ISSUE TITLE
The prefetch_batches in _PrefetchDataFetcher always is 1

### ISSUE THREAD

**Issue by niuliling123** [Lightning-AI/pytorch-lightning#19539]
### Bug description

I set prefetch_factors in pytorch dataloader, but the __next__ still costs a lot of time. My _DataFetcher is _PrefetchDataFetcher, the printed prefetch_factors never changed. 

_PrefetchDataFetcher was returned in  return _PrefetchDataFetcher() but the prefetch_factors was unsetted

### What version are you seeing the problem on?

v2.1

### How to reproduce the bug

```python
change the data_factor in dataloader and print prefetch_batches in _PrefetchDataFetcher
```

### Error messages and logs

```
# Error messages and logs here please
```

### Environment

<details>
  <summary>Current environment</summary>

```
#- Lightning Component (e.g. Trainer, LightningModule, LightningApp, LightningWork, LightningFlow):
#- PyTorch Lightning Version (e.g., 1.5.0):
#- Lightning App Version (e.g., 0.5.2):
#- PyTorch Version (e.g., 2.0):
#- Python version (e.g., 3.9):
#- OS (e.g., Linux):
#- CUDA/cuDNN version:
#- GPU models and configuration:
#- How you installed Lightning(`conda`, `pip`, source):
#- Running environment of LightningApp (e.g. local, cloud):
```

</details>

**Comment by awaelchli** [comment]
@niuliling123 `prefetch_batches` in Lightning internals is not the same as the prefetch factor for the DataLoader, they are independent things that work differently. If you set `DataLoader(prefetch_factor=x)`, it will be used. You can check that by printing 

```py
print(self.trainer.train_dataloader.prefetch_factor)
```

in your `training_step` for example.
