### ISSUE TITLE
Importing DeepSpeedStrategy fails

### ISSUE THREAD

**Issue by ZetangForward** [Lightning-AI/pytorch-lightning#19569]
### Bug description

I try to initialize pl.trainer with deepspeed strategy. However, I meet a strange error, which is shown below

### What version are you seeing the problem on?

v2.2

### How to reproduce the bug

```python
strategy = DeepSpeedStrategy(config="/nvme/zecheng/modelzipper/projects/state-space-model/configs/deepspeed/stage2.json")
trainer = pl.Trainer(
    default_root_dir=os.path.join(tb_logger.log_dir , "checkpoints"),
    logger=tb_logger,
    callbacks=[lr_monitor, ckpt_monitor],
    check_val_every_n_epoch=1 if data_module.val_dataloader is not None else 1000000,  # set a large number if no validation set
    # strategy=DDPStrategy(find_unused_parameters=False),
    strategy=strategy,
    precision="bf16-mixed",
    max_steps=config.experiment.num_training_steps,
    devices=config.experiment.device_num,
    gradient_clip_val=1,
    enable_model_summary=True,
    num_sanity_val_steps=20,
    fast_dev_run=5 # for debugging
)

```
```


### Error messages and logs

```
Traceback (most recent call last):
  File "/nvme/zecheng/modelzipper/projects/state-space-model/mamba/train.py", line 397, in main
    trainer = pl.Trainer(
  File "/home/amax/anaconda3/envs/zecheng/lib/python3.10/site-packages/pytorch_lightning/utilities/argparse.py", line 70, in insert_env_defaults
    return fn(self, **kwargs)
  File "/home/amax/anaconda3/envs/zecheng/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 400, in __init__
    self._accelerator_connector = _AcceleratorConnector(
  File "/home/amax/anaconda3/envs/zecheng/lib/python3.10/site-packages/pytorch_lightning/trainer/connectors/accelerator_connector.py", line 134, in __init__
    self._check_config_and_set_final_flags(
  File "/home/amax/anaconda3/envs/zecheng/lib/python3.10/site-packages/pytorch_lightning/trainer/connectors/accelerator_connector.py", line 203, in _check_config_and_set_final_flags
    raise ValueError(
ValueError: You selected an invalid strategy name: `strategy=<lightning.pytorch.strategies.deepspeed.DeepSpeedStrategy object at 0x7fb932781750>`. It must be either a string or an instance of `pytorch_lightning.strategies.Strategy`. Example choices: auto, ddp, ddp_spawn, deepspeed, ... Find a complete list of options in our documentation at https://lightning.ai
```


### Environment

pytorch-lightning version 2.2.0.post0
deepspeed version 0.11.2
pytorch version 2.1.2

### More info

None

**Comment by awaelchli** [comment]
Hey @ZetangForward 

You can't mix the `lightning` imports with `pytorch_lightning`. You need to use the same imports everywhere.

For example, if you use

```py
from pytorch_lightning import Trainer
```

you also need to do

```py
from pytorch_lightning.strategies import DeepSpeedStrategy
```

**Comment by ZetangForward** [comment]
OK, THX for your help. This issue is fixed.
