### ISSUE TITLE
How to set max training steps or epochs?

### ISSUE THREAD

**Issue by pengzhangzhi** [Lightning-AI/pytorch-lightning#19582]
### Bug description

I am trying the set the two parameters to set the training iterations . 
```
 max_steps: 1000000
  max_epochs: 100 
```
But the training iterations is also a fixed number 26706 no matter how I tune the two parameters.
![image](https://github.com/Lightning-AI/pytorch-lightning/assets/59241275/2d05893c-8947-458d-9b52-259237051a84)

### What version are you seeing the problem on?

master

### How to reproduce the bug

```python
Here are my full configurations

trainer:
  devices: 8 # number of GPUs or CPUs
  num_nodes: 1 
  accelerator: gpu #gpu or cpu
  precision: bf16 #16 or 32
  strategy: deepspeed_stage_2
  logger: False # logger is provided by NeMo exp_manager
  enable_checkpointing: False # checkpointing is done by NeMo exp_manager
  max_epochs: 100 # # use max_steps instead with NeMo Megatron model
  log_every_n_steps: 10  # number of interations between logging
  val_check_interval: 1500
  limit_val_batches: 50 # number of batches in validation step, use fraction for fraction of data, 0 to disable
  limit_test_batches: 500 # number of batches in test step, use fraction for fraction of data, 0 to disable
  accumulate_grad_batches: 1
  gradient_clip_val: 1.0
  benchmark: False
  max_steps: 1000000
  num_sanity_val_steps: 2

```

Here are the trainer codes:
```
trainer = pl.Trainer(
        **trainer_cfg,
        callbacks=callbacks,
    )
    
    model = instantiate(model_cfg.model)
    
    data_module = instantiate({"_target_":data_cfg._target_}, data_cfg, trainer,)
    pl_model = LightningModel(model, lm_cfg)

    exp_manager(trainer, cfg.exp_manager)
    trainer.fit(
        pl_model,
        train_dataloaders=data_module.get_data_loader("train"),
        val_dataloaders=data_module.get_data_loader("validation"),
    )


```
```


### Error messages and logs

```
# Error messages and logs here please
```


### Environment

<details>
  <summary>Current environment</summary>

```
#- Lightning Component (e.g. Trainer, LightningModule, LightningApp, LightningWork, LightningFlow):
#- PyTorch Lightning Version (e.g., 1.5.0):
#- Lightning App Version (e.g., 0.5.2):
#- PyTorch Version (e.g., 2.0):
#- Python version (e.g., 3.9):
#- OS (e.g., Linux):
#- CUDA/cuDNN version:
#- GPU models and configuration:
#- How you installed Lightning(`conda`, `pip`, source):
#- Running environment of LightningApp (e.g. local, cloud):
```

</details>


### More info

_No response_

**Comment by awaelchli** [comment]
@pengzhangzhi 

The value in the progress bar 26706 is smaller than `max_steps: 1000000`, so it won't stop after one epoch. Set it to a value smaller than 26706 to see it working, i.e., stopping before the epoch.

For example, set `max_steps=2` and you will see it stops after 2 steps.

**Comment by pengzhangzhi** [comment]
Thanks @awaelchli , but I want to set a large training steps to make the training longer

**Comment by awaelchli** [comment]
But your dataloader only has 26706 batches. To train with this data multiple times, this is called epoch. So if you set
```
max_epochs = 10
```
for example, then that would be 10 * 26706 of batches you train on.

**Comment by pengzhangzhi** [comment]
Thanks for the clarification!! I see the problem :) Just increase the epochs

**Comment by awaelchli** [comment]
Yep. And if you only care about epochs, you can remove `max_steps`, don't need to set it.

**Comment by pengzhangzhi** [comment]
Hey @awaelchli One more question, when I resume from a checkpoint and I go to the  step where the ckpt is saved, does my dataloder is also resumed from that step? Or just restart over?

**Comment by awaelchli** [comment]
Unfortunately no, it will start over. Sometimes this matters, sometimes not. It depends on your task. If you want to be save, make sure to only resume from checkpoints that are saved at the epoch end.

**Comment by pengzhangzhi** [comment]
Would be interesting to add this as a feature? Because for model training as scale, the data is also large it takes a few days to iterate over the whole dataset. And sometimes the training crashes, you want to resume and continue training on new data instead what you have trained on.

**Comment by awaelchli** [comment]
The PyTorch DataLoader doesn't support this, and it is very difficult to implement this in general. For custom dataloaders, we recently added this feature:
https://github.com/Lightning-AI/pytorch-lightning/releases/tag/2.2.0#highlights-dataloader-state
(but it is not yet well documented)

We also have a library called lit-data, where we implement dataloaders that are stateful and can be resumed at any point:
https://github.com/Lightning-AI/litdata

This is a new library in development, so we are already working on this, it's not yet officially released. You can give it a try if you want by following the installation instruction there.
