### ISSUE TITLE
Initializing Trainer with accelerator=HPUAccelerator() and strategy="auto" initializes it with incorrect strategies

### ISSUE THREAD

**Issue by ankitgola005** [Lightning-AI/pytorch-lightning#19614]
### Bug description

Initializing Trainer with accelerator=HPUAccelerator() (from lightning_habana) and strategy = "auto" initializes it with incorrect strategies. 
For single device, it initializes with SingleDeviceStrategy instead of SingleHPUStrategy,
For multiple devices, it inits with ddp instead of ParallelHPUStrategy.

Issue is not seen when setting accelerator="hpu".

### What version are you seeing the problem on?

v2.1, v2.2, master

### How to reproduce the bug

```python
from lightning import Trainer
from lightning.pytorch.demos.boring_classes import BoringModel
from lightning_habana import HPUAccelerator

model = BoringModel()

trainer = Trainer(
    accelerator=HPUAccelerator(),
    devices=1,
    strategy="auto",
    fast_dev_run=True,
)

trainer.fit(model)
```

### Error messages and logs

```
# Error message

Traceback (most recent call last):
  File "/home/agola/qnpu/qnplt/src/lightning-Habana/tests/test_pytorch/test_strategy.py", line 10, in <module>
    trainer = Trainer(
  File "/home/agola/qnpu/qnplt/src/pytorch-lightning/src/lightning/pytorch/utilities/argparse.py", line 70, in insert_env_defaults
    return fn(self, **kwargs)
  File "/home/agola/qnpu/qnplt/src/pytorch-lightning/src/lightning/pytorch/trainer/trainer.py", line 401, in __init__
    self._accelerator_connector = _AcceleratorConnector(
  File "/home/agola/qnpu/qnplt/src/pytorch-lightning/src/lightning/pytorch/trainer/connectors/accelerator_connector.py", line 161, in __init__
    self._lazy_init_strategy()
  File "/home/agola/qnpu/qnplt/src/pytorch-lightning/src/lightning/pytorch/trainer/connectors/accelerator_connector.py", line 587, in _lazy_init_strategy
    raise ValueError(
ValueError: The `HPUAccelerator` can only be used with a `SingleHPUStrategy` or `HPUParallelStrategy`, found SingleDeviceStrategy.
```

### Environment

<details>
  <summary>Current environment</summary>

* CUDA:
        - GPU:               None
        - available:         False
        - version:           None
* Lightning:
        - lightning:         2.3.0.dev0
        - lightning-cloud:   0.5.64
        - lightning-habana:  1.5.0.dev0
        - lightning-utilities: 0.10.1
        - pytorch-lightning: 2.2.1
        - torch:             2.2.0a0+git8964477
        - torch-tb-profiler: 0.4.0
        - torchaudio:        2.2.0+08901ad
        - torchdata:         0.7.1+5e6f7b7
        - torchmetrics:      0.11.4
        - torchtext:         0.17.0+400da5c
        - torchvision:       0.17.0+b2383d4
* System:
        - OS:                Linux
        - architecture:
                - 64bit
                - ELF
        - processor:         x86_64
        - python:            3.10.13
        - release:           5.15.0-91-generic
        - version:           #101-Ubuntu SMP Tue Nov 14 13:30:08 UTC 2023

</details>

cc @jerome-habana

**Comment by awaelchli** [comment]
@ankitgola005 If you set `accelerator="hpu"` it works, right? This line here should be changed to do an instance check in addition for checking the string:

https://github.com/Lightning-AI/pytorch-lightning/blob/096b063d6eeb41567409f4a6b9bac6f5af28ed93/src/lightning/pytorch/trainer/connectors/accelerator_connector.py#L411

to this:

```py
if self._accelerator_flag == "hpu" or isinstance(self._accelerator_flag, HPUAccelerator):
```

**Comment by ankitgola005** [comment]
setting it as accelerator="hpu" works. the check is missing a comparison with HPUAccelerator instance, and so it skips this case and picks from the default SingleDeviceStrategy / DDPStrategy instead.
