### ISSUE TITLE
Log dict changed behavior: can't log train and validation metrics on the same plot

### ISSUE THREAD

**Issue by mfoglio** [Lightning-AI/pytorch-lightning#19620]
### Bug description

I want to log my training and validation metrics on the same plot as two lines of different colors. I used to do that using torch lightning 1.7.7 with the following code:
```
self.log_dict({'output_1 Loss': {'VALIDATION': 0}, 'output_2 Loss': {'VALIDATION': 0}})
```
After updating to `2.2.0+post0`, I get the error:
```
ValueError: `self.log(output_1 Loss, {'VALIDATION': 0})` was called, but `dict` values cannot be logged
```
How should I edit my code?

### What version are you seeing the problem on?

v2.2

### How to reproduce the bug

The following Python code will raise an error when used with the first requirements.txt but not with the second one.

Python Code:
```
import pytorch_lightning as pl
import torch
from torch import nn
from torch.utils.data import DataLoader, Dataset


class DummyNet(nn.Module):

    def __init__(self):
        super(DummyNet, self).__init__()
        self.linear = nn.Linear(10, 1)
        self.linear

    def forward(self, x):
        return self.linear(x)


class DummyModelModule(pl.LightningModule):

    def __init__(self, net: DummyNet):
        super(DummyModelModule, self).__init__()
        self.net = net
        self.loss = torch.nn.MSELoss()
        self.optimizer = torch.optim.SGD(net.parameters(), lr=1e-8, momentum=0.9)

    def forward(self, x: torch.Tensor):
        return self.net(x)

    def configure_optimizers(self):
        return self.optimizer

    def training_step(self, batch, batch_id):
        inputs, y = batch
        y_pred = self.forward(inputs)
        loss = self.loss(y_pred, y)
        self.log('loss', loss, prog_bar=True)
        # let's assume that the model had two outputs
        self.log_dict({
            'output_1 Loss': {'TRAINING': loss},
            'output_2 Loss': {'TRAINING': loss * 2}}
        )
        return {'loss': loss}

    def validation_step(self, batch, batch_id):
        inputs, y = batch
        y_pred = self.forward(inputs)
        loss = self.loss(y_pred, y)
        # let's assume that the model had two outputs
        self.log_dict({
            'output_1 Loss': {'VALIDATION': loss},
            'output_2 Loss': {'VALIDATION': loss * 2}}
        )
        return {'loss': loss}

    def test_step(self, batch, batch_id):
        inputs, y = batch
        y_pred = self.forward(inputs)
        loss = self.loss(y_pred, y)
        return {'loss': loss}


class DummyDataset(Dataset):

    def __init__(self):
        self.items = [
            (
                torch.ones((1, 10), dtype=torch.float32) * i,
                torch.tensor([2 * i - 5], dtype=torch.float32) + torch.randint(-10, 10, (1, ))
            )
            for i in range(100)
        ]

    def __len__(self):
        return len(self.items)

    def __getitem__(self, index: int):
        return self.items[index]


class DummyDataModule(pl.LightningDataModule):

    def __init__(self):
        super().__init__()
        self.save_hyperparameters(logger=False)
        self.train_dataset = None
        self.val_dataset = None
        self.test_dataset = None

    def prepare_data(self):
        pass

    def setup(self, stage = None):
        self.train_dataset = DummyDataset()
        self.val_dataset = DummyDataset()
        self.test_dataset = DummyDataset()

    @property
    def _get_data_loaders_common_kwargs(self):
        return dict(
            batch_size=8,
            num_workers=1,
            pin_memory=True,
            persistent_workers=True,
            prefetch_factor=1,
            drop_last=False
        )

    def train_dataloader(self):
        return DataLoader(self.train_dataset)

    def val_dataloader(self):
        return DataLoader(self.val_dataset)

    def test_dataloader(self):
        return DataLoader(self.test_dataset)


if __name__ == '__main__':
    torch.multiprocessing.set_start_method("fork")

    net = DummyNet()
    model = DummyModelModule(net)
    datamodule = DummyDataModule()
    datamodule.setup()
    trainer = pl.Trainer(max_epochs=5)
    trainer.fit(model, datamodule=datamodule)

```
Requirements.txt (the one that causes the error)
```
albumentations==1.3.0
bidict==0.22.1
diskcache==5.4.0
hydra-colorlog==1.2.0
hydra-core==1.3.2
iterative-stratification==0.1.7
matplotlib==3.7.5
omegaconf==2.3.0
opencv-python==4.9.0.80
opencv-python-headless==4.7.0.72
pandas==1.5.1
pytorch-lightning==2.2.0.post0
pytorch-lightning-bolts==0.3.2.post1
rich==13.7.0
sagemaker==2.112.2
sagemaker-experiments==0.1.39
sagemaker-pytorch-training==2.6.2.post0
sagemaker-training==4.2.9
seaborn==0.13.2
timm==0.9.16
torchmetrics==0.10.0
--extra-index-url https://download.pytorch.org/whl/cu116
torch==2.2.0
--extra-index-url https://download.pytorch.org/whl/cu116
torchvision==0.17.0
```
Requirements.txt (the python code will work just fine with these libraries)
```
albumentations==1.3.0
bidict==0.22.1
diskcache==5.4.0
hydra-colorlog==1.2.0
hydra-core==1.2.0
iterative-stratification==0.1.7
matplotlib==3.6.0
omegaconf==2.2.3
pytorch-lightning==1.7.7
pytorch-lightning-bolts==0.3.2.post1
rich==12.6.0
seaborn==0.12.1
timm==0.5.4
torchmetrics==0.10.0
--extra-index-url https://download.pytorch.org/whl/cu116
torch==1.12.0
--extra-index-url https://download.pytorch.org/whl/cu116
torchvision==0.13.0
```

### Error messages and logs

The following error is raised by the first requirements.txt but not by the second one:
```
ValueError: `self.log(output_1 Loss, {'VALIDATION': tensor(172.3776)})` was called, but `dict` values cannot be logged
```

**Comment by awaelchli** [comment]
If you want to log a dictionary of metrics, you can use `self.log_dict()`.

**Comment by mfoglio** [comment]
Hi @awaelchli , 
Thank you for your reply. Unfortunately, this is not true. I added the Python code to reproduce the error above. Please note that you will get the error only when installing dependencies using the first requirements.txt provided. When using the second one, the python code will work fine.
Let me know if you need any other information. Thank you!

**Comment by awaelchli** [comment]
What I'm saying is that you can't log dictionaries as values:

```py
self.log_dict({'output_1 Loss': {'VALIDATION': 0}, 'output_2 Loss': {'VALIDATION': 0}})
```

Change it to

```py
self.log_dict({'output_1 Loss': 0, 'output_2 Loss': 0})
```

Which is equivalent to 

```py
self.log('output_1 Loss', 0)
self.log('output_2 Loss', 0)
```

**Comment by mfoglio** [comment]
Thank you for your reply, @awaelchli . 
The reason I was using `self.log_dict({'output_1 Loss': {'VALIDATION': 0}, 'output_2 Loss': {'VALIDATION': 0}})` and `self.log_dict({'output_1 Loss': {'TRAIN': 0}, 'output_2 Loss': {'TRAIN': 0}})` is that they allowed me to plot the validation and train values on the same plot:
<img width="548" alt="Screenshot 2024-03-13 at 10 37 08 AM" src="https://github.com/Lightning-AI/pytorch-lightning/assets/19287629/b29de559-a6a4-4ab7-8eb8-4489dd41d4d6">
Do you know how I can achieve the same result with your code?

**Comment by awaelchli** [comment]
That's probably some feature of the TensorBoard logger. You can try to use the TensorBoardLogger directly to achieve this, maybe like this (haven't tried):

```py
self.logger.experiment.add_scalars({'output_1 Loss': {'TRAIN': 0}, 'output_2 Loss': {'TRAIN': 0}})
```

**Comment by awaelchli** [comment]
Can't answer appropriately for the "why it used to work and not anymore" because it's a very long time ago since 1.7. But `self.log` is meant for logging metrics to the logger and nothing more. It has tons of features and needs to stay focused and agnostic to the logger. It can't be misunderstood as a "plotting functionality", because this is highly dependent on the logger being used. So it can't accept any type of input (like a nested dict). 

> Do you know how your proposed solution behave when using DDP and multiple GPUs?
Yes, it will behave well in the sense that it will log on rank 0 (no duplicate logs).

**Comment by mfoglio** [comment]
Thank you for your precious help, @awaelchli . I am experiencing some issue with the logs and plots when using DDP.

I just tried to train my model using DDP. Overall the training is working, but the log is duplicated. What's interesting is that part of the logs is logged twice, even though I am training on 4 GPUs (not 2).

For instance, the progress bars are logged twice:
```
#015Epoch 12:   0%|          | 1/3296 [00:14<13:20:38,  0.07it/s, v_num=0]
#015Epoch 12:   0%|          | 1/3296 [00:14<13:20:40,  0.07it/s, v_num=0]
#015Epoch 12:   0%|          | 2/3296 [00:15<7:13:41,  0.13it/s, v_num=0] 
#015Epoch 12:   0%|          | 2/3296 [00:15<7:13:42,  0.13it/s, v_num=0]
#015Epoch 12:   0%|          | 3/3296 [00:17<5:11:11,  0.18it/s, v_num=0]
#015Epoch 12:   0%|          | 3/3296 [00:17<5:11:12,  0.18it/s, v_num=0]
...
```
A second, possibly unrelated problem, is in the plots.

Note how the first plot have two values for the same step of the validation loss:
<img width="628" alt="Screenshot 2024-03-15 at 12 16 45 PM" src="https://github.com/Lightning-AI/pytorch-lightning/assets/19287629/d898497f-7a04-4df4-9598-c2b09b660f3d">
Details:
<img width="1508" alt="Screenshot 2024-03-15 at 12 19 26 PM" src="https://github.com/Lightning-AI/pytorch-lightning/assets/19287629/b5134153-2d2e-4fa0-a499-0e0d01e759b8">
<img width="1464" alt="Screenshot 2024-03-15 at 12 19 14 PM" src="https://github.com/Lightning-AI/pytorch-lightning/assets/19287629/67022f5b-d199-4f4b-81ad-b5b70b727096">

This is how I log my metrics:
```
    def _log_metrics(self, log_metrics):
        """
        Example of log_metrics during the training_step:
        {
            'original_image_ImageSTD': {'TRAIN': 1.0222947597503662},
            'original_image_Loss': {'TRAIN': 1.5629997253417969}
        }
        Example of log_metrics during the validation_step:
        {
            'original_image_ImageSTD': {'VALIDATION': 0.18248741328716278},
            'original_image_Loss': {'VALIDATION': 0.8312402367591858}
        }
        """
        for metric_name, values in log_metrics.items():
            self.logger.experiment.add_scalars(metric_name, values, self.global_step)
            for split_name, value in values.items():
                self.log(
                    name=f'{metric_name}-{split_name}',
                    value=value,
                    sync_dist=True,
                    rank_zero_only=True,
                    reduce_fx='mean'
                )
```
As you can see each metric is logged twice using:
- `self.logger.experiment.add_scalars(metric_name, values, self.global_step)` to plot the metric
- `self.log` so that the `ModelCheckpoint` can monitor the metric to find the best model
However, the value logged should be the same. Instead, in the figure above, the validation loss is logged twice with two different values.
How can I fix this?
Thank you

**Comment by awaelchli** [comment]
You are printing `#015` to the terminal which is why it's messing up your progress bar.
Your metrics are logged twice because you are logging it twice, so this is not surprising at all. Your usage of `self.log` is not correct. Remove `rank_zero_only=True` (see [docs](https://lightning.ai/docs/pytorch/stable/visualize/logging_advanced.html#rank-zero-only))
Your two values are not the same, because you are reducing across all devices in the `self.log` call, remove `sync_dist=True, reduce_fx='mean'`.

**Comment by mfoglio** [comment]
Hey @awaelchli , thank you for your help.
I did as you suggested, and I get the following warning:
```
/usr/local/lib/python3.8/dist-packages/pytorch_lightning/trainer/connectors/logger_connector/result.py:441: It is recommended to use `self.log('vehicle_color_Loss-VALIDATION', ..., sync_dist=True)` when logging on epoch level in distributed setting to accumulate the metric across devices.
```
Could you clarify why we don't want the `sync_dist=True`?

**Comment by mfoglio** [comment]
Hey @awaelchli, sorry for pinging you. I wondered if you could help me with my question above.

**Comment by awaelchli** [comment]
What I meant was remove `rank_zero_only=True`.
