### ISSUE TITLE
Fabric.save doesn't work with special path containing asterisks

### ISSUE THREAD

**Issue by JalinWang** [Lightning-AI/pytorch-lightning#19623]
### Bug description

When cwd is `outputs/cifar-10/2024-03-13/16-27-23=50*10`, the `Fabric.save` results to save the checkpoint in `outputs/cifar-10/2024-03-13/16-27-23=50010`😮  `50*10` -> `50010`

Snippet & Screenshot: 
```fabric.save("mAP_best_res.pt", mAP_best_res)```
![image](https://github.com/Lightning-AI/pytorch-lightning/assets/20621784/38e49727-14c8-48ea-b477-34e8a77c2e88)

### What version are you seeing the problem on?

v2.1

### How to reproduce the bug

1. create a folder whose name contains an asterisk and then cd into it
2. run python cli ( or create a `.py` and then run):
```python
from lightning.fabric import Fabric
fabric = Fabric()
fabric.save("test", {})
```

Reproduece result:
![image](https://github.com/Lightning-AI/pytorch-lightning/assets/20621784/38e3e160-7793-4188-aff0-4373a57e9d40)

### Environment

<details>
  <summary>Current environment</summary>

```
lightning                 2.1.2
lightning-utilities       0.9.0
pytorch-lightning         2.1.2
OS: ubuntu
```

</details>

**Comment by awaelchli** [comment]
@JalinWang 

Fabric uses `torch.save`. Can you repeat your steps with `torch.save()` directly and confirm it's the same problem?

**Comment by awaelchli** [comment]
I checked, the same happens with `torch.save()`. @JalinWang Could you please report this on the PyTorch side?

**Comment by JalinWang** [comment]
Wait ... My `torch.save()` works well?? ( blue arrow)
![image](https://github.com/Lightning-AI/pytorch-lightning/assets/20621784/d53eb6d8-173c-4f23-9b1c-fcc3cb655872)

**Comment by JalinWang** [comment]
A handier python script for testing & the output:
output:
```
> python test.py
2.0.1
dir: ../test0dir
-- test_save_fabric
dir: ../test*dir
-- test_save_torch
```

```python
import os
from lightning.fabric import Fabric
import torch

dir_name = "test*dir"
os.makedirs(dir_name, exist_ok=True)
os.chdir(dir_name)

fabric = Fabric()
fabric.save("test_save_fabric", {})

torch.save({}, "test_save_torch")

# os.chdir("../")
# os.system("tree ./")

for path, dirs, files in os.walk("../"):
  if not path.endswith("dir"):
    continue
  print(f"dir: {path}")
  for f in files:
    print(f"-- {f}")
```

**Comment by JalinWang** [comment]
I traced it down to `from lightning.fabric.utilities.cloud_io import _atomic_save()` and found it's related with the behavior of `fsspec` lib🤔

```
def _atomic_save(checkpoint: Dict[str, Any], filepath: Union[str, Path]) -> None:
    bytesbuffer = io.BytesIO()
    log.debug(f"Saving checkpoint: {filepath}")
    torch.save(checkpoint, bytesbuffer)
    with fsspec.open(filepath, "wb") as f:
        f.write(bytesbuffer.getvalue())
```

**Comment by JalinWang** [comment]
They treat the asterisk as glob expression!  It does make sense, but ~1 hr in total has gone 😭

python3.11/site-packages/fsspec/core.py
```
from glob import has_magic
```
glob.py
```
magic_check = re.compile('([*?[])')
```
