### ISSUE TITLE
UI issue with Documentation

### ISSUE THREAD

**Issue by Dev-Khant** [Lightning-AI/pytorch-lightning#19669]
### 📚 Documentation

UI issue on https://lightning.ai/docs/fabric/stable/examples/. Tags are overlapping on text.

<img width="753" alt="Screenshot 2024-03-18 at 4 21 25 PM" src="https://github.com/Lightning-AI/pytorch-lightning/assets/57898986/1c78004f-6492-4e18-a782-e5b316a6b1a1">

cc @borda

**Comment by Borda** [comment]
@adamjkuhn could you pls check it :rabbit:

**Comment by Danu8902** [comment]
Tried to contribute to this issue by adding this code: .display-card-container {
    display: flex;
    flex-wrap: wrap;
    justify-content: center;
    gap: 20px; /* Adjust the gap between items */
}

.displayitem {
    flex: 1 0 300px; /* Set a fixed width for each item */
    max-width: 100%; /* Ensure items don't exceed container width */
    margin-bottom: 20px; /* Add some space between items */
}

.displayitem .card {
    height: 100%; /* Ensure all cards have the same height */
}

.displayitem .card-body {
    height: 100%; /* Ensure all card bodies have the same height */
}

.displayitem .card-title {
    margin-bottom: 10px; /* Add some space below the title */
}

.displayitem .card-text {
    margin-bottom: 10px; /* Add some space below the description */
}

.displayitem .btn {
    width: 100%; /* Make the button full-width within the card */
}
, but there's no way knowing if it works, I don't have full permission to the repo. Github isn't allowing me to clone the repo and make the changes, please add it and let me know if it works. I need to know so I can let the Tublian mentors know that I contributed and send them a link that shows my contribution.
@Dev-Khant, @Borda
