### ISSUE TITLE
CLI trainer_defaults logger leads to error in config.yaml

### ISSUE THREAD

**Issue by jonasreiher** [Lightning-AI/pytorch-lightning#19681]
### Bug description

The LightningCLI allows to specify `trainer_defaults`. If you specify a logger there, e.g. the `TensorBoardLogger`, the logged `config.yaml` file includes this:

```yaml
trainer:
  ...
  logger:
  - Unable to serialize instance <lightning.pytorch.loggers.tensorboard.TensorBoardLogger
    object at 0x7f2e65a3aa10>
```

This is problematic if you try to load this config (e.g. for resuming a run) via `python main.py fit --config config.yaml`, where you get an error.

In the logged config.yaml, I would expect either no entry at all for the logger (this is also the case for callbacks if you add them through `trainer_defaults` or something like this:

```yaml
trainer:
  logger:
    class_path: lightning.pytorch.loggers.TensorBoardLogger
    init_args:
      save_dir: .
      name: logs
      version: null
      ...
```

### What version are you seeing the problem on?

v2.2

### How to reproduce the bug

```python
# main.py

from lightning.pytorch.cli import LightningCLI
from lightning.pytorch.demos.boring_classes import BoringDataModule, BoringModel
from lightning.pytorch.loggers import TensorBoardLogger

if __name__ == "__main__":
    cli = LightningCLI(
        model_class=BoringModel,
        datamodule_class=BoringDataModule,
        trainer_defaults={
            "logger": [TensorBoardLogger(".")],
        },
    )


```sh
python main.py fit --trainer.max_epochs 1
```

Then check `lightning_logs/version_0/config.yaml` and try

```sh
python main.py fit --config lightning_logs/version_0/config.yaml
```

### Error messages and logs

```txt
error: Parser key "trainer.logger":
  Does not validate against any of the Union subtypes
  Subtypes: (<class 'lightning.pytorch.loggers.logger.Logger'>, typing.Iterable[lightning.pytorch.loggers.logger.Logger], <class 'bool'>, <class 'NoneType'>)
  Errors:
    - Not a valid subclass of Logger
      Subclass types expect one of:
      - a class path (str)
      - a dict with class_path entry
      - a dict without class_path but with init_args entry (class path given previously)
    - Unexpected import path format: Unable to serialize instance <lightning.pytorch.loggers.tensorboard.TensorBoardLogger object at 0x7f2e65a3aa10>
    - Expected a <class 'bool'>
    - Expected a <class 'NoneType'>
  Given value type: <class 'list'>
  Given value: ['Unable to serialize instance <lightning.pytorch.loggers.tensorboard.TensorBoardLogger object at 0x7f2e65a3aa10>']
```

### Environment

<details>
  <summary>Current environment</summary>

* CUDA:
        - GPU:
                - NVIDIA A10
        - available:         True
        - version:           12.1
* Lightning:
        - lightning:         2.2.1
        - lightning-utilities: 0.10.1
        - pytorch-lightning: 2.2.1
        - torch:             2.2.1
        - torchmetrics:      1.3.1
        - torchrl:           0.3.1
        - torchvision:       0.17.1
* Packages:
        - absl-py:           2.1.0
        - aiohttp:           3.9.3
        - aiosignal:         1.3.1
        - antlr4-python3-runtime: 4.9.3
        - asttokens:         2.4.1
        - attrs:             23.2.0
        - bitsandbytes:      0.41.0
        - black:             24.2.0
        - click:             8.1.7
        - cloudpickle:       3.0.0
        - comm:              0.2.2
        - contourpy:         1.2.0
        - cycler:            0.12.1
        - debugpy:           1.8.1
        - decorator:         5.1.1
        - docstring-parser:  0.15
        - executing:         2.0.1
        - filelock:          3.13.1
        - fonttools:         4.49.0
        - frozenlist:        1.4.1
        - fsspec:            2024.2.0
        - grpcio:            1.62.1
        - hydra-core:        1.3.2
        - iaml:              1.0a1
        - idna:              3.6
        - importlib-resources: 6.3.0
        - ipykernel:         6.29.3
        - ipython:           8.22.2
        - isort:             5.13.2
        - jedi:              0.19.1
        - jinja2:            3.1.3
        - jsonargparse:      4.27.5
        - jupyter-client:    8.6.1
        - jupyter-core:      5.7.2
        - kiwisolver:        1.4.5
        - lightning:         2.2.1
        - lightning-utilities: 0.10.1
        - markdown:          3.5.2
        - markdown-it-py:    3.0.0
        - markupsafe:        2.1.5
        - matplotlib:        3.8.3
        - matplotlib-inline: 0.1.6
        - mdurl:             0.1.2
        - mpmath:            1.3.0
        - multidict:         6.0.5
        - mypy-extensions:   1.0.0
        - nest-asyncio:      1.6.0
        - networkx:          3.2.1
        - numpy:             1.26.4
        - nvidia-cublas-cu12: 12.1.3.1
        - nvidia-cuda-cupti-cu12: 12.1.105
        - nvidia-cuda-nvrtc-cu12: 12.1.105
        - nvidia-cuda-runtime-cu12: 12.1.105
        - nvidia-cudnn-cu12: 8.9.2.26
        - nvidia-cufft-cu12: 11.0.2.54
        - nvidia-curand-cu12: 10.3.2.106
        - nvidia-cusolver-cu12: 11.4.5.107
        - nvidia-cusparse-cu12: 12.1.0.106
        - nvidia-nccl-cu12:  2.19.3
        - nvidia-nvjitlink-cu12: 12.4.99
        - nvidia-nvtx-cu12:  12.1.105
        - omegaconf:         2.3.0
        - packaging:         24.0
        - parso:             0.8.3
        - pathspec:          0.12.1
        - pexpect:           4.9.0
        - pillow:            10.2.0
        - pip:               23.3.1
        - pip-autoremove:    0.10.0
        - platformdirs:      4.2.0
        - prompt-toolkit:    3.0.43
        - protobuf:          4.25.3
        - psutil:            5.9.8
        - ptyprocess:        0.7.0
        - pure-eval:         0.2.2
        - pygments:          2.17.2
        - pyparsing:         3.1.2
        - python-dateutil:   2.9.0.post0
        - pytorch-lightning: 2.2.1
        - pyyaml:            6.0.1
        - pyzmq:             25.1.2
        - rich:              13.7.1
        - setuptools:        68.2.2
        - six:               1.16.0
        - stack-data:        0.6.3
        - sympy:             1.12
        - tensorboard:       2.16.2
        - tensorboard-data-server: 0.7.2
        - tensorboardx:      2.6.2.2
        - tensordict:        0.3.1
        - torch:             2.2.1
        - torchmetrics:      1.3.1
        - torchrl:           0.3.1
        - torchvision:       0.17.1
        - tornado:           6.4
        - tqdm:              4.66.2
        - traitlets:         5.14.2
        - triton:            2.2.0
        - typeshed-client:   2.5.1
        - typing-extensions: 4.10.0
        - wcwidth:           0.2.13
        - werkzeug:          3.0.1
        - wheel:             0.41.2
        - yarl:              1.9.4
* System:
        - OS:                Linux
        - architecture:
                - 64bit
                - ELF
        - processor:         x86_64
        - python:            3.11.8
        - release:           5.15.0-39-generic
        - version:           #42-Ubuntu SMP Thu Jun 9 23:42:32 UTC 2022

</details>

**Comment by mauvilsa** [comment]
Don't use an instance to set a default, because jsonargparse is not able to know how that instance was created to know what to save in the config. Instead, for the default use a dict with `class_path` and `init_args`, like:
```python
        trainer_defaults={
            "logger": {
                "class_path": "...",
                "init_args": {
                    ...
                },
            },
        },
```

**Comment by jonasreiher** [comment]
Thanks! Now that I think about it, this makes a lot of sense. Why is the behavior different for callbacks added via trainer defaults, though?
