### ISSUE TITLE
Expose client argument in `MLFlowLogger`

### ISSUE THREAD

**Issue by dannyfriar** [Lightning-AI/pytorch-lightning#19710]
### Description & Motivation

MLflow has an [async autologging client](https://github.com/mlflow/mlflow/blob/2248511d5d86bbd751a0fea4241f78be7bc8f3c8/mlflow/utils/autologging_utils/client.py#L89). It also allows logging metrics asynchronously by passing `synchronous=False` to the various `log_` methods.

It would be useful to support passing in a client argument to the `MLflowLogger` to make it possible to use the async client. Or alternatively, exposing a `synchronous` argument that would be passed down to the `log_` methods.

Maybe this autologging client should be the default? This is already the default when using the `mlflow` autolog: https://github.com/mlflow/mlflow/blob/master/mlflow/pytorch/_lightning_autolog.py#L472.

cc @borda

**Comment by awaelchli** [comment]
@dannyfriar I've discussed this with @clumsy in #19639. 
I vote for exposing a flag on the MLFLowLogger.

It seems that there are multiple ways to implement it. @clumsy wanted to use threading directly in the logger (see the PR). You proposed to set this trough the client. Please discuss here the pros and cons so we can converge on a solution. Thanks!

**Comment by dannyfriar** [comment]
Thanks I hadn't seen this PR. The main reason I suggested exposing via the client is to match the way it's done in the mlflow pytorch autlogging but after looking through that code I think it's simpler and neater to use the synchronous flag. The batch autlogging client isn't documented very well. 

It's also possible to enable this via the `MLFLOW_ENABLE_ASYNC_LOGGING` env var but I'd still vote for having the flag.

**Comment by clumsy** [comment]
Please check my proposal, @dannyfriar: https://github.com/Lightning-AI/pytorch-lightning/pull/19639#issuecomment-2026250772
