### ISSUE TITLE
Unable to extend FSDPStrategy to HPU accelerator

### ISSUE THREAD

**Issue by jyothisambolu** [Lightning-AI/pytorch-lightning#19753]
### Bug description

We are trying to support FSDP strategy on HPU accelerators. But due to a restriction from accelerator connector, we are unable to use FSDPStrategy on HPU.

https://github.com/Lightning-AI/pytorch-lightning/blob/76b691d80c6c5203c66365272ce246ac86e418f0/src/lightning/pytorch/trainer/connectors/accelerator_connector.py#L459

### What version are you seeing the problem on?

v2.2

### Error messages and logs

```
# Error messages and logs
Traceback (most recent call last):
  File "/home/jsambolu/github/fsdp_integration/lightning-Habana/tests/test_pytorch/../../examples/pytorch/language_model.py", line 92, in <module>
    trainer = Trainer(accelerator=HPUAccelerator(), strategy=_strategy, fast_dev_run=10, enable_model_summary=True)
  File "/home/jsambolu/venv/lib/python3.10/site-packages/lightning/pytorch/utilities/argparse.py", line 70, in insert_env_defaults
    return fn(self, **kwargs)
  File "/home/jsambolu/venv/lib/python3.10/site-packages/lightning/pytorch/trainer/trainer.py", line 401, in __init__
    self._accelerator_connector = _AcceleratorConnector(
  File "/home/jsambolu/venv/lib/python3.10/site-packages/lightning/pytorch/trainer/connectors/accelerator_connector.py", line 159, in __init__
    self._check_strategy_and_fallback()
  File "/home/jsambolu/venv/lib/python3.10/site-packages/lightning/pytorch/trainer/connectors/accelerator_connector.py", line 487, in _check_strategy_and_fallback
    raise MisconfigurationException(
lightning.fabric.utilities.exceptions.MisconfigurationException: You selected strategy to be `fsdp`, but GPU accelerator is not used.
```

### Environment

<details>
  <summary>Current environment</summary>

```
#- Lightning Component (e.g. Trainer, LightningModule, LightningApp, LightningWork, LightningFlow):
#- PyTorch Lightning Version (e.g., 1.5.0):
#- Lightning App Version (e.g., 0.5.2):
#- PyTorch Version (e.g., 2.0):
#- Python version (e.g., 3.9):
#- OS (e.g., Linux):
#- CUDA/cuDNN version:
#- GPU models and configuration:
#- How you installed Lightning(`conda`, `pip`, source):
#- Running environment of LightningApp (e.g. local, cloud):
```

</details>

**Comment by jerome-habana** [comment]
@Borda FYA

**Comment by awaelchli** [comment]
@jyothisambolu Isn't PyTorch's FSDP only compatible with CUDA? Do you have a custom FSDPStrategy? I can't find one in lightning-habana.

**Comment by jerome-habana** [comment]
> @jyothisambolu Isn't PyTorch's FSDP only compatible with CUDA? Do you have a custom FSDPStrategy? I can't find one in lightning-habana.

@awaelchli - to push HPUFSDPStrategy, we need this change to be in place else we get the error mentioned in the issue above. Once this is pushed in, we'll push the FSDP PR to lightning-habana. I can share a draft if it helps.

**Comment by awaelchli** [comment]
@jerome-habana Yes please, that would be very insightful. I'd like to know whether your FSDP strategy subclasses ours and if so, to what extend.

**Comment by jerome-habana** [comment]
> @jerome-habana Yes please, that would be very insightful. I'd like to know whether your FSDP strategy subclasses ours and if so, to what extend.

@awaelchli checkout https://github.com/Lightning-AI/lightning-Habana/pull/174 . It mostly includes changes wrt initialization and device usage instead of index

**Comment by awaelchli** [comment]
@jerome-habana Thanks for sharing. I opened an alternative approach in #19781 that would unblock you. #19781 is closer to the original intent of the error checking and doesn't require a check against the integration. After the FSDP strategy in habana-lightning is released, we can still add more error checking if we want to.

Regarding the HPU FSDP implementation: I see there are several overrides of internals. Please note that we don't provide backward compatibility for internals of strategies, especially the protected methods and members. We will make changes to the FSDP strategy that may break your overrides. If this is undesired, I recommend not subclassing FSDPStrategy and instead subclassing ParallelStrategy.

**Comment by jerome-habana** [comment]
> @jerome-habana Thanks for sharing. I opened an alternative approach in #19781 that would unblock you. #19781 is closer to the original intent of the error checking and doesn't require a check against the integration. After the FSDP strategy in habana-lightning is released, we can still add more error checking if we want to.
> 
> Regarding the HPU FSDP implementation: I see there are several overrides of internals. Please note that we don't provide backward compatibility for internals of strategies, especially the protected methods and members. We will make changes to the FSDP strategy that may break your overrides. If this is undesired, I recommend not subclassing FSDPStrategy and instead subclassing ParallelStrategy.

@awaelchli in the long run, we want to move away from inheriting native strategies. But for now, we are dependent on base class fsdp strategy with the gpu checks removed to enable fsdp with hpu. This is to avoid some code duplication and have accelerator specific change alone inside hpufsdpstrategy.

**Comment by jyothisambolu** [comment]
@awaelchli Can you please apply the fix to lightning-fabric as well? The same check is present inside fabric connector and is disallowing usage of FSDP strategy with fabric on HPU.

https://github.com/Lightning-AI/pytorch-lightning/blob/76b691d80c6c5203c66365272ce246ac86e418f0/src/lightning/pytorch/trainer/connectors/accelerator_connector.py#L459
