### ISSUE TITLE
Does `fabric.save()` save on rank 0?

### ISSUE THREAD

**Issue by LautaroEst** [Lightning-AI/pytorch-lightning#19780]
### Bug description

I'm trying to save a simple object using `fabric.save()` but always get the same error and I don't know if I'm missing something about the way checkpoints are saved and loaded or if it's a bug.  The error is caused when saving the model, and the `fabric.barrier()` produces that the state.pkl file is saved correclty. However I always get the same `RuntimeError: [../third_party/gloo/gloo/transport/tcp/pair.cc:534] Connection closed by peer [10.1.103.33]:62095` error.

I've already red the [documentation](https://lightning.ai/docs/fabric/stable/guide/checkpoint/distributed_checkpoint.html) but I still don't understand why it is happening.

### What version are you seeing the problem on?

v2.2

### How to reproduce the bug

```python
import lightning as L

def setup():

    fabric = L.Fabric(accelerator="cpu", devices=2)
    fabric.launch(main)

def main(fabric):

    state = {"a": 1, "b": 2}

    if fabric.global_rank == 0:
        fabric.save("state.pkl", state)
    
    fabric.barrier()


if __name__ == "__main__":
    setup()
```

### Error messages and logs

```
Initializing distributed: GLOBAL_RANK: 0, MEMBER: 1/2
Initializing distributed: GLOBAL_RANK: 1, MEMBER: 2/2
----------------------------------------------------------------------------------------------------
distributed_backend=gloo
All distributed processes registered. Starting with 2 processes
----------------------------------------------------------------------------------------------------

Traceback (most recent call last):
  File "/mnt/DATOS-KOALA/Documents/Doctorado/test_fabric/main.py", line 20, in <module>
    setup()
  File "/mnt/DATOS-KOALA/Documents/Doctorado/test_fabric/main.py", line 7, in setup
    fabric.launch(main)
  File "/mnt/DATOS-KOALA/anaconda3/envs/llmcal/lib/python3.12/site-packages/lightning/fabric/fabric.py", line 859, in launch
    return self._wrap_and_launch(function, self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/DATOS-KOALA/anaconda3/envs/llmcal/lib/python3.12/site-packages/lightning/fabric/fabric.py", line 944, in _wrap_and_launch
    return launcher.launch(to_run, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/DATOS-KOALA/anaconda3/envs/llmcal/lib/python3.12/site-packages/lightning/fabric/strategies/launchers/subprocess_script.py", line 107, in launch
    return function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/DATOS-KOALA/anaconda3/envs/llmcal/lib/python3.12/site-packages/lightning/fabric/fabric.py", line 950, in _wrap_with_setup
    return to_run(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/DATOS-KOALA/Documents/Doctorado/test_fabric/main.py", line 16, in main
    fabric.barrier()
  File "/mnt/DATOS-KOALA/anaconda3/envs/llmcal/lib/python3.12/site-packages/lightning/fabric/fabric.py", line 545, in barrier
    self._strategy.barrier(name=name)
  File "/mnt/DATOS-KOALA/anaconda3/envs/llmcal/lib/python3.12/site-packages/lightning/fabric/strategies/ddp.py", line 162, in barrier
    torch.distributed.barrier()
  File "/mnt/DATOS-KOALA/anaconda3/envs/llmcal/lib/python3.12/site-packages/torch/distributed/c10d_logger.py", line 72, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/DATOS-KOALA/anaconda3/envs/llmcal/lib/python3.12/site-packages/torch/distributed/distributed_c10d.py", line 3446, in barrier
    work.wait()
RuntimeError: [../third_party/gloo/gloo/transport/tcp/pair.cc:534] Connection closed by peer [10.1.103.33]:62095
```

### Environment

<details>
  <summary>Current environment</summary>

* CUDA:
	- GPU:               None
	- available:         False
	- version:           12.1
* Lightning:
	- lightning:         2.2.2
	- lightning-utilities: 0.11.2
	- pytorch-lightning: 2.2.2
	- torch:             2.2.2
	- torchmetrics:      1.3.2
* Packages:
	- aiohttp:           3.9.4
	- aiosignal:         1.3.1
	- attrs:             23.2.0
	- filelock:          3.13.4
	- frozenlist:        1.4.1
	- fsspec:            2024.3.1
	- idna:              3.7
	- jinja2:            3.1.3
	- lightning:         2.2.2
	- lightning-utilities: 0.11.2
	- markupsafe:        2.1.5
	- mpmath:            1.3.0
	- multidict:         6.0.5
	- networkx:          3.3
	- numpy:             1.26.4
	- nvidia-cublas-cu12: 12.1.3.1
	- nvidia-cuda-cupti-cu12: 12.1.105
	- nvidia-cuda-nvrtc-cu12: 12.1.105
	- nvidia-cuda-runtime-cu12: 12.1.105
	- nvidia-cudnn-cu12: 8.9.2.26
	- nvidia-cufft-cu12: 11.0.2.54
	- nvidia-curand-cu12: 10.3.2.106
	- nvidia-cusolver-cu12: 11.4.5.107
	- nvidia-cusparse-cu12: 12.1.0.106
	- nvidia-nccl-cu12:  2.19.3
	- nvidia-nvjitlink-cu12: 12.4.127
	- nvidia-nvtx-cu12:  12.1.105
	- packaging:         24.0
	- pip:               23.3.1
	- pytorch-lightning: 2.2.2
	- pyyaml:            6.0.1
	- setuptools:        68.2.2
	- sympy:             1.12
	- torch:             2.2.2
	- torchmetrics:      1.3.2
	- tqdm:              4.66.2
	- typing-extensions: 4.11.0
	- wheel:             0.41.2
	- yarl:              1.9.4
* System:
	- OS:                Linux
	- architecture:
		- 64bit
		- ELF
	- processor:         x86_64
	- python:            3.12.2
	- release:           6.5.0-26-generic
	- version:           #26~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Tue Mar 12 10:22:43 UTC 2

</details>

cc @carmocca @justusschock @awaelchli

**Comment by awaelchli** [comment]
@LautaroEst The use of 

```py
if fabric.global_rank == 0:
        fabric.save("state.pkl", state)
```

is not correct. Can you please remove `if fabric.global_rank == 0`. Fabric already makes sure to save correctly on the rank that should save. Here is the checkpointing guide:

https://lightning.ai/docs/fabric/stable/guide/checkpoint/checkpoint.html

And the docs state:

> Fabric and the underlying strategy will decide in which format your checkpoint gets saved. For example, strategy="ddp" saves a single file on rank 0, while strategy="fsdp" saves multiple files from all ranks.

**Comment by LautaroEst** [comment]
Thanks @awaelchli, it worked! I don't know why I was convinced that saving should be done under the if statement.
