### ISSUE TITLE
The packages such as libraries and models are not loading from files 

### ISSUE THREAD

**Issue by sinanLab** [Lightning-AI/pytorch-lightning#19792]
### Bug description

I'm using PyTorch Lightning for model training. Some of the external files, such as datasets and data loaders, can be loaded, but models and other custom libraries cannot be loaded from directories. I have already the code multiple times and works fine, but the main issue is that I can't import packages from outside. Including all the code in one file makes the code messy.

<img width="1280" alt="error" src="https://github.com/Lightning-AI/pytorch-lightning/assets/61152623/c455dd20-00d6-419a-982b-57f08f0737d6">

### What version are you seeing the problem on?

v2.2

### Error messages and logs

(cuda-env) sinan@sinan:/mnt/d/new_code_successful$ python pinn.py
2024-04-21 04:19:35.703608: I tensorflow/core/util/port.cc:113] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2024-04-21 04:19:35.781649: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-04-21 04:19:35.781698: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-04-21 04:19:35.798250: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-04-21 04:19:35.822356: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: SSE4.1 SSE4.2 AVX AVX2 AVX_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
Traceback (most recent call last):
  File "/mnt/d/new_code_successful/pinn.py", line 11, in <module>
    from models.basics import SimpleNN
ModuleNotFoundError: No module named 'models'

### Environment

(cuda-env) sinan@sinan:/mnt/d/new_code_successful$ python collect_env_details.py
/mnt/d/new_code_successful/collect_env_details.py:24: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  import pkg_resources
<details>
  <summary>Current environment</summary>

* CUDA:
        - GPU:
                - NVIDIA GeForce RTX 4050 Laptop GPU
        - available:         True
        - version:           12.0
* Lightning:
        - lightning-utilities: 0.11.2
        - pytorch-lightning: 2.2.2
        - torch:             2.1.2.post300
        - torchaudio:        2.1.2
        - torchmetrics:      1.3.2
        - torchvision:       0.16.2
* Packages:
        - absl-py:           2.1.0
        - aiohttp:           3.9.3
        - aiosignal:         1.3.1
        - astunparse:        1.6.3
        - attrs:             23.2.0
        - blinker:           1.7.0
        - brotli:            1.1.0
        - cached-property:   1.5.2
        - cachetools:        5.3.3
        - certifi:           2024.2.2
        - cffi:              1.16.0
        - chardet:           5.2.0
        - charset-normalizer: 3.3.2
        - click:             8.1.7
        - colorama:          0.4.6
        - contourpy:         1.2.1
        - coverage:          7.4.4
        - cryptography:      42.0.5
        - cycler:            0.12.1
        - datasets:          2.19.0
        - dill:              0.3.8
        - distlib:           0.3.8
        - exceptiongroup:    1.2.0
        - filelock:          3.13.4
        - flatbuffers:       24.3.25
        - fonttools:         4.51.0
        - frozenlist:        1.4.1
        - fsspec:            2024.3.1
        - gast:              0.5.4
        - google-auth:       2.29.0
        - google-auth-oauthlib: 1.2.0
        - google-pasta:      0.2.0
        - grpcio:            1.59.3
        - h5py:              3.11.0
        - huggingface-hub:   0.22.2
        - idna:              3.7
        - importlib-metadata: 7.1.0
        - iniconfig:         2.0.0
        - jinja2:            3.1.3
        - joblib:            1.4.0
        - keras:             2.15.0
        - kiwisolver:        1.4.5
        - lightning-utilities: 0.11.2
        - markdown:          3.6
        - markupsafe:        2.1.5
        - matplotlib:        3.8.4
        - ml-dtypes:         0.2.0
        - mock:              5.1.0
        - mpmath:            1.3.0
        - multidict:         6.0.5
        - multiprocess:      0.70.16
        - munkres:           1.1.4
        - networkx:          3.3
        - nose:              1.3.7
        - numpy:             1.26.4
        - oauthlib:          3.2.2
        - opt-einsum:        3.3.0
        - packaging:         24.0
        - pandas:            2.2.2
        - pillow:            10.2.0
        - pip:               23.3.1
        - platformdirs:      4.2.0
        - pluggy:            1.4.0
        - ply:               3.11
        - protobuf:          4.24.4
        - pyarrow:           15.0.0
        - pyarrow-hotfix:    0.6
        - pyasn1:            0.6.0
        - pyasn1-modules:    0.4.0
        - pycparser:         2.22
        - pyjwt:             2.8.0
        - pyopenssl:         24.0.0
        - pyparsing:         3.0.9
        - pyproject-api:     1.6.1
        - pyqt5:             5.15.10
        - pyqt5-sip:         12.13.0
        - pysocks:           1.7.1
        - pytest:            8.1.1
        - python-dateutil:   2.9.0
        - pytorch-lightning: 2.2.2
        - pytz:              2024.1
        - pyu2f:             0.1.5
        - pyyaml:            6.0.1
        - regex:             2024.4.16
        - requests:          2.31.0
        - requests-oauthlib: 2.0.0
        - rsa:               4.9
        - safetensors:       0.4.3
        - scikit-learn:      1.4.2
        - scipy:             1.13.0
        - setuptools:        68.2.2
        - sip:               6.7.12
        - six:               1.16.0
        - sympy:             1.12
        - tensorboard:       2.15.2
        - tensorboard-data-server: 0.7.0
        - tensorflow:        2.15.0
        - tensorflow-estimator: 2.15.0
        - termcolor:         2.4.0
        - threadpoolctl:     3.4.0
        - tokenizers:        0.15.2
        - tomli:             2.0.1
        - torch:             2.1.2.post300
        - torchaudio:        2.1.2
        - torchmetrics:      1.3.2
        - torchvision:       0.16.2
        - tornado:           6.4
        - tox:               4.14.2
        - tqdm:              4.66.2
        - transformers:      4.39.3
        - typing-extensions: 4.11.0
        - tzdata:            2024.1
        - urllib3:           2.2.1
        - virtualenv:        20.25.3
        - werkzeug:          3.0.2
        - wheel:             0.41.2
        - wrapt:             1.14.1
        - xxhash:            3.4.1
        - yarl:              1.9.4
        - zipp:              3.17.0
* System:
        - OS:                Linux
        - architecture:
                - 64bit
                - ELF
        - processor:         x86_64
        - python:            3.11.8
        - release:           5.15.146.1-microsoft-standard-WSL2
        - version:           #1 SMP Thu Jan 11 04:09:03 UTC 2024

</details>

**Comment by awaelchli** [comment]
@sinanLab This isn't caused by PyTorch Lightning. This is simply because you are running the Python program from a directory other than the one where "models" is. Python can't know from where you'd want to import this `models.basics`. Either make your code base into a proper package (Using a setup.py file for instance), or by appending the path to the `models.basics` module to the Python system path (you can find examples of this online).
