### ISSUE TITLE
FSDP Strategy checkpoint loading

### ISSUE THREAD

**Issue by xin-w8023** [Lightning-AI/pytorch-lightning#19802]
### Description & Motivation

https://github.com/Lightning-AI/pytorch-lightning/blob/b9680a364da4e875b237ec3c03e67a9c32ef475b/src/lightning/pytorch/strategies/fsdp.py#L587-L596
Here we can only check a local path whether sharded or not. Any remote file path like hdfs://, the function will eventually raise an error. 

cc @borda

**Comment by awaelchli** [comment]
The feature has been requested here: #18786
Contributions always welcome :)
