### ISSUE TITLE
Is the Lightning App deprecated? (Lightning App doc is not found)

### ISSUE THREAD

**Issue by guyleaf** [Lightning-AI/pytorch-lightning#19854]
### Bug description

Hi,
I cannot find the documentation for Lightning Apps from the main website.

It seems the [link](https://lightning.ai/docs/app/stable/) is broken.
Is it a bug or something?

Thanks

### What version are you seeing the problem on?

master

### How to reproduce the bug
The [link](https://lightning.ai/docs/app/stable/) will be redirected to the main docs.

### Error messages and logs

```
# Error messages and logs here please
```

### Environment

<details>
  <summary>Current environment</summary>

```
#- Lightning Component (e.g. Trainer, LightningModule, LightningApp, LightningWork, LightningFlow):
#- PyTorch Lightning Version (e.g., 1.5.0):
#- Lightning App Version (e.g., 0.5.2):
#- PyTorch Version (e.g., 2.0):
#- Python version (e.g., 3.9):
#- OS (e.g., Linux):
#- CUDA/cuDNN version:
#- GPU models and configuration:
#- How you installed Lightning(`conda`, `pip`, source):
#- Running environment of LightningApp (e.g. local, cloud):
```

</details>

**Comment by lantiga** [comment]
Hey @guyleaf we will be restructuring apps in the future in a smaller-scoped package, so we're phasing out the current implementation.
On that note I'd be interested in understanding your use case better, would it be possible for you to describe it (here or on our Discord)?
