### ISSUE TITLE
AttributeError: type object 'Trainer' has no attribute 'add_argparse_args'

### ISSUE THREAD

**Issue by Park-yebin** [Lightning-AI/pytorch-lightning#19905]
### Bug description

When trying to run

```
parser = argparse.ArgumentParser()
parser = Trainer.add_argparse_args(parser)
args = parser.parse_args([])
```
AttributeError: type object 'Trainer' has no attribute 'add_argparse_args'
That error message appears.

### What version are you seeing the problem on?

v2.0, v2.1, v2.2

### How to reproduce the bug

```python
import argparse
import pytorch_lightning
from pytorch_lightning.trainer import Trainer
from pytorch_lightning.callbacks import ModelCheckpoint, Callback, LearningRateMonitor

parser = argparse.ArgumentParser()
parser.add_argument(
        "--gpus",
        type=int,
        default=1,
        help="num of gpus to use",
)
parser = Trainer.add_argparse_args(parser)
args = parser.parse_args()
```
```
AttributeError: type object 'Trainer' has no attribute 'add_argparse_args'
```

#- Lightning Component (e.g. Trainer, LightningModule, LightningApp, LightningWork, LightningFlow): Trainer
#- PyTorch Lightning Version (e.g., 1.5.0): 2.0.0
#- Lightning App Version (e.g., 0.5.2):
#- PyTorch Version (e.g., 2.0): 2.0.1
#- Python version (e.g., 3.9): 3.8.8
#- OS (e.g., Linux): Linux
#- CUDA/cuDNN version: 12.0
#- GPU models and configuration:
#- How you installed Lightning(`conda`, `pip`, source): conda install pytorch-lightning=2.0.0 -c conda-forge
#- Running environment of LightningApp (e.g. local, cloud):

### More info

When I first encountered the error, I thought it might be a version conflict issue between internal programs, so I installed 'pytorch_lightning' anew by referring to the link('https://lightning.ai/docs/pytorch/stable/versioning.html').
I finished reinstalling, but that didn't solve the problem. What's the problem?
(At first, I've installed ver 2.2 then, I convert to 2.0. For test I've done the same thing at ver 2.1)

**Comment by awaelchli** [comment]
Hi 
The method removed in 2.0, so the AttributeError is expected. 
The change is documented in the [migration guide](https://lightning.ai/docs/pytorch/stable/upgrade/from_1_9.html).
In the [release notes](https://github.com/Lightning-AI/pytorch-lightning/releases/tag/2.0.0#bc-changes), we give some more details for the reason of the change (section "The brittle argument parsing utilities").
