### ISSUE TITLE
`grep: Invalid option -- P` when running `./tests/run_standalone_tests.sh` on macOS

### ISSUE THREAD

**Issue by Peiffap** [Lightning-AI/pytorch-lightning#19938]
### Bug description

BSD `grep` no longer supports the `-- P` option on macOS.

One fix would be to use GNU `grep` instead, as `ggrep`.

### What version are you seeing the problem on?

master

### Error messages and logs

```
# Error messages and logs here please
```

### Environment

<details>
  <summary>Current environment</summary>

```
#- Lightning Component (e.g. Trainer, LightningModule, LightningApp, LightningWork, LightningFlow):
#- PyTorch Lightning Version (e.g., 1.5.0):
#- Lightning App Version (e.g., 0.5.2):
#- PyTorch Version (e.g., 2.0):
#- Python version (e.g., 3.9):
#- OS (e.g., Linux):
#- CUDA/cuDNN version:
#- GPU models and configuration:
#- How you installed Lightning(`conda`, `pip`, source):
#- Running environment of LightningApp (e.g. local, cloud):
```

</details>

cc @borda

**Comment by awaelchli** [comment]
Hey @Peiffap 
You are welcome to send a PR for this if you'd like. 
We don't have any tests in `run_standalone_tests.sh` that would run on macos, but for completeness, this fix would be good IMO.
