### ISSUE TITLE
docker image doesn't have `pytorch_lightning`

### ISSUE THREAD

**Issue by grisaitis** [Lightning-AI/pytorch-lightning#19951]
### Bug description

```shell
$ docker run --rm pytorchlightning/pytorch_lightning:base-cuda-py3.10-torch2.2-cuda12.1.0 python -c "import pytorch_lightning"

==========
== CUDA ==
==========

CUDA Version 12.1.0

...

Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'pytorch_lightning'
```

is this the intended behavior?

### What version are you seeing the problem on?

v2.2

cc @borda

**Comment by Borda** [comment]
Hello, apologies for the confusion, this is not docker for production but for development and in particular the one you refer is for CI as you can see that it does not mention PL in the tag at all...
