### ISSUE TITLE
Make distributed checkpoint saving atomic

### ISSUE THREAD

**Issue by awaelchli** [Lightning-AI/pytorch-lightning#20012]
### Description & Motivation

As an extension to #20011, we could make our distributed checkpoints saving logic atomic too:
https://github.com/Lightning-AI/pytorch-lightning/blob/55b95f26adf7156036f6450d33001c2aaa7a0fbb/src/lightning/fabric/strategies/fsdp.py#L874

### Pitch

First check whether the FileSystemWriter from PyTorch is already atomic. Write to a tmp directory first, then rename it. Depending on whether #18786 wants to progress, might be easier to do after?

### Additional context

cc @borda @awaelchli @corwinjoy

**Comment by corwinjoy** [comment]
@awaelchli  Seems like a reasonable idea, but it may not be general enough depending on how general your storage specs are. As I understand it from reading through fsspec code, it seems some storage targets may not even have directories. I also see that in the torch code, at least for filesystems, it looks like .tmp files are created first and then these are renamed giving some additional integrity.  e.g.

torch/distributed/checkpoint/filesystem.py: 524
```
class FileSystemWriter(StorageWriter):
...
    def finish(self, metadata: Metadata, results: List[List[WriteResult]]) -> None:
        storage_md = dict()
        for wr_list in results:
            storage_md.update({wr.index: wr.storage_data for wr in wr_list})
        metadata.storage_data = storage_md
        tmp_path = cast(Path, self.fs.concat_path(self.path, ".metadata.tmp"))
        meta_path = cast(Path, self.fs.concat_path(self.path, ".metadata"))
        with self.fs.create_stream(tmp_path, "wb") as metadata_file:
            pickle.dump(metadata, metadata_file)
            if self.sync_files:
                try:
                    os.fsync(metadata_file.fileno())
                except AttributeError:
                    os.sync()

        self.fs.rename(tmp_path, meta_path)
```

One alternative might be to write some kind of checksum or marker file to indicate that a directory save is complete. This could serve as an alternative for accepting that a checkpoint is complete.

**Comment by awaelchli** [comment]
If filesystem writer already does this, then that's great and we don't have to do anything.
Even if it wasn't, I don't see why we couldn't just move the files using https://filesystem-spec.readthedocs.io/en/latest/api.html#fsspec.spec.AbstractFileSystem.mv. Seems like a trivial operation that any filesystem should support.
