### ISSUE TITLE
`pkg_resources` Deprecation Warnings on import

### ISSUE THREAD

**Issue by LucaBonfiglioli** [Lightning-AI/pytorch-lightning#20077]
### Bug description

When using `setuptools>=67` importing stuff from pytorch lightning results in deprecation warning.

Setuptools 66.1.1 was released in Jan 20 2023. Pytorch Lightning has been using deprecated `pkg_resources` APIs for about 18 months. Is there any chance we can get rid of this in one of the next updates?

Thank you :)

### What version are you seeing the problem on?

master

### How to reproduce the bug

```python
import warnings

warnings.filterwarnings("error")
import pytorch_lightning
```

### Error messages and logs

```
Traceback (most recent call last):
  File "/home/xxx/repos/xxx/xxx.py", line 4, in <module>
    import lightning_utilities.core.imports
  File "/home/xxx/venvs/xxx/lib/python3.10/site-packages/lightning_utilities/__init__.py", line 6, in <module>
    from lightning_utilities.core.apply_func import apply_to_collection
  File "/home/xxx/venvs/xxx/lib/python3.10/site-packages/lightning_utilities/core/__init__.py", line 5, in <module>
    from lightning_utilities.core.imports import compare_version, module_available
  File "/home/xxx/venvs/xxx/lib/python3.10/site-packages/lightning_utilities/core/imports.py", line 14, in <module>
    import pkg_resources
  File "/home/xxx/venvs/xxx/lib/python3.10/site-packages/pkg_resources/__init__.py", line 105, in <module>
    warnings.warn(
DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
```

### Environment

<details>
  <summary>Current environment</summary>

```
#- PyTorch Lightning Version 2.3.3:
#- PyTorch Version 2.3.1:
#- Python version 3.10:
#- OS (e.g., Linux): Ubuntu 22.04
#- CUDA/cuDNN version: 11.8
#- GPU models and configuration: irrelevant
#- How you installed Lightning(`conda`, `pip`, source): pip
```

</details>

**Comment by awaelchli** [comment]
Hey @LucaBonfiglioli 
The deprecation does not originate from PyTorch Lightning. You can see in the trace that it is from `lightning_utilities`. We should fix it there. There is already an issue for it with some discussion: https://github.com/Lightning-AI/utilities/issues/119.

**Comment by LucaBonfiglioli** [comment]
Thank you for your response. Sorry for the dupliate issue.
