### ISSUE TITLE
module statistics has no attribute mean

### ISSUE THREAD

**Issue by FabianKuon** [Lightning-AI/pytorch-lightning#20086]
### Bug description

When updating to the new PyTorch-lightning version 2.3.3 and using the MlFlowLogger as logger arg in the trainer I‘m getting the error trace (see error section)

### What version are you seeing the problem on?

master

### Error messages and logs

```
train.py 9 <module>
import mlflow.pytorch
 
__init__.py 1190 <module>
from mlflow.pytorch._lightning_autolog import MlflowModelCheckpointCallback  # noqa: F401
 
_lightning_autolog.py 24 <module>
import pytorch_lightning as pl
 
__init__.py 27 <module>
from pytorch_lightning.callbacks import Callback  # noqa: E402
 
__init__.py 29 <module>
from pytorch_lightning.callbacks.pruning import ModelPruning
 
pruning.py 32 <module>
from pytorch_lightning.core.module import LightningModule
 
__init__.py 16 <module>
from pytorch_lightning.core.module import LightningModule
 
module.py 62 <module>
from pytorch_lightning.loggers import Logger
 
__init__.py 14 <module>
from pytorch_lightning.loggers.comet import CometLogger
 
comet.py 30 <module>
from pytorch_lightning.loggers.logger import Logger, rank_zero_experiment
 
logger.py 103 <module>
default_func: Callable[[Sequence[float]], float] = statistics.mean,
 
AttributeError:
module 'statistics' has no attribute 'mean'

```

### Environment

<details>
  <summary>Current environment</summary>

```
#- PyTorch Lightning Version (e.g., 1.5.0): 2.3.3
#- PyTorch Version (e.g., 2.0): 2.3.1
#- Python version (e.g., 3.9): 3.11
#- OS (e.g., Linux): MacOS Sonoma 14.5
#- CUDA/cuDNN version:
#- GPU models and configuration:
#- How you installed Lightning(`conda`, `pip`, source): pip
```

</details>

**Comment by awaelchli** [comment]
Hey @FabianKuon 
The statistics module is a standard module in Python and it definitely has a mean function. Could you please check that you don't have a different statistics module in the python path? For example, if you have a `statistics.py` module in your code, it would cause a collision with the standard library package. In this case, please rename or delete it.

**Comment by FabianKuon** [comment]
@awaelchli thank you very much for your quick response. You‘re right I do have a statistics.py file in my repo. Renaming that solved the issue. 

Once again thank you very much

**Comment by awaelchli** [comment]
Perfect!
