### ISSUE TITLE
wandblogger : File handles cannot be properly released

### ISSUE THREAD

**Issue by zhf321** [Lightning-AI/pytorch-lightning#20093]
### Bug description

During the training process, I used WandBLogger to record the experimental results. However, I found that the number of file handles continued to increase during the training process, which led to the continuous accumulation of system resources and eventually caused the program to crash. If you have any suggestions or solutions, please help me solve this problem. Thank you for your help!

### What version are you seeing the problem on?

v2.2

### How to reproduce the bug

```python
None
```

### Error messages and logs

```
# Error messages and logs here please
```

### Environment

#- PyTorch Lightning Version (e.g., 1.5.0):
#- PyTorch Version (e.g., 2.0):
#- Python version (e.g., 3.8):
#- OS (e.g., Linux):
#- CUDA/cuDNN version:
#- GPU models and configuration:
#- How you installed Lightning(`conda`, `pip`, source):

**Comment by awaelchli** [comment]
@zhf321 This is not enough information to investigate. You didn't fill out the report template, so I'm closing the issue. If you provide the infos (notably the code snippet that creates this issue), we can reopen it. However note that Lightning's wrapper around wandb does not open any file handles, it just calls into the wandb api.
