### ISSUE TITLE
Get `num_nodes` automatically

### ISSUE THREAD

**Issue by BakerBunker** [Lightning-AI/pytorch-lightning#20104]
### Description & Motivation

Currently `Trainer`'s `num_nodes` parameter can only be specified manually, and need to manually modify the config every time change the number of nodes when using the Trainer cli.
We can add an `auto` option to `num_nodes` parameter, and get the value via `WORLD_SIZE` parameter.

### Pitch

Add an `auto` option to `num_nodes` parameter, which could get from `WORLD_SIZE` parameter.

### Alternatives

N/A

### Additional context

N/A

cc @borda @justusschock @awaelchli

**Comment by awaelchli** [comment]
@BakerBunker An auto option was on my mind for a long time (https://github.com/Lightning-AI/pytorch-lightning/issues/14078). It will be some work to do this correctly for all cluster environments, but it is in theory possible.

**Comment by BakerBunker** [comment]
Thank you for your explanation, I didn't find that issue, I will close this issue and hope this feature will be implemented :)
