### ISSUE TITLE
Support restoring callbacks' status when predicting

### ISSUE THREAD

**Issue by zihaozou** [Lightning-AI/pytorch-lightning#20137]
### Description & Motivation

I implemented EMA using Callback. However, when predicting, the callback's weight isn't loaded back 

### Pitch

remove the condition at: https://github.com/Lightning-AI/pytorch-lightning/blob/f5d82504da252a255df268bd2bb99bf3f2886d27/src/lightning/pytorch/trainer/connectors/checkpoint_connector.py#L400

cc @borda

**Comment by chualanagit** [comment]
@awaelchli would appreciate a review on this [PR](https://github.com/Lightning-AI/pytorch-lightning/pull/20403), thanks!
