### ISSUE TITLE
mps and manual_seed_all 

### ISSUE THREAD

**Issue by Tonys21** [Lightning-AI/pytorch-lightning#20145]
### Description & Motivation

Hi,
I'm sorry to disturb here but i can't find any information anywhere about this.
I'm struggling with an automatic function used with cuda to have the same seed on both GPU and CPU. 

Here is the function i worked from:

###### Function for setting the seed:

          def set_seed(seed):
              np.random.seed(seed)
              torch.manual_seed(seed)
              if torch.cuda.is_available():
                  torch.cuda.manual_seed(seed)
                  torch.cuda.manual_seed_all(seed)
          set_seed(42)

##### Ensure that all operations are deterministic on GPU (if used) for reproducibility
          torch.backends.cudnn.deterministic = True
          torch.backends.cudnn.benchmark = False

Here is the way i tried to transpose the function for mps:

###### function for setting the seed 
          def set_seed(seed):
              np.random.seed(seed)
              torch.manual_seed(seed)
              if torch.backends.mps.is_available(): # GPU operation have separate seeds
                  torch.mps.manual_seed(seed)
                  torch.mps.manual_seed_all(seed)
              set_seed(42)

But actually (i read the pytorch documentation) it seems the manual_seed_all() function doesn't exist. 
I don't know how to get around this problem and keep my reproductibility using mps. 

If i mute the torch.mps.manual_seed_all() line i have this error:

        ---------------------------------------------------------------------------
        RecursionError                            Traceback (most recent call last)
        Cell In[35], line 6
              4 ## Create a plot for every activation function
              5 for i, act_fn_name in enumerate(act_fn_by_name):
        ----> 6     set_seed(42) # Setting the seed ensures that we have the same weight initialization for each activation function
              7     act_fn = act_fn_by_name[act_fn_name]()
              8     net_actfn = BaseNetwork(act_fn=act_fn).to(device)
        
        Cell In[34], line 13, in set_seed(seed)
             11        torch.mps.manual_seed(seed)
             12 #       torch.mps.manual_seed_all(seed)
        ---> 13    set_seed(42)
        
        Cell In[34], line 13, in set_seed(seed)
             11        torch.mps.manual_seed(seed)
             12 #       torch.mps.manual_seed_all(seed)
        ---> 13    set_seed(42)
        
            [... skipping similar frames: set_seed at line 13 (2957 times)]
        
        Cell In[34], line 13, in set_seed(seed)
             11        torch.mps.manual_seed(seed)
             12 #       torch.mps.manual_seed_all(seed)
        ---> 13    set_seed(42)
        
        Cell In[34], line 9, in set_seed(seed)
              7 def set_seed(seed):
              8     np.random.seed(seed)
        ----> 9     torch.manual_seed(seed)
             10     if torch.backends.mps.is_available(): # GPU operation have separate seeds
             11         torch.mps.manual_seed(seed)
        
        File [/Applications/anaconda3/envs/DL-torch-arm64/lib/python3.10/site-packages/torch/_dynamo/eval_frame.py:451](http://localhost:8889/Applications/anaconda3/envs/DL-torch-arm64/lib/python3.10/site-packages/torch/_dynamo/eval_frame.py#line=450), in _TorchDynamoContext.__call__.<locals>._fn(*args, **kwargs)
            449 prior = set_eval_frame(callback)
            450 try:
        --> 451     return fn(*args, **kwargs)
            452 finally:
            453     set_eval_frame(prior)
        
        File [/Applications/anaconda3/envs/DL-torch-arm64/lib/python3.10/site-packages/torch/_dynamo/external_utils.py:36](http://localhost:8889/Applications/anaconda3/envs/DL-torch-arm64/lib/python3.10/site-packages/torch/_dynamo/external_utils.py#line=35), in wrap_inline.<locals>.inner(*args, **kwargs)
             34 @functools.wraps(fn)
             35 def inner(*args, **kwargs):
        ---> 36     return fn(*args, **kwargs)
        
        File [/Applications/anaconda3/envs/DL-torch-arm64/lib/python3.10/site-packages/torch/random.py:45](http://localhost:8889/Applications/anaconda3/envs/DL-torch-arm64/lib/python3.10/site-packages/torch/random.py#line=44), in manual_seed(seed)
             42 import torch.cuda
             44 if not torch.cuda._is_in_bad_fork():
        ---> 45     torch.cuda.manual_seed_all(seed)
             47 import torch.mps
             48 if not torch.mps._is_in_bad_fork():
        
        File [/Applications/anaconda3/envs/DL-torch-arm64/lib/python3.10/site-packages/torch/cuda/random.py:126](http://localhost:8889/Applications/anaconda3/envs/DL-torch-arm64/lib/python3.10/site-packages/torch/cuda/random.py#line=125), in manual_seed_all(seed)
            123         default_generator = torch.cuda.default_generators[i]
            124         default_generator.manual_seed(seed)
        --> 126 _lazy_call(cb, seed_all=True)
        
        File [/Applications/anaconda3/envs/DL-torch-arm64/lib/python3.10/site-packages/torch/cuda/__init__.py:230](http://localhost:8889/Applications/anaconda3/envs/DL-torch-arm64/lib/python3.10/site-packages/torch/cuda/__init__.py#line=229), in _lazy_call(callable, **kwargs)
            228 global _lazy_seed_tracker
            229 if kwargs.get("seed_all", False):
        --> 230     _lazy_seed_tracker.queue_seed_all(callable, traceback.format_stack())
            231 elif kwargs.get("seed", False):
            232     _lazy_seed_tracker.queue_seed(callable, traceback.format_stack())
        
        File [/Applications/anaconda3/envs/DL-torch-arm64/lib/python3.10/traceback.py:213](http://localhost:8889/Applications/anaconda3/envs/DL-torch-arm64/lib/python3.10/traceback.py#line=212), in format_stack(f, limit)
            211 if f is None:
            212     f = sys._getframe().f_back
        --> 213 return format_list(extract_stack(f, limit=limit))
        
        File [/Applications/anaconda3/envs/DL-torch-arm64/lib/python3.10/traceback.py:227](http://localhost:8889/Applications/anaconda3/envs/DL-torch-arm64/lib/python3.10/traceback.py#line=226), in extract_stack(f, limit)
            225 if f is None:
            226     f = sys._getframe().f_back
        --> 227 stack = StackSummary.extract(walk_stack(f), limit=limit)
            228 stack.reverse()
            229 return stack
        
        File [/Applications/anaconda3/envs/DL-torch-arm64/lib/python3.10/traceback.py:383](http://localhost:8889/Applications/anaconda3/envs/DL-torch-arm64/lib/python3.10/traceback.py#line=382), in StackSummary.extract(klass, frame_gen, limit, lookup_lines, capture_locals)
            381 if lookup_lines:
            382     for f in result:
        --> 383         f.line
            384 return result
        
        File [/Applications/anaconda3/envs/DL-torch-arm64/lib/python3.10/traceback.py:306](http://localhost:8889/Applications/anaconda3/envs/DL-torch-arm64/lib/python3.10/traceback.py#line=305), in FrameSummary.line(self)
            304     if self.lineno is None:
            305         return None
        --> 306     self._line = linecache.getline(self.filename, self.lineno)
            307 return self._line.strip()
        
        File [/Applications/anaconda3/envs/DL-torch-arm64/lib/python3.10/linecache.py:30](http://localhost:8889/Applications/anaconda3/envs/DL-torch-arm64/lib/python3.10/linecache.py#line=29), in getline(filename, lineno, module_globals)
             26 def getline(filename, lineno, module_globals=None):
             27     """Get a line for a Python source file from the cache.
             28     Update the cache if it doesn't contain an entry for this file already."""
        ---> 30     lines = getlines(filename, module_globals)
             31     if 1 <= lineno <= len(lines):
             32         return lines[lineno - 1]
        
        File [/Applications/anaconda3/envs/DL-torch-arm64/lib/python3.10/linecache.py:42](http://localhost:8889/Applications/anaconda3/envs/DL-torch-arm64/lib/python3.10/linecache.py#line=41), in getlines(filename, module_globals)
             40 if filename in cache:
             41     entry = cache[filename]
        ---> 42     if len(entry) != 1:
             43         return cache[filename][2]
             45 try:
        
        RecursionError: maximum recursion depth exceeded while calling a Python object

-------------------------------------------------------------------------------------------------------------------------

Well i'm sorry if my message is not clear of it's a too big demand for a so small use case. 

Thank you for your answer.

I can add informations if need. 

### Pitch

I would like to use:

torch.mps.manual_seed_all

After a night of thinking i'm wondering how mps is considered. 
Is is considered as a GPU? Or as some kind of mix of GPU/CPU. In this second case it seems i maybe wouldn't need the manual_seed_all function because all my processing environment would have the same seed with the torch.mps.manual_seed function. 

BUT it seems i still have this issue with RecursionError. 
And it seems the error comes from the point where torch.cuda.manual_seed_all is imported in line 45 of manual_seed_function. 

Well thank you for your help and answers

### Alternatives

I wish i had the knowledge to do so

### Additional context

active environment : DL-torch-arm64
    active env location : /Applications/anaconda3/envs/DL-torch-arm64
            shell level : 2
       user config file : /Users/.../.condarc
 populated config files : /Users/.../.condarc
          conda version : 24.7.1
    conda-build version : 24.5.1
         python version : 3.12.2.final.0
                 solver : libmamba (default)
       virtual packages : __archspec=1=m1
                          __conda=24.7.1=0
                          __osx=14.5=0
                          __unix=0=0
       base environment : /Applications/anaconda3  (writable)
      conda av data dir : /Applications/anaconda3/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/osx-arm64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/osx-arm64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/osx-arm64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /Applications/anaconda3/pkgs
                          /Users/.../.conda/pkgs
       envs directories : /Applications/anaconda3/envs
                          /Users/.../.conda/envs
               platform : osx-arm64
             user-agent : conda/24.7.1 requests/2.32.2 CPython/3.12.2 Darwin/23.5.0 OSX/14.5 solver/libmamba conda-libmamba-solver/24.1.0 libmambapy/1.5.8 aau/0.4.4 c/. s/. e/.
                UID:GID : 501:20
             netrc file : None
           offline mode : False

cc @borda

**Comment by awaelchli** [comment]
To set the seed on all devices, you can simply call `torch.manual_seed(...)`:
https://github.com/pytorch/pytorch/blob/bdd83c4c7f1ede5f528ffc49ee8eb348f20a26bd/torch/random.py#L32-L60

If the recursion error is from PyTorch, please submit an issue to the PyTorch repo.

**Comment by Tonys21** [comment]
ok thank you i'll try on PyTorch repo then
