### ISSUE TITLE
metrics csv in ddp mode

### ISSUE THREAD

**Issue by ruyanyinian** [Lightning-AI/pytorch-lightning#20371]
### Bug description

It seems like that metrics.csv only log rank 0 when launch ddp mode? Am I able to create  different  metrics.csv for logging different ranks, because I want to log losses in different rank? If so, How?  

### What version are you seeing the problem on?

v2.2

### Error messages and logs

```
# Error messages and logs here please
```

### Environment

<details>
  <summary>Current environment</summary>

```
#- PyTorch Lightning Version (e.g., 2.4.0):
#- PyTorch Version (e.g., 2.4):
#- Python version (e.g., 3.12):
#- OS (e.g., Linux):
#- CUDA/cuDNN version:
#- GPU models and configuration:
#- How you installed Lightning(`conda`, `pip`, source):
```

</details>

**Comment by lantiga** [comment]
By default PyTorch Lightning will save metrics on rank 0, after aggregation.

If you need to save them individually per rank you need to do it manually, either by recording separate metrics, or saving a file from the rank:

```
def training_step(self, batch, batch_idx):
    # Your training logic
    loss = ...
    
    # Log metrics specific to the current rank
    # this will still save metrics on rank 0, but will save separate metrics per rank
    self.log(f"rank_{self.global_rank}_loss", loss, on_step=True, on_epoch=False, sync_dist=True)
    
    # Optionally save metrics to disk directly
    if batch_idx % 100 == 0:  # Save every 100 batches
        with open(f"metrics_rank_{self.global_rank}.txt", "a") as f:
            f.write(f"Step {self.global_step}, Loss: {loss.item()}\n")
    
    return loss
```
