### ISSUE TITLE
Allowing setting timeout in DeepSpeedStrategy

### ISSUE THREAD

**Issue by jedyang97** [Lightning-AI/pytorch-lightning#20466]
### Outline & Motivation

In DDPStrategy / FSDPStrategy, the `timeout=datetime.timedelta(seconds=1800)` flag is exposed and thus allowing user to tune. However, in DeepSpeedStrategy, which is a subclass of DDPStrategy, this flag is not exposed, which makes it hard to change the timeout behavior.

Is there any workaround? Otherwise, I think it might be worth adding `kwargs` to the `__init__()` function of DeepSpeedStrategy, and pass along those parameters to the parent class DDPStrategy.

cc @borda @awaelchli @justusschock

**Comment by lantiga** [comment]
Hey @jedyang97 definitely, do you want to send in a quick PR?
