### ISSUE TITLE
Stop renaming everything, you're annoying. Fix the names of the classes and don't rename them.

### ISSUE THREAD

**Issue by vadinabronin** [Lightning-AI/pytorch-lightning#20465]
### Bug description

description in title

### What version are you seeing the problem on?

v1.x

### How to reproduce the bug

```python

```

### Error messages and logs

```
# Error messages and logs here please
Support for `training_epoch_end` has been removed in v2.0.0. `ResnetTT` implements this method. You can use the `on_train_epoch_end` hook instead. To access outputs, save them in-memory as instance attributes. You can find migration examples in https://github.com/Lightning-AI/lightning/pull/16520.
```

### Environment

<details>
  <summary>Current environment</summary>

```
#- PyTorch Lightning Version (e.g., 2.4.0):
#- PyTorch Version (e.g., 2.4):
#- Python version (e.g., 3.12):
#- OS (e.g., Linux):
#- CUDA/cuDNN version:
#- GPU models and configuration:
#- How you installed Lightning(`conda`, `pip`, source):
```

</details>

### More info

I don't understand what you were on when you replaced it `training_epoch_end` to `on_train_epoch_end`. Are you crazy? Do you understand that this is how many problems with versions arise? what kind of idiot do you have to be to do such crap

**Comment by lantiga** [comment]
1) with 2.0 (March 2023) we made an explicit commitment to stabilize the API and we 100% followed that
https://github.com/Lightning-AI/pytorch-lightning/releases/tag/2.0.0

2) disrespectful language is not tolerated for any reason around here
