### ISSUE TITLE
UnboundLocalError: local variable 'any_on_epoch' referenced before assignment in prediction loop

### ISSUE THREAD

**Issue by farhadrgh** [Lightning-AI/pytorch-lightning#20472]
### Bug description

`UnboundLocalError` raises when using the predict method with `return_predictions=False`.

This is due to `any_on_epoch` [not being defined](https://github.com/Lightning-AI/pytorch-lightning/blob/be608fa355b835b9b0727df2f5476f0a1d90bc59/src/lightning/pytorch/loops/prediction_loop.py#L236) if `data_fetcher` is [an instance](https://github.com/Lightning-AI/pytorch-lightning/blob/be608fa355b835b9b0727df2f5476f0a1d90bc59/src/lightning/pytorch/loops/prediction_loop.py#L229) of `_DataLoaderIterDataFetcher`.

### What version are you seeing the problem on?

v2.4

### Error messages and logs

```
UnboundLocalError: local variable 'any_on_epoch' referenced before assignment
```

### Environment

<details>
  <summary>Current environment</summary>

```
#- PyTorch Lightning Version (e.g., 2.4.0):
#- PyTorch Version (e.g., 2.4):
#- Python version (e.g., 3.12):
#- OS (e.g., Linux):
#- CUDA/cuDNN version:
#- GPU models and configuration:
#- How you installed Lightning(`conda`, `pip`, source):
```

</details>

**Comment by lantiga** [comment]
nice catch

> This is due to any_on_epoch [not being defined](https://github.com/Lightning-AI/pytorch-lightning/blob/be608fa355b835b9b0727df2f5476f0a1d90bc59/src/lightning/pytorch/loops/prediction_loop.py#L236) if data_fetcher is [not an instance](https://github.com/Lightning-AI/pytorch-lightning/blob/be608fa355b835b9b0727df2f5476f0a1d90bc59/src/lightning/pytorch/loops/prediction_loop.py#L229) of _DataLoaderIterDataFetcher.

it's actually the other way around, it errors out when it *is* an instance of `_DataLoaderIterDataFetcher`

the solution is to replace lines 236 and 237:
https://github.com/Lightning-AI/pytorch-lightning/blob/be608fa355b835b9b0727df2f5476f0a1d90bc59/src/lightning/pytorch/loops/prediction_loop.py#L236-L237

with

```python
any_on_epoch = self._store_data_for_prediction_writer(batch_idx, dataloader_idx) if not using_dataloader_iter else False
```

Would you like to volunteer for a quite PR?

**Comment by farhadrgh** [comment]
Thanks, Yes, I just fixed the issue description as well.
