### ISSUE TITLE
Lost Acess to all my Teamspace Studios

### ISSUE THREAD

**Issue by arslanmzahid** [Lightning-AI/pytorch-lightning#20522]
### Bug description

I am working on some studios on my account and have lost access to all the studios. I lost aces to all my studios and now the page just returns a 404 error. 

I have 2 to 3months of work on these studios and I really need to access them inorder to complete the pending work. 

Please look in to this matter for me. 

Regards 
Arslan

<img width="1440" alt="Screenshot 2024-12-26 at 9 10 15 PM" src="https://github.com/user-attachments/assets/57878c3c-e86b-412f-a59e-d87d5d240c80" />

### What version are you seeing the problem on?

master

### Error messages and logs

```
# Error messages and logs here please
```

### Environment

<details>
  <summary>Current environment</summary>

```
#- PyTorch Lightning Version (e.g., 2.5.0):
#- PyTorch Version (e.g., 2.5):
#- Python version (e.g., 3.12):
#- OS (e.g., Linux):
#- CUDA/cuDNN version:
#- GPU models and configuration:
#- How you installed Lightning(`conda`, `pip`, source):
```

</details>

**Comment by divymurli** [comment]
I'm having the same problem!!

**Comment by lantiga** [comment]
Please post Studio issues here https://www.reddit.com/r/lightningAI
