### ISSUE TITLE
Ability to build docs without relying on pytorch tutorials section

### ISSUE THREAD

**Issue by satishjasthi** [Lightning-AI/pytorch-lightning#8189]
Currently when I cloned the PL repo and tried to build docs to resolve some issues wrt docs, the 
`
make html 
`
command fails because of dependencies issues which are related to tutorials section in docs/config.py
Based on discussion with @Borda Its would be better if we can make the docs section independent of tutorials.

This issues tries to remove the dependencies between docs and tutorials, so that we can build the docs independently

**Comment by satishjasthi** [comment]
@Borda  I have started working on this issue, Ill submit a PR as soon as possible

**Comment by Borda** [comment]
@satishjasthi how is it going?

**Comment by awaelchli** [comment]
The command was recently changed so that by default, `make docs` runs in "fast" mode without the need to render the tutorials. So this should be resolved now :)
