### ISSUE TITLE
loading large model not finished after 16 hours

### ISSUE THREAD

**Issue by mijosch** [Lightning-AI/pytorch-lightning#9928]
## 🐛 Bug

After saving a checkpoint of a large pytorch_forecasting model (10'100 targets forecasting based on previous 10'000 values ), loading the checkpoint lasts forever (i killed loading after 16 hours).

With 5 targets forecasting based on previous 5 values -> works
With 50 targets forecasting based on previous 50 values -> works
With 500 targets forecasting based on previous 500 values -> works
With 5000 targets forecasting based on previous 5000 values -> in test

Atm. trying to find the amount where it stops working.

### To Reproduce

The model hast 10'100 target values, the prediction is 24 time intervals based on 48 past time intervals.
The predictions are quantiles(0.25,0.5,0.75)

### Expected behavior

the model can be loaded in a reasonable timeframe.

### Environment

- PyTorch 1.4.9
- PyTorch 1.9.1
- Python version: 3.8.10
- OS (e.g., Linux): Ubuntu 20.04
- CUDA/cuDNN version: -
- GPU models and configuration: -
- How you installed PyTorch (`conda`, `pip`, source): pip

### Additional context

Loading and saving of small models works well.

**Comment by justusschock** [comment]
I see, can you try to do it with a torch.nn.Module as a baseclass instead? just to see if this is something we are doing different from the original pytorch code?

**Comment by mijosch** [comment]
I have other models in pure pytorch with custom written training loops that have the size of about 200MB and never had issues with loading them but they are just fully convolutional models with maybe less keys in the state_dict. The one here is a temporal fusion transformer and I dont know the structure of it.

But I dont think that the size is the problem, I think the key count is the issue.
The 2 targets from 2 columns already has 292 keys in the state_dict.
The 10 targets from 10 columns already has 668 keys in the state_dict.
The 100 targets from 100 columns already has 4898 keys in the state_dict.
The 1000 targets from 1000 columns already has 47198 keys in the state_dict.

The increase in keys is also some what linear I guess.

Loading the pickle from drive does not work in parallel but cant you assign the state_dict in parallel? 
I think one reason for being slow is, that the function does just use one thread (one CPU core is at 100% the rest is idling around). 
So using a threadpoolexecutor and start a thread for each key in the state_dict might be an improvement.
Is this a topic for pytorch?

**Comment by justusschock** [comment]
Hi sorry for the late response. I just double checked and we are not doing anything special here. We just rely on the function provided by pytorch, so I do think it would be best if you open an issue with them :)
