### ISSUE TITLE
Support `str(datamodule)`

### ISSUE THREAD

**Issue by carmocca** [Lightning-AI/pytorch-lightning#9947]
## 🚀 Feature

Add support

```python
print(str(MyDataModule()))
```

### Motivation

It currently prints:

```python
<__main__.MyDataModule object at 0x10284c970>
```

### Pitch

It could print the DataLoader structure:

```python
MyDataModule(
    train_dataloader: {"a": DataLoaderClass(batch_size=8, num_batches=16, num_workers=2), "b":  DataLoaderClass(batch_size=2, num_batches=16, num_workers=2)]
    val_dataloader: [DataLoaderClass(batch_size=3, num_batches=14, num_workers=0), DataLoaderClass(batch_size=8, num_batches=4, num_workers=0)]
    test_dataloader: DataLoaderClass(batch_size=4, num_batches=7, num_workers=2)
)
```

Or the number of batches per dataloader, similar to what was done in https://github.com/PyTorchLightning/pytorch-lightning/issues/5965

### Alternatives

Open to other ideas

______________________________________________________________________

#### If you enjoy Lightning, check out our other projects! ⚡

<sub>

- [**Metrics**](https://github.com/PyTorchLightning/metrics): Machine learning metrics for distributed, scalable PyTorch applications.

- [**Flash**](https://github.com/PyTorchLightning/lightning-flash): The fastest way to get a Lightning baseline! A collection of tasks for fast prototyping, baselining, finetuning and solving problems with deep learning

- [**Bolts**](https://github.com/PyTorchLightning/lightning-bolts): Pretrained SOTA Deep Learning models, callbacks and more for research and production with PyTorch Lightning and PyTorch

- [**Lightning Transformers**](https://github.com/PyTorchLightning/lightning-transformers): Flexible interface for high performance research using SOTA Transformers leveraging Pytorch Lightning, Transformers, and Hydra.

</sub>

**Comment by Abelarm** [comment]
> Hi guys I am currently at a problem between: ![Screenshot 2021-10-16 at 20 01 05](https://user-images.githubusercontent.com/6976921/137597611-e60a2098-83f7-47b2-b00f-4a10a7369701.png)
> 
> and
> 
> ![Screenshot 2021-10-16 at 20 20 09](https://user-images.githubusercontent.com/6976921/137598127-58bf9360-1ea8-4f15-b230-3eed2682ab81.png) *
> 
> *which is not consistent on the prints.
> 
> the problem is the str() of the dict :(
> 
> Do you have any idea? or one of the two solutions is good enough?

if you really want the keys of the dict to be with "" I can do it but I won't be the nicest of the solutions

**Comment by carmocca** [comment]
The main reason for the revertion of `len` was the impact to existing truthiness checks. That should not be a problem for `str`.

@ananthsub do you think the rest of the points you raised in https://github.com/PyTorchLightning/pytorch-lightning/issues/5965#issuecomment-948862064 are worth dropping this feature? We would still have the problem of initialization.

**Comment by Abelarm** [comment]
> in the spirit of https://docs.python.org/3.4/reference/datamodel.html#object.__repr__
> 
> > If at all possible, this should look like a valid Python expression that could be used to recreate an object with the same value (given an appropriate environment).
> 
> I recommend:
> 
> 1. keeping the quotes around dict keys but not dict values
> 2. using an `=` after the name of initialization parameters instead of a `:`
> 
> Following these recommendations, @Abelarm 's test expression would become:
> 
> ```
> MyDataModule(
>     train_dataloader={"a": DataLoaderClass(batch_size=8, num_batches=16, num_workers=2), "b":  DataLoaderClass(batch_size=2, num_batches=16, num_workers=2)]
>     val_dataloader=[DataLoaderClass(batch_size=3, num_batches=14, num_workers=0), DataLoaderClass(batch_size=8, num_batches=4, num_workers=0)]
>     test_dataloader=DataLoaderClass(batch_size=4, num_batches=7, num_workers=2)
> )
> ```

in my pr I already go : instead of =  but I am struggling to add "" around keys dict :(

**Comment by MrWhatZitToYaa** [comment]
It seems like this feature is still not implemented. Would it be possible to work in this issue?
